package main

import (
	"bytes"
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// renderInventory produces docs/IMPLEMENTATION_INVENTORY.md from the codelet
// spec table, so the inventory can never drift from the actual registrations.
// Non-codelet coverage (generic SIMD kernels, the 386 tier, the pure-Go
// algorithm families) is described in a static section below, maintained here
// alongside the dispatch code it describes.

// simdColumns is the column order of the quick-reference grids.
//
//nolint:gochecknoglobals // static configuration for the inventory renderer
var simdColumns = []string{"SIMDNone", "SIMDSSE2", "SIMDSSE3", "SIMDAVX2", "SIMDAVX512", "SIMDNEON"}

//nolint:gochecknoglobals // static configuration for the inventory renderer
var simdColumnNames = map[string]string{
	"SIMDNone":   "Go",
	"SIMDSSE2":   "SSE2",
	"SIMDSSE3":   "SSE3",
	"SIMDAVX2":   "AVX2",
	"SIMDAVX512": "AVX-512",
	"SIMDNEON":   "NEON",
}

// variantNames maps the signature-derived variant token to a display name.
//
//nolint:gochecknoglobals // static configuration for the inventory renderer
var variantNames = map[string]string{
	"radix2":              "Radix-2",
	"radix4":              "Radix-4",
	"radix8":              "Radix-8",
	"radix16":             "Radix-16",
	"radix32":             "Radix-32",
	"radix4_then2":        "Mixed-2/4",
	"radix4_then2_params": "Mixed-2/4",
	"mixedradix":          "Mixed-2/4",
	"radix16x32":          "Radix-16×32",
	"radix32x32":          "Radix-32×32",
	"mixed":               "Mixed 128×3",
	"sixstep":             "Six-step",
	"sixstep64x128":       "Six-step 64×128",
	"generic":             "Generic radix-2",
}

var signatureRe = regexp.MustCompile(`^dit[0-9]+_(.+)_(generic|avx2|avx512|sse2|sse3|neon)$`)

// variantOf derives the display variant from a codelet signature.
func variantOf(sig string) string {
	m := signatureRe.FindStringSubmatch(sig)
	if m == nil {
		return sig
	}

	if name, ok := variantNames[m[1]]; ok {
		return name
	}

	return m[1]
}

type gridKey struct {
	size    int
	variant string
}

func renderInventory() []byte {
	var b bytes.Buffer

	b.WriteString("# FFT Implementation Inventory\n\n")
	b.WriteString("<!-- Code generated by cmd/gencodelets from cmd/gencodelets/specs.go; DO NOT EDIT.\n")
	b.WriteString("     Regenerate with: go generate ./internal/kernels/... -->\n\n")
	b.WriteString("This document inventories the size-specific FFT codelets registered by\n")
	b.WriteString("`internal/kernels` (source of truth: the declarative table in\n")
	b.WriteString("`cmd/gencodelets/specs.go`) and summarizes the non-codelet kernel tiers.\n")
	b.WriteString("SIMD kernels are part of the **default build** and are selected at runtime\n")
	b.WriteString("via `internal/cpu.DetectFeatures()`; build with `-tags purego` for the\n")
	b.WriteString("pure-Go fallback.\n\n")

	for _, prec := range []int{64, 128} {
		fmt.Fprintf(&b, "## Codelet Quick Reference — complex%d\n\n", prec)
		renderGrid(&b, prec)
	}

	renderCounts(&b)
	renderStaticSections(&b)

	return b.Bytes()
}

// renderGrid writes the size × SIMD-level grid for one precision.
func renderGrid(b *bytes.Buffer, prec int) {
	cells := map[gridKey]map[string]bool{}

	var keys []gridKey

	for _, s := range codeletSpecs {
		if s.Prec != prec {
			continue
		}

		k := gridKey{size: s.Size, variant: variantOf(s.Signature)}
		if cells[k] == nil {
			cells[k] = map[string]bool{}

			keys = append(keys, k)
		}

		cells[k][s.SIMDLevel] = true
	}

	sort.Slice(keys, func(i, j int) bool {
		if keys[i].size != keys[j].size {
			return keys[i].size < keys[j].size
		}

		return keys[i].variant < keys[j].variant
	})

	b.WriteString("| Size | Algorithm |")

	for _, c := range simdColumns {
		fmt.Fprintf(b, " %s |", simdColumnNames[c])
	}

	b.WriteString("\n|---:|---|")

	for range simdColumns {
		b.WriteString(":---:|")
	}

	b.WriteString("\n")

	for _, k := range keys {
		fmt.Fprintf(b, "| %d | %s |", k.size, k.variant)

		for _, c := range simdColumns {
			mark := "-"
			if cells[k][c] {
				mark = "✓"
			}

			fmt.Fprintf(b, " %s |", mark)
		}

		b.WriteString("\n")
	}

	b.WriteString("\n✓ = registered codelet (forward + inverse); - = not registered.\n\n")
}

// renderCounts writes the per-target registration counts.
func renderCounts(b *bytes.Buffer) {
	b.WriteString("## Registration Counts\n\n")
	b.WriteString("| Target | Build constraint | complex64 | complex128 | Total |\n")
	b.WriteString("|---|---|---:|---:|---:|\n")

	total := 0

	for _, tgt := range targets {
		n64 := len(specsFor(tgt.kind, 64))
		n128 := len(specsFor(tgt.kind, 128))
		total += n64 + n128

		tag := tgt.buildTag
		if tag == "" {
			tag = "(all builds)"
		}

		fmt.Fprintf(b, "| %s | `%s` | %d | %d | %d |\n", tgt.kind, tag, n64, n128, n64+n128)
	}

	fmt.Fprintf(b, "\nTotal registered codelets: **%d**.\n\n", total)
}

// renderStaticSections describes kernel coverage that lives outside the
// codelet registry. Keep this in sync with internal/fft dispatch.
func renderStaticSections(b *bytes.Buffer) {
	b.WriteString(strings.TrimLeft(`
## Beyond the Codelet Registry

Codelets cover the tuned size-specific fast paths. Everything else is served
by these tiers, in dispatch order:

1. **Generic SIMD kernels** (internal/fft dispatch, internal/asm):
   size-generic DIT and Stockham kernels for AVX-512 / AVX2 / SSE3 / SSE2 on
   amd64, NEON on arm64, and SSE2/SSE3 on 386. These serve every power-of-two
   size without a registered codelet (on amd64 the AVX-512 tier also serves
   all Stockham-resolved sizes; see internal/fft/kernels_amd64_avx512.go).
2. **386 size-specific kernels** (internal/asm/x86, dispatched via
   internal/fft/kernels_386_asm.go): SSE2/SSE3 kernels for sizes 2/4/8/16,
   including the size-16 radix-16 variant.
3. **Pure-Go algorithm families** (internal/kernels, internal/transform):
   DIT, Stockham, mixed-radix 2/3/5/7/11, Bluestein (arbitrary lengths),
   six-step/eight-step (large sizes), and recursive decomposition — both
   precisions, every platform, and the only tier under -tags purego.

Higher plan-level features (real FFT, 2D/3D/N-D, batch/strided, convolution)
compose these 1D kernels; see README.md and PLAN.md.

## Testing

Every registered codelet is validated per-direction against the naive
reference DFT (internal/reference), plus round-trip and in-place coverage;
a meta-test asserts every signature has reference coverage
(internal/kernels/codelet_roundtrip_all_test.go). SIMD and pure-Go paths are
cross-checked in CI on amd64, 386, and arm64 (QEMU).
`, "\n"))
}
