package main

// NEON (arm64) rows of the codelet registration table. Kept in a separate
// file from specs.go only to respect the repository file-length limit;
// the table is still one logical unit and is concatenated in init().

//nolint:gochecknoglobals // the codelet table is the generator's declarative input
var codeletSpecsNEON = []codeletSpec{
	{
		Target: "neon", Prec: 64, Size: 4,
		Forward:   "arm64.ForwardNEONSize4Radix4Complex64Asm",
		Inverse:   "arm64.InverseNEONSize4Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit4_radix4_neon", Priority: 10,
	},
	{
		Target: "neon", Prec: 64, Size: 8,
		Forward:   "arm64.ForwardNEONSize8Radix2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize8Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit8_radix2_neon", Priority: 20,
	},
	{
		Target: "neon", Prec: 64, Size: 8,
		Forward:   "arm64.ForwardNEONSize8Radix4Complex64Asm",
		Inverse:   "arm64.InverseNEONSize8Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit8_radix4_neon", Priority: 25,
	},
	{
		Target: "neon", Prec: 64, Size: 8,
		Forward:   "arm64.ForwardNEONSize8Radix8Complex64Asm",
		Inverse:   "arm64.InverseNEONSize8Radix8Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeCore",
		Signature: "dit8_radix8_neon", Priority: 30,
	},
	{
		Target: "neon", Prec: 64, Size: 16,
		Forward:   "arm64.ForwardNEONSize16Radix2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize16Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix2_neon", Priority: 22,
	},
	{
		Target: "neon", Prec: 64, Size: 16,
		Forward:   "arm64.ForwardNEONSize16Radix4Complex64Asm",
		Inverse:   "arm64.InverseNEONSize16Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix4_neon", Priority: 28,
	},
	{
		Target: "neon", Prec: 64, Size: 32,
		Forward:   "arm64.ForwardNEONSize32Radix2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize32Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix2_neon", Priority: 20,
	},
	{
		Target: "neon", Prec: 64, Size: 32,
		Forward:   "arm64.ForwardNEONSize32Radix4Then2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize32Radix4Then2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix4_then2_neon", Priority: 24,
	},
	{
		Target: "neon", Prec: 64, Size: 64,
		Forward:   "arm64.ForwardNEONSize64Radix2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize64Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix2_neon", Priority: 22,
	},
	{
		Target: "neon", Prec: 64, Size: 128,
		Forward:   "arm64.ForwardNEONSize128Radix2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize128Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix2_neon", Priority: 20,
	},
	{
		Target: "neon", Prec: 64, Size: 128,
		Forward:   "arm64.ForwardNEONSize128Radix4Then2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize128Radix4Then2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix4_then2_neon", Priority: 24,
	},
	{
		Target: "neon", Prec: 64, Size: 256,
		Forward:   "arm64.ForwardNEONSize256Radix2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize256Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix2_neon", Priority: 18,
	},
	{
		Target: "neon", Prec: 64, Size: 256,
		Forward:   "arm64.ForwardNEONSize256Radix4Complex64Asm",
		Inverse:   "arm64.InverseNEONSize256Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix4_neon", Priority: 28,
	},
	{
		Target: "neon", Prec: 64, Size: 512,
		Forward:   "arm64.ForwardNEONComplex64Asm",
		Inverse:   "arm64.InverseNEONComplex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix2_neon", Priority: 1,
	},
	{
		Target: "neon", Prec: 64, Size: 512,
		Forward:   "arm64.ForwardNEONSize512Radix4Then2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize512Radix4Then2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix4_then2_neon", Priority: 24,
	},
	{
		Target: "neon", Prec: 64, Size: 1024,
		Forward:   "arm64.ForwardNEONComplex64Asm",
		Inverse:   "arm64.InverseNEONComplex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit1024_radix2_neon", Priority: 1,
	},
	{
		Target: "neon", Prec: 64, Size: 1024,
		Forward:   "arm64.ForwardNEONSize1024Radix4Complex64Asm",
		Inverse:   "arm64.InverseNEONSize1024Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit1024_radix4_neon", Priority: 28,
	},
	{
		Target: "neon", Prec: 64, Size: 2048,
		Forward:   "arm64.ForwardNEONSize2048Radix4Then2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize2048Radix4Then2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit2048_radix4_then2_neon", Priority: 24,
	},
	{
		Target: "neon", Prec: 64, Size: 4096,
		Forward:   "arm64.ForwardNEONSize4096Radix4Complex64Asm",
		Inverse:   "arm64.InverseNEONSize4096Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit4096_radix4_neon", Priority: 28,
	},
	{
		Target: "neon", Prec: 64, Size: 8192,
		Forward:   "arm64.ForwardNEONSize8192Radix4Then2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize8192Radix4Then2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit8192_radix4_then2_neon", Priority: 24,
	},
	{
		Target: "neon", Prec: 64, Size: 16384,
		Forward:   "arm64.ForwardNEONSize16384Radix4Complex64Asm",
		Inverse:   "arm64.InverseNEONSize16384Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit16384_radix4_neon", Priority: 28,
	},
	{
		Target: "neon", Prec: 64, Size: 32768,
		Forward:   "arm64.ForwardNEONSize32768Radix4Then2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize32768Radix4Then2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit32768_radix4_then2_neon", Priority: 24,
	},
	{
		Target: "neon", Prec: 128, Size: 4,
		Forward:   "arm64.ForwardNEONSize4Radix4Complex128Asm",
		Inverse:   "arm64.InverseNEONSize4Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit4_radix4_neon", Priority: 10,
	},
	{
		Target: "neon", Prec: 128, Size: 8,
		Forward:   "arm64.ForwardNEONSize8Radix2Complex128Asm",
		Inverse:   "arm64.InverseNEONSize8Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit8_radix2_neon", Priority: 20,
	},
	{
		Target: "neon", Prec: 128, Size: 8,
		Forward:   "arm64.ForwardNEONSize8Radix4Complex128Asm",
		Inverse:   "arm64.InverseNEONSize8Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit8_radix4_neon", Priority: 25,
	},
	{
		Target: "neon", Prec: 128, Size: 16,
		Forward:   "arm64.ForwardNEONSize16Complex128Asm",
		Inverse:   "arm64.InverseNEONSize16Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix2_neon", Priority: 22,
	},
	{
		Target: "neon", Prec: 128, Size: 16,
		Forward:   "arm64.ForwardNEONSize16Radix4Complex128Asm",
		Inverse:   "arm64.InverseNEONSize16Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix4_neon", Priority: 28,
	},
	{
		Target: "neon", Prec: 128, Size: 32,
		Forward:   "arm64.ForwardNEONComplex128Asm",
		Inverse:   "arm64.InverseNEONComplex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit32_generic_neon", Priority: 1,
	},
	{
		Target: "neon", Prec: 128, Size: 32,
		Forward:   "arm64.ForwardNEONSize32Complex128Asm",
		Inverse:   "arm64.InverseNEONSize32Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix2_neon", Priority: 20,
	},
	{
		Target: "neon", Prec: 128, Size: 32,
		Forward:   "arm64.ForwardNEONSize32Radix4Then2Complex128Asm",
		Inverse:   "arm64.InverseNEONSize32Radix4Then2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix4_then2_neon", Priority: 24,
	},
	{
		Target: "neon", Prec: 128, Size: 64,
		Forward:   "arm64.ForwardNEONSize64Radix2Complex128Asm",
		Inverse:   "arm64.InverseNEONSize64Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix2_neon", Priority: 20,
	},
	{
		Target: "neon", Prec: 128, Size: 64,
		Forward:   "arm64.ForwardNEONSize64Radix4Complex128Asm",
		Inverse:   "arm64.InverseNEONSize64Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix4_neon", Priority: 24,
	},
	{
		Target: "neon", Prec: 128, Size: 128,
		Forward:   "arm64.ForwardNEONSize128Radix2Complex128Asm",
		Inverse:   "arm64.InverseNEONSize128Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix2_neon", Priority: 20,
	},
	{
		Target: "neon", Prec: 128, Size: 128,
		Forward:   "arm64.ForwardNEONSize128Radix4Then2Complex128Asm",
		Inverse:   "arm64.InverseNEONSize128Radix4Then2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix4_then2_neon", Priority: 24,
	},
	{
		Target: "neon", Prec: 128, Size: 256,
		Forward:   "arm64.ForwardNEONSize256Radix2Complex128Asm",
		Inverse:   "arm64.InverseNEONSize256Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix2_neon", Priority: 18,
	},
	{
		Target: "neon", Prec: 128, Size: 256,
		Forward:   "arm64.ForwardNEONSize256Radix4Complex128Asm",
		Inverse:   "arm64.InverseNEONSize256Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix4_neon", Priority: 28,
	},
	{
		Target: "neon", Prec: 128, Size: 512,
		Forward:   "arm64.ForwardNEONSize512Radix4Then2Complex128Asm",
		Inverse:   "arm64.InverseNEONSize512Radix4Then2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix4_then2_neon", Priority: 24,
	},
	{
		Target: "neon", Prec: 128, Size: 512,
		Forward:   "arm64.ForwardNEONComplex128Asm",
		Inverse:   "arm64.InverseNEONComplex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit512_generic_neon", Priority: 1,
	},
	{
		Target: "neon", Prec: 128, Size: 1024,
		Forward:   "arm64.ForwardNEONSize1024Radix4Complex128Asm",
		Inverse:   "arm64.InverseNEONSize1024Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit1024_radix4_neon", Priority: 28,
	},
	{
		Target: "neon", Prec: 128, Size: 2048,
		Forward:   "arm64.ForwardNEONSize2048Radix4Then2Complex128Asm",
		Inverse:   "arm64.InverseNEONSize2048Radix4Then2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit2048_radix4_then2_neon", Priority: 24,
	},
	{
		Target: "neon", Prec: 128, Size: 4096,
		Forward:   "arm64.ForwardNEONSize4096Radix4Complex128Asm",
		Inverse:   "arm64.InverseNEONSize4096Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit4096_radix4_neon", Priority: 28,
	},
	{
		Target: "neon", Prec: 128, Size: 8192,
		Forward:   "arm64.ForwardNEONSize8192Radix4Then2Complex128Asm",
		Inverse:   "arm64.InverseNEONSize8192Radix4Then2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit8192_radix4_then2_neon", Priority: 24,
	},
	{
		Target: "neon", Prec: 128, Size: 16384,
		Forward:   "arm64.ForwardNEONSize16384Radix4Complex128Asm",
		Inverse:   "arm64.InverseNEONSize16384Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit16384_radix4_neon", Priority: 28,
	},
	{
		Target: "neon", Prec: 128, Size: 32768,
		Forward:   "arm64.ForwardNEONSize32768Radix4Then2Complex128Asm",
		Inverse:   "arm64.InverseNEONSize32768Radix4Then2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit32768_radix4_then2_neon", Priority: 24,
	},
}

func init() {
	codeletSpecs = append(codeletSpecs, codeletSpecsNEON...)
}
