package main

// codeletSpec is one declarative row of the codelet registration table. It is
// the single source of truth for the built-in codelets; the generator turns it
// into the register*DITCodelets{64,128} functions in internal/kernels.
//
// This table was seeded by AST-extracting the original hand-written
// codelet_init*.go files. To add or retune a codelet, edit a row here (or add
// one) and run `go generate ./internal/kernels/...`.
type codeletSpec struct {
	// Target selects the output file / build tag: "generic", "avx2", "avx512", "sse2", "neon".
	Target string
	// Prec is 64 or 128 (complex64 / complex128).
	Prec int
	// Size is the FFT length the codelet handles.
	Size int
	// Forward / Inverse are kernel expressions matching the CodeletFunc
	// signature (bool-returning; the codelet reports whether it handled the
	// transform).
	Forward string
	Inverse string
	// Algorithm, SIMDLevel, KernelType are planner enum identifiers.
	Algorithm  string
	SIMDLevel  string
	KernelType string
	// Signature is the human-readable codelet name (used for wisdom lookups).
	Signature string
	// Priority breaks ties within a (Size, SIMDLevel); higher wins, negative disables.
	Priority int
	// TwiddleSize / PrepareTwiddle are optional identifiers for codelets that
	// need a custom twiddle layout; empty when unused.
	TwiddleSize    string
	PrepareTwiddle string
}

//nolint:gochecknoglobals // the codelet table is the generator's declarative input
var codeletSpecs = []codeletSpec{
	{
		Target: "generic", Prec: 64, Size: 4,
		Forward:   "forwardDIT4Radix4Complex64",
		Inverse:   "inverseDIT4Radix4Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeCore",
		Signature: "dit4_radix4_generic", Priority: 0,
	},
	{
		Target: "generic", Prec: 64, Size: 8,
		Forward:   "forwardDIT8Radix2Complex64",
		Inverse:   "inverseDIT8Radix2Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit8_radix2_generic", Priority: 20,
	},
	{
		Target: "generic", Prec: 64, Size: 8,
		Forward:   "forwardDIT8Radix8Complex64",
		Inverse:   "inverseDIT8Radix8Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeCore",
		Signature: "dit8_radix8_generic", Priority: 30,
	},
	{
		Target: "generic", Prec: 64, Size: 8,
		Forward:   "forwardDIT8Radix4Complex64",
		Inverse:   "inverseDIT8Radix4Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit8_mixedradix_generic", Priority: 25,
	},
	{
		Target: "generic", Prec: 64, Size: 16,
		Forward:   "forwardDIT16Radix2Complex64",
		Inverse:   "inverseDIT16Radix2Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix2_generic", Priority: 10,
	},
	{
		Target: "generic", Prec: 64, Size: 16,
		Forward:   "forwardDIT16Radix4Complex64",
		Inverse:   "inverseDIT16Radix4Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix4_generic", Priority: 20,
	},
	{
		Target: "generic", Prec: 64, Size: 16,
		Forward:   "forwardDIT16Radix16Complex64",
		Inverse:   "inverseDIT16Radix16Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix16_generic", Priority: 30,
	},
	{
		Target: "generic", Prec: 64, Size: 32,
		Forward:   "forwardDIT32Radix2Complex64",
		Inverse:   "inverseDIT32Radix2Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix2_generic", Priority: 0,
	},
	{
		Target: "generic", Prec: 64, Size: 32,
		Forward:   "forwardDIT32Radix4Then2Complex64",
		Inverse:   "inverseDIT32Radix4Then2Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix4_then2_generic", Priority: 10,
	},
	{
		Target: "generic", Prec: 64, Size: 32,
		Forward:   "forwardDIT32Radix32Complex64",
		Inverse:   "inverseDIT32Radix32Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeCore",
		Signature: "dit32_radix32_generic", Priority: 5,
	},
	{
		Target: "generic", Prec: 64, Size: 64,
		Forward:   "forwardDIT64Radix2Complex64",
		Inverse:   "inverseDIT64Radix2Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix2_generic", Priority: 0,
	},
	{
		Target: "generic", Prec: 64, Size: 64,
		Forward:   "forwardDIT64Radix4Complex64",
		Inverse:   "inverseDIT64Radix4Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix4_generic", Priority: 20,
	},
	{
		Target: "generic", Prec: 64, Size: 128,
		Forward:   "forwardDIT128Radix2Complex64",
		Inverse:   "inverseDIT128Radix2Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix2_generic", Priority: 0,
	},
	{
		Target: "generic", Prec: 64, Size: 128,
		Forward:   "forwardDIT128Radix4Then2Complex64",
		Inverse:   "inverseDIT128Radix4Then2Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix4_then2_generic", Priority: 15,
	},
	{
		Target: "generic", Prec: 64, Size: 256,
		Forward:   "forwardDIT256Complex64",
		Inverse:   "inverseDIT256Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix2_generic", Priority: 10,
	},
	{
		Target: "generic", Prec: 64, Size: 256,
		Forward:   "forwardDIT256Radix4Complex64",
		Inverse:   "inverseDIT256Radix4Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix4_generic", Priority: 20,
	},
	{
		Target: "generic", Prec: 64, Size: 256,
		Forward:   "forwardDIT256Radix16Complex64",
		Inverse:   "inverseDIT256Radix16Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix16_generic", Priority: 30,
	},
	{
		Target: "generic", Prec: 64, Size: 384,
		Forward:   "forwardDIT384MixedComplex64",
		Inverse:   "inverseDIT384MixedComplex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit384_mixed_generic", Priority: 20,
	},
	{
		Target: "generic", Prec: 64, Size: 512,
		Forward:   "forwardDIT512Complex64",
		Inverse:   "inverseDIT512Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix2_generic", Priority: 10,
	},
	{
		Target: "generic", Prec: 64, Size: 512,
		Forward:   "forwardDIT512Radix8Complex64",
		Inverse:   "inverseDIT512Radix8Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix8_generic", Priority: 30,
	},
	{
		Target: "generic", Prec: 64, Size: 512,
		Forward:   "forwardDIT512Radix4Then2Complex64",
		Inverse:   "inverseDIT512Radix4Then2Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix4_then2_generic", Priority: 45,
	},
	{
		Target: "generic", Prec: 64, Size: 512,
		Forward:   "forwardDIT512Mixed16x32Complex64",
		Inverse:   "inverseDIT512Mixed16x32Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix16x32_generic", Priority: 35,
	},
	{
		Target: "generic", Prec: 64, Size: 1024,
		Forward:   "forwardDIT1024Radix4Complex64",
		Inverse:   "inverseDIT1024Radix4Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit1024_radix4_generic", Priority: 15,
	},
	{
		Target: "generic", Prec: 64, Size: 1024,
		Forward:   "forwardDIT1024Mixed32x32Complex64",
		Inverse:   "inverseDIT1024Mixed32x32Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit1024_radix32x32_generic", Priority: 25,
	},
	{
		Target: "generic", Prec: 64, Size: 2048,
		Forward:   "forwardDIT2048Radix4Then2Complex64",
		Inverse:   "inverseDIT2048Radix4Then2Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit2048_radix4_then2_generic", Priority: 20,
	},
	{
		Target: "generic", Prec: 64, Size: 4096,
		Forward:   "forwardDIT4096Radix4Complex64",
		Inverse:   "inverseDIT4096Radix4Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit4096_radix4_generic", Priority: 15,
	},
	{
		Target: "generic", Prec: 64, Size: 4096,
		Forward:   "forwardDIT4096SixStepComplex64",
		Inverse:   "inverseDIT4096SixStepComplex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit4096_sixstep_generic", Priority: 25,
	},
	{
		Target: "generic", Prec: 64, Size: 8192,
		Forward:   "forwardDIT8192Radix4Then2Complex64",
		Inverse:   "inverseDIT8192Radix4Then2Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit8192_radix4_then2_generic", Priority: 20,
	},
	{
		Target: "generic", Prec: 64, Size: 8192,
		Forward:   "forwardDIT8192SixStep64x128Complex64",
		Inverse:   "inverseDIT8192SixStep64x128Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit8192_sixstep64x128_generic", Priority: 30,
	},
	{
		Target: "generic", Prec: 64, Size: 16384,
		Forward:   "forwardDIT16384Radix4Complex64",
		Inverse:   "inverseDIT16384Radix4Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit16384_radix4_generic", Priority: 15,
	},
	{
		Target: "generic", Prec: 64, Size: 16384,
		Forward:   "forwardDIT16384SixStepComplex64",
		Inverse:   "inverseDIT16384SixStepComplex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit16384_sixstep_generic", Priority: 25,
	},
	{
		Target: "generic", Prec: 128, Size: 4,
		Forward:   "forwardDIT4Radix4Complex128",
		Inverse:   "inverseDIT4Radix4Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeCore",
		Signature: "dit4_radix4_generic", Priority: 0,
	},
	{
		Target: "generic", Prec: 128, Size: 8,
		Forward:   "forwardDIT8Radix2Complex128",
		Inverse:   "inverseDIT8Radix2Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit8_radix2_generic", Priority: 20,
	},
	{
		Target: "generic", Prec: 128, Size: 8,
		Forward:   "forwardDIT8Radix8Complex128",
		Inverse:   "inverseDIT8Radix8Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeCore",
		Signature: "dit8_radix8_generic", Priority: 30,
	},
	{
		Target: "generic", Prec: 128, Size: 8,
		Forward:   "forwardDIT8Radix4Complex128",
		Inverse:   "inverseDIT8Radix4Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit8_mixedradix_generic", Priority: 25,
	},
	{
		Target: "generic", Prec: 128, Size: 16,
		Forward:   "forwardDIT16Radix2Complex128",
		Inverse:   "inverseDIT16Radix2Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix2_generic", Priority: 10,
	},
	{
		Target: "generic", Prec: 128, Size: 16,
		Forward:   "forwardDIT16Radix4Complex128",
		Inverse:   "inverseDIT16Radix4Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix4_generic", Priority: 20,
	},
	{
		Target: "generic", Prec: 128, Size: 16,
		Forward:   "forwardDIT16Radix16Complex128",
		Inverse:   "inverseDIT16Radix16Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix16_generic", Priority: 30,
	},
	{
		Target: "generic", Prec: 128, Size: 32,
		Forward:   "forwardDIT32Radix2Complex128",
		Inverse:   "inverseDIT32Radix2Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix2_generic", Priority: 0,
	},
	{
		Target: "generic", Prec: 128, Size: 32,
		Forward:   "forwardDIT32Radix4Then2Complex128",
		Inverse:   "inverseDIT32Radix4Then2Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix4_then2_generic", Priority: 15,
	},
	{
		Target: "generic", Prec: 128, Size: 32,
		Forward:   "forwardDIT32Radix32Complex128",
		Inverse:   "inverseDIT32Radix32Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeCore",
		Signature: "dit32_radix32_generic", Priority: 5,
	},
	{
		Target: "generic", Prec: 128, Size: 64,
		Forward:   "forwardDIT64Radix2Complex128",
		Inverse:   "inverseDIT64Radix2Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix2_generic", Priority: 0,
	},
	{
		Target: "generic", Prec: 128, Size: 64,
		Forward:   "forwardDIT64Radix4Complex128",
		Inverse:   "inverseDIT64Radix4Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix4_generic", Priority: 20,
	},
	{
		Target: "generic", Prec: 128, Size: 128,
		Forward:   "forwardDIT128Radix2Complex128",
		Inverse:   "inverseDIT128Radix2Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix2_generic", Priority: 0,
	},
	{
		Target: "generic", Prec: 128, Size: 128,
		Forward:   "forwardDIT128Radix4Then2Complex128",
		Inverse:   "inverseDIT128Radix4Then2Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix4_then2_generic", Priority: 15,
	},
	{
		Target: "generic", Prec: 128, Size: 256,
		Forward:   "forwardDIT256Complex128",
		Inverse:   "inverseDIT256Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix2_generic", Priority: 10,
	},
	{
		Target: "generic", Prec: 128, Size: 256,
		Forward:   "forwardDIT256Radix4Complex128",
		Inverse:   "inverseDIT256Radix4Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix4_generic", Priority: 20,
	},
	{
		Target: "generic", Prec: 128, Size: 256,
		Forward:   "forwardDIT256Radix16Complex128",
		Inverse:   "inverseDIT256Radix16Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix16_generic", Priority: 15,
	},
	{
		Target: "generic", Prec: 128, Size: 384,
		Forward:   "forwardDIT384MixedComplex128",
		Inverse:   "inverseDIT384MixedComplex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit384_mixed_generic", Priority: 20,
	},
	{
		Target: "generic", Prec: 128, Size: 512,
		Forward:   "forwardDIT512Complex128",
		Inverse:   "inverseDIT512Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix2_generic", Priority: 10,
	},
	{
		Target: "generic", Prec: 128, Size: 512,
		Forward:   "forwardDIT512Radix8Complex128",
		Inverse:   "inverseDIT512Radix8Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix8_generic", Priority: 35,
	},
	{
		Target: "generic", Prec: 128, Size: 512,
		Forward:   "forwardDIT512Radix4Then2Complex128",
		Inverse:   "inverseDIT512Radix4Then2Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix4_then2_generic", Priority: 45,
	},
	{
		Target: "generic", Prec: 128, Size: 512,
		Forward:   "forwardDIT512Mixed16x32Complex128",
		Inverse:   "inverseDIT512Mixed16x32Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix16x32_generic", Priority: 30,
	},
	{
		Target: "generic", Prec: 128, Size: 1024,
		Forward:   "forwardDIT1024Radix4Complex128",
		Inverse:   "inverseDIT1024Radix4Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit1024_radix4_generic", Priority: 15,
	},
	{
		Target: "generic", Prec: 128, Size: 1024,
		Forward:   "forwardDIT1024Mixed32x32Complex128",
		Inverse:   "inverseDIT1024Mixed32x32Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit1024_radix32x32_generic", Priority: 25,
	},
	{
		Target: "generic", Prec: 128, Size: 2048,
		Forward:   "forwardDIT2048Radix4Then2Complex128",
		Inverse:   "inverseDIT2048Radix4Then2Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit2048_radix4_then2_generic", Priority: 20,
	},
	{
		Target: "generic", Prec: 128, Size: 4096,
		Forward:   "forwardDIT4096Radix4Complex128",
		Inverse:   "inverseDIT4096Radix4Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit4096_radix4_generic", Priority: 15,
	},
	{
		Target: "generic", Prec: 128, Size: 4096,
		Forward:   "forwardDIT4096SixStepComplex128",
		Inverse:   "inverseDIT4096SixStepComplex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit4096_sixstep_generic", Priority: 25,
	},
	{
		Target: "generic", Prec: 128, Size: 8192,
		Forward:   "forwardDIT8192Radix4Then2Complex128",
		Inverse:   "inverseDIT8192Radix4Then2Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit8192_radix4_then2_generic", Priority: 20,
	},
	{
		Target: "generic", Prec: 128, Size: 8192,
		Forward:   "forwardDIT8192SixStep64x128Complex128",
		Inverse:   "inverseDIT8192SixStep64x128Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit8192_sixstep64x128_generic", Priority: 30,
	},
	{
		Target: "generic", Prec: 128, Size: 16384,
		Forward:   "forwardDIT16384Radix4Complex128",
		Inverse:   "inverseDIT16384Radix4Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit16384_radix4_generic", Priority: 15,
	},
	{
		Target: "generic", Prec: 128, Size: 16384,
		Forward:   "forwardDIT16384SixStepComplex128",
		Inverse:   "inverseDIT16384SixStepComplex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNone", KernelType: "KernelTypeDIT",
		Signature: "dit16384_sixstep_generic", Priority: 25,
	},
	{
		Target: "avx2", Prec: 64, Size: 4,
		Forward:   "amd64.ForwardAVX2Size4Radix4Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size4Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit4_radix4_avx2", Priority: 5,
	},
	{
		Target: "avx2", Prec: 64, Size: 8,
		Forward:   "amd64.ForwardAVX2Size8Radix2Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size8Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit8_radix2_avx2", Priority: 7,
	},
	{
		Target: "avx2", Prec: 64, Size: 8,
		Forward:   "amd64.ForwardAVX2Size8Radix4Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size8Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit8_radix4_avx2", Priority: 10,
	},
	{
		Target: "avx2", Prec: 64, Size: 8,
		Forward:   "amd64.ForwardAVX2Size8Radix8Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size8Radix8Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeCore",
		Signature: "dit8_radix8_avx2", Priority: 9,
	},
	{
		Target: "avx2", Prec: 64, Size: 16,
		Forward:   "amd64.ForwardAVX2Size16Radix2Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size16Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix2_avx2", Priority: 20,
	},
	{
		Target: "avx2", Prec: 64, Size: 16,
		Forward:   "amd64.ForwardAVX2Size16Radix4Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size16Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix4_avx2", Priority: 30,
	},
	{
		Target: "avx2", Prec: 64, Size: 16,
		Forward:   "amd64.ForwardAVX2Size16Radix16Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size16Radix16Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix16_avx2", Priority: 50,
	},
	{
		Target: "avx2", Prec: 64, Size: 32,
		Forward:   "amd64.ForwardAVX2Size32Radix32Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size32Radix32Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeCore",
		Signature: "dit32_radix32_avx2", Priority: 25,
	},
	{
		Target: "avx2", Prec: 64, Size: 32,
		Forward:   "amd64.ForwardAVX2Size32Radix2Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size32Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix2_avx2", Priority: 20,
	},
	{
		Target: "avx2", Prec: 64, Size: 32,
		Forward:   "amd64.ForwardAVX2Size32Radix4Then2Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size32Radix4Then2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix4_then2_avx2", Priority: 22,
	},
	{
		Target: "avx2", Prec: 64, Size: 64,
		Forward:   "amd64.ForwardAVX2Size64Radix2Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size64Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix2_avx2", Priority: 19,
	},
	{
		Target: "avx2", Prec: 64, Size: 64,
		Forward:   "amd64.ForwardAVX2Size64Radix4Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size64Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix4_avx2", Priority: 25,
	},
	{
		Target: "avx2", Prec: 64, Size: 128,
		Forward:   "amd64.ForwardAVX2Size128Radix4Then2Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size128Radix4Then2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix4_then2_avx2", Priority: 25,
	},
	{
		Target: "avx2", Prec: 64, Size: 128,
		Forward:   "amd64.ForwardAVX2Size128Radix2Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size128Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix2_avx2", Priority: 20,
	},
	{
		Target: "avx2", Prec: 64, Size: 256,
		Forward:   "amd64.ForwardAVX2Size256Radix2Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size256Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix2_avx2", Priority: 15,
	},
	{
		Target: "avx2", Prec: 64, Size: 256,
		Forward:   "forwardAVX2Size256Radix4Complex64Safe",
		Inverse:   "amd64.InverseAVX2Size256Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix4_avx2", Priority: 120,
	},
	{
		Target: "avx2", Prec: 64, Size: 256,
		Forward:   "amd64.ForwardAVX2Size256Radix16Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size256Radix16Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix16_avx2", Priority: 130,
	},
	{
		Target: "avx2", Prec: 64, Size: 512,
		Forward:   "amd64.ForwardAVX2Size512Radix2Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size512Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix2_avx2", Priority: 10,
	},
	{
		Target: "avx2", Prec: 64, Size: 512,
		Forward:   "amd64.ForwardAVX2Size512Radix4Then2Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size512Radix4Then2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix4_then2_avx2", Priority: 25,
	},
	{
		Target: "avx2", Prec: 64, Size: 512,
		Forward:   "amd64.ForwardAVX2Size512Radix8Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size512Radix8Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix8_avx2", Priority: 30,
	},
	{
		Target: "avx2", Prec: 64, Size: 512,
		Forward:   "amd64.ForwardAVX2Size512Radix16x32Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size512Radix16x32Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix16x32_avx2", Priority: 20,
	},
	{
		Target: "avx2", Prec: 64, Size: 384,
		Forward:   "forwardDIT384MixedComplex64",
		Inverse:   "inverseDIT384MixedComplex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit384_mixed_avx2", Priority: 25,
	},
	{
		Target: "avx2", Prec: 64, Size: 2048,
		Forward:   "amd64.ForwardAVX2Size2048Radix4Then2Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size2048Radix4Then2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit2048_radix4_then2_avx2", Priority: 25,
	},
	{
		Target: "avx2", Prec: 64, Size: 8192,
		Forward:   "amd64.ForwardAVX2Size8192Radix4Then2Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size8192Radix4Then2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit8192_radix4_then2_avx2", Priority: 25,
	},
	{
		Target: "avx2", Prec: 64, Size: 8192,
		Forward:   "amd64.ForwardAVX2Size8192Radix4Then2ParamsComplex64Asm",
		Inverse:   "amd64.InverseAVX2Size8192Radix4Then2ParamsComplex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit8192_radix4_then2_params_avx2", Priority: 30,
		TwiddleSize: "twiddleSize8192Radix4Then2AVX2", PrepareTwiddle: "prepareTwiddle8192Radix4Then2AVX2",
	},
	{
		Target: "avx2", Prec: 64, Size: 8192,
		Forward:   "forwardDIT8192SixStep64x128AVX2Complex64",
		Inverse:   "inverseDIT8192SixStep64x128AVX2Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit8192_sixstep64x128_avx2", Priority: 35,
	},
	{
		Target: "avx2", Prec: 64, Size: 1024,
		Forward:   "amd64.ForwardAVX2Size1024Radix4Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size1024Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit1024_radix4_avx2", Priority: 25,
	},
	{
		Target: "avx2", Prec: 64, Size: 1024,
		Forward:   "amd64.ForwardAVX2Size1024Radix32x32Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size1024Radix32x32Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit1024_radix32x32_avx2", Priority: 30,
	},
	{
		Target: "avx2", Prec: 64, Size: 4096,
		Forward:   "amd64.ForwardAVX2Size4096Radix4Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size4096Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit4096_radix4_avx2", Priority: 25,
	},
	{
		Target: "avx2", Prec: 64, Size: 4096,
		Forward:   "forwardDIT4096SixStepAVX2Complex64",
		Inverse:   "inverseDIT4096SixStepAVX2Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit4096_sixstep_avx2", Priority: 35,
	},
	{
		Target: "avx2", Prec: 64, Size: 16384,
		Forward:   "amd64.ForwardAVX2Size16384Radix4Complex64Asm",
		Inverse:   "amd64.InverseAVX2Size16384Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit16384_radix4_avx2", Priority: 25,
	},
	{
		Target: "avx2", Prec: 64, Size: 16384,
		Forward:   "forwardDIT16384SixStepAVX2Complex64",
		Inverse:   "inverseDIT16384SixStepAVX2Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit16384_sixstep_avx2", Priority: 35,
	},
	// AVX-512 codelets: the generic AVX-512 radix-2 DIT kernel, registered only
	// at the sizes where it beats the best AVX2 codelet (codelet selection
	// prefers the higher SIMD level, so an entry here always outranks the AVX2
	// ones on AVX-512 hosts). Benchmarks and the complex128 rationale live in
	// internal/kernels/dit_avx512_amd64.go.
	{
		Target: "avx512", Prec: 64, Size: 1024,
		Forward:   "forwardAVX512Radix2Complex64",
		Inverse:   "inverseAVX512Radix2Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX512", KernelType: "KernelTypeDIT",
		Signature: "dit1024_radix2_avx512", Priority: 10,
	},
	{
		Target: "avx512", Prec: 64, Size: 4096,
		Forward:   "forwardAVX512Radix2Complex64",
		Inverse:   "inverseAVX512Radix2Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX512", KernelType: "KernelTypeDIT",
		Signature: "dit4096_radix2_avx512", Priority: 10,
	},
	{
		Target: "avx512", Prec: 64, Size: 8192,
		Forward:   "forwardAVX512Radix2Complex64",
		Inverse:   "inverseAVX512Radix2Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX512", KernelType: "KernelTypeDIT",
		Signature: "dit8192_radix2_avx512", Priority: 10,
	},
	{
		Target: "avx512", Prec: 64, Size: 16384,
		Forward:   "forwardAVX512Radix2Complex64",
		Inverse:   "inverseAVX512Radix2Complex64",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX512", KernelType: "KernelTypeDIT",
		Signature: "dit16384_radix2_avx512", Priority: 10,
	},
	{
		Target: "avx2", Prec: 128, Size: 384,
		Forward:   "forwardDIT384MixedComplex128",
		Inverse:   "inverseDIT384MixedComplex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit384_mixed_avx2", Priority: 25,
	},
	{
		Target: "avx2", Prec: 128, Size: 4,
		Forward:   "forwardDIT4Radix4Complex128",
		Inverse:   "inverseDIT4Radix4Complex128",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit4_radix4_avx2", Priority: 5,
	},
	{
		Target: "avx2", Prec: 128, Size: 8,
		Forward:   "amd64.ForwardAVX2Size8Radix8Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size8Radix8Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeCore",
		Signature: "dit8_radix8_avx2", Priority: 9,
	},
	{
		Target: "avx2", Prec: 128, Size: 8,
		Forward:   "amd64.ForwardAVX2Size8Radix2Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size8Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit8_radix2_avx2", Priority: 25,
	},
	{
		Target: "avx2", Prec: 128, Size: 8,
		Forward:   "amd64.ForwardAVX2Size8Radix4Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size8Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit8_radix4_avx2", Priority: 30,
	},
	{
		Target: "avx2", Prec: 128, Size: 16,
		Forward:   "amd64.ForwardAVX2Size16Radix2Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size16Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix2_avx2", Priority: 20,
	},
	{
		Target: "avx2", Prec: 128, Size: 16,
		Forward:   "amd64.ForwardAVX2Size16Radix4Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size16Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix4_avx2", Priority: 30,
	},
	{
		Target: "avx2", Prec: 128, Size: 32,
		Forward:   "amd64.ForwardAVX2Size32Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size32Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix2_avx2", Priority: 20,
	},
	{
		Target: "avx2", Prec: 128, Size: 32,
		Forward:   "amd64.ForwardAVX2Size32Radix4Then2Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size32Radix4Then2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix4_then2_avx2", Priority: 22,
	},
	{
		Target: "avx2", Prec: 128, Size: 64,
		Forward:   "amd64.ForwardAVX2Size64Radix2Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size64Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix2_avx2", Priority: 20,
	},
	{
		Target: "avx2", Prec: 128, Size: 64,
		Forward:   "amd64.ForwardAVX2Size64Radix4Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size64Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix4_avx2", Priority: 25,
	},
	{
		Target: "avx2", Prec: 128, Size: 128,
		Forward:   "amd64.ForwardAVX2Size128Radix2Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size128Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix2_avx2", Priority: 20,
	},
	{
		Target: "avx2", Prec: 128, Size: 256,
		Forward:   "amd64.ForwardAVX2Size256Radix2Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size256Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix2_avx2", Priority: 25,
	},
	{
		Target: "avx2", Prec: 128, Size: 256,
		Forward:   "amd64.ForwardAVX2Size256Radix4Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size256Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix4_avx2", Priority: 40,
	},
	{
		Target: "avx2", Prec: 128, Size: 256,
		Forward:   "amd64.ForwardAVX2Size256Radix16Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size256Radix16Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix16_avx2", Priority: 15,
		TwiddleSize: "twiddleSize256Radix16AVX2", PrepareTwiddle: "prepareTwiddle256Radix16AVX2",
	},
	{
		Target: "avx2", Prec: 128, Size: 512,
		Forward:   "amd64.ForwardAVX2Size512Radix2Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size512Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix2_avx2", Priority: 10,
	},
	{
		Target: "avx2", Prec: 128, Size: 512,
		Forward:   "amd64.ForwardAVX2Size512Radix4Then2Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size512Radix4Then2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix4_then2_avx2", Priority: 25,
	},
	{
		Target: "avx2", Prec: 128, Size: 1024,
		Forward:   "amd64.ForwardAVX2Size1024Radix32x32Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size1024Radix32x32Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit1024_radix32x32_avx2", Priority: 30,
		TwiddleSize: "twiddleSize1024Radix32x32AVX2", PrepareTwiddle: "prepareTwiddle1024Radix32x32AVX2",
	},
	{
		Target: "avx2", Prec: 128, Size: 2048,
		Forward:   "amd64.ForwardAVX2Size2048Radix4Then2Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size2048Radix4Then2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit2048_radix4_then2_avx2", Priority: 25,
	},
	{
		Target: "avx2", Prec: 128, Size: 4096,
		Forward:   "amd64.ForwardAVX2Size4096Radix4Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size4096Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit4096_radix4_avx2", Priority: 30,
	},
	{
		Target: "avx2", Prec: 128, Size: 8192,
		Forward:   "amd64.ForwardAVX2Size8192Radix4Then2Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size8192Radix4Then2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit8192_radix4_then2_avx2", Priority: 25,
	},
	{
		Target: "avx2", Prec: 128, Size: 16384,
		Forward:   "amd64.ForwardAVX2Size16384Radix4Complex128Asm",
		Inverse:   "amd64.InverseAVX2Size16384Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDAVX2", KernelType: "KernelTypeDIT",
		Signature: "dit16384_radix4_avx2", Priority: 30,
	},
	{
		Target: "sse2", Prec: 64, Size: 4,
		Forward:   "amd64.ForwardSSE2Size4Radix4Complex64Asm",
		Inverse:   "amd64.InverseSSE2Size4Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeDIT",
		Signature: "dit4_radix4_sse2", Priority: 5,
	},
	{
		Target: "sse2", Prec: 64, Size: 8,
		Forward:   "amd64.ForwardSSE3Size8Radix2Complex64Asm",
		Inverse:   "amd64.InverseSSE3Size8Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE3", KernelType: "KernelTypeDIT",
		Signature: "dit8_radix2_sse3", Priority: 18,
	},
	{
		Target: "sse2", Prec: 64, Size: 8,
		Forward:   "amd64.ForwardSSE3Size8Radix8Complex64Asm",
		Inverse:   "amd64.InverseSSE3Size8Radix8Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE3", KernelType: "KernelTypeCore",
		Signature: "dit8_radix8_sse3", Priority: 30,
	},
	{
		Target: "sse2", Prec: 64, Size: 16,
		Forward:   "amd64.ForwardSSE3Size16Radix16Complex64Asm",
		Inverse:   "amd64.InverseSSE3Size16Radix16Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE3", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix16_sse3", Priority: 40,
	},
	{
		Target: "sse2", Prec: 64, Size: 16,
		Forward:   "amd64.ForwardSSE3Size16Radix2Complex64Asm",
		Inverse:   "amd64.InverseSSE3Size16Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE3", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix2_sse3", Priority: 17,
	},
	{
		Target: "sse2", Prec: 64, Size: 16,
		Forward:   "amd64.ForwardSSE3Size16Radix4Complex64Asm",
		Inverse:   "amd64.InverseSSE3Size16Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE3", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix4_sse3", Priority: 18,
	},
	{
		Target: "sse2", Prec: 64, Size: 32,
		Forward:   "amd64.ForwardSSE3Size32Radix2Complex64Asm",
		Inverse:   "amd64.InverseSSE3Size32Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE3", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix2_sse3", Priority: 17,
	},
	{
		Target: "sse2", Prec: 64, Size: 32,
		Forward:   "amd64.ForwardSSE3Size32Radix4Then2Complex64Asm",
		Inverse:   "amd64.InverseSSE3Size32Radix4Then2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE3", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix4_then2_sse3", Priority: 19,
	},
	{
		Target: "sse2", Prec: 64, Size: 64,
		Forward:   "amd64.ForwardSSE3Size64Radix4Complex64Asm",
		Inverse:   "amd64.InverseSSE3Size64Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE3", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix4_sse3", Priority: 18,
	},
	{
		Target: "sse2", Prec: 64, Size: 64,
		Forward:   "amd64.ForwardSSE3Size64Radix2Complex64Asm",
		Inverse:   "amd64.InverseSSE3Size64Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE3", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix2_sse3", Priority: 17,
	},
	{
		Target: "sse2", Prec: 64, Size: 128,
		Forward:   "amd64.ForwardSSE3Size128Radix4Then2Complex64Asm",
		Inverse:   "amd64.InverseSSE3Size128Radix4Then2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE3", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix4_then2_sse3", Priority: 17,
	},
	{
		Target: "sse2", Prec: 64, Size: 128,
		Forward:   "amd64.ForwardSSE3Size128Radix2Complex64Asm",
		Inverse:   "amd64.InverseSSE3Size128Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE3", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix2_sse3", Priority: 17,
	},
	{
		Target: "sse2", Prec: 64, Size: 512,
		Forward:   "amd64.ForwardSSE3Size512Radix2Complex64Asm",
		Inverse:   "amd64.InverseSSE3Size512Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE3", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix2_sse3", Priority: 10,
	},
	{
		Target: "sse2", Prec: 64, Size: 512,
		Forward:   "amd64.ForwardSSE3Size512Radix4Then2Complex64Asm",
		Inverse:   "amd64.InverseSSE3Size512Radix4Then2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE3", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix4_then2_sse3", Priority: 12,
	},
	{
		Target: "sse2", Prec: 64, Size: 1024,
		Forward:   "amd64.ForwardSSE3Size1024Radix4Complex64Asm",
		Inverse:   "amd64.InverseSSE3Size1024Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE3", KernelType: "KernelTypeDIT",
		Signature: "dit1024_radix4_sse3", Priority: 12,
	},
	{
		Target: "sse2", Prec: 128, Size: 4,
		Forward:   "amd64.ForwardSSE2Size4Radix4Complex128Asm",
		Inverse:   "amd64.InverseSSE2Size4Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeDIT",
		Signature: "dit4_radix4_sse2", Priority: 5,
	},
	{
		Target: "sse2", Prec: 128, Size: 8,
		Forward:   "amd64.ForwardSSE2Size8Radix2Complex128Asm",
		Inverse:   "amd64.InverseSSE2Size8Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeDIT",
		Signature: "dit8_radix2_sse2", Priority: 17,
	},
	{
		Target: "sse2", Prec: 128, Size: 8,
		Forward:   "amd64.ForwardSSE2Size8Radix8Complex128Asm",
		Inverse:   "amd64.InverseSSE2Size8Radix8Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeCore",
		Signature: "dit8_radix8_sse2", Priority: 30,
	},
	{
		Target: "sse2", Prec: 128, Size: 8,
		Forward:   "amd64.ForwardSSE2Size8Radix4Complex128Asm",
		Inverse:   "amd64.InverseSSE2Size8Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeDIT",
		Signature: "dit8_radix4_sse2", Priority: 18,
	},
	{
		Target: "sse2", Prec: 128, Size: 16,
		Forward:   "amd64.ForwardSSE2Size16Radix2Complex128Asm",
		Inverse:   "amd64.InverseSSE2Size16Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix2_sse2", Priority: 17,
	},
	{
		Target: "sse2", Prec: 128, Size: 16,
		Forward:   "amd64.ForwardSSE2Size16Radix4Complex128Asm",
		Inverse:   "amd64.InverseSSE2Size16Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix4_sse2", Priority: 18,
	},
	{
		Target: "sse2", Prec: 128, Size: 32,
		Forward:   "amd64.ForwardSSE2Size32Radix2Complex128Asm",
		Inverse:   "amd64.InverseSSE2Size32Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix2_sse2", Priority: 17,
	},
	{
		Target: "sse2", Prec: 128, Size: 32,
		Forward:   "amd64.ForwardSSE2Size32Radix4Then2Complex128Asm",
		Inverse:   "amd64.InverseSSE2Size32Radix4Then2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix4_then2_sse2", Priority: 19,
	},
	{
		Target: "sse2", Prec: 128, Size: 64,
		Forward:   "amd64.ForwardSSE2Size64Radix2Complex128Asm",
		Inverse:   "amd64.InverseSSE2Size64Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix2_sse2", Priority: 18,
	},
	{
		Target: "sse2", Prec: 128, Size: 64,
		Forward:   "amd64.ForwardSSE2Size64Radix4Complex128Asm",
		Inverse:   "amd64.InverseSSE2Size64Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix4_sse2", Priority: 18,
	},
	{
		Target: "sse2", Prec: 128, Size: 128,
		Forward:   "amd64.ForwardSSE2Size128Radix2Complex128Asm",
		Inverse:   "amd64.InverseSSE2Size128Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix2_sse2", Priority: 17,
	},
	{
		Target: "sse2", Prec: 128, Size: 128,
		Forward:   "amd64.ForwardSSE2Size128Radix4Then2Complex128Asm",
		Inverse:   "amd64.InverseSSE2Size128Radix4Then2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix4_then2_sse2", Priority: 18,
	},
	{
		Target: "sse2", Prec: 128, Size: 256,
		Forward:   "amd64.ForwardSSE2Size256Radix2Complex128Asm",
		Inverse:   "amd64.InverseSSE2Size256Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix2_sse2", Priority: 12,
	},
	{
		Target: "sse2", Prec: 128, Size: 256,
		Forward:   "amd64.ForwardSSE2Size256Radix4Complex128Asm",
		Inverse:   "amd64.InverseSSE2Size256Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix4_sse2", Priority: 18,
	},
	{
		Target: "sse2", Prec: 128, Size: 512,
		Forward:   "amd64.ForwardSSE2Size512Radix2Complex128Asm",
		Inverse:   "amd64.InverseSSE2Size512Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix2_sse2", Priority: 10,
	},
	{
		Target: "sse2", Prec: 128, Size: 512,
		Forward:   "amd64.ForwardSSE2Size512Radix4Then2Complex128Asm",
		Inverse:   "amd64.InverseSSE2Size512Radix4Then2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix4_then2_sse2", Priority: 12,
	},
	{
		Target: "sse2", Prec: 128, Size: 1024,
		Forward:   "amd64.ForwardSSE2Size1024Radix4Complex128Asm",
		Inverse:   "amd64.InverseSSE2Size1024Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDSSE2", KernelType: "KernelTypeDIT",
		Signature: "dit1024_radix4_sse2", Priority: 12,
	},
	{
		Target: "neon", Prec: 64, Size: 4,
		Forward:   "arm64.ForwardNEONSize4Radix4Complex64Asm",
		Inverse:   "arm64.InverseNEONSize4Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit4_radix4_neon", Priority: 10,
	},
	{
		Target: "neon", Prec: 64, Size: 8,
		Forward:   "arm64.ForwardNEONSize8Radix2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize8Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit8_radix2_neon", Priority: 20,
	},
	{
		Target: "neon", Prec: 64, Size: 8,
		Forward:   "arm64.ForwardNEONSize8Radix4Complex64Asm",
		Inverse:   "arm64.InverseNEONSize8Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit8_radix4_neon", Priority: 25,
	},
	{
		Target: "neon", Prec: 64, Size: 8,
		Forward:   "arm64.ForwardNEONSize8Radix8Complex64Asm",
		Inverse:   "arm64.InverseNEONSize8Radix8Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeCore",
		Signature: "dit8_radix8_neon", Priority: 30,
	},
	{
		Target: "neon", Prec: 64, Size: 16,
		Forward:   "arm64.ForwardNEONSize16Radix2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize16Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix2_neon", Priority: 22,
	},
	{
		Target: "neon", Prec: 64, Size: 16,
		Forward:   "arm64.ForwardNEONSize16Radix4Complex64Asm",
		Inverse:   "arm64.InverseNEONSize16Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix4_neon", Priority: 28,
	},
	{
		Target: "neon", Prec: 64, Size: 32,
		Forward:   "arm64.ForwardNEONSize32Radix2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize32Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix2_neon", Priority: 20,
	},
	{
		Target: "neon", Prec: 64, Size: 32,
		Forward:   "arm64.ForwardNEONSize32Radix4Then2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize32Radix4Then2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix4_then2_neon", Priority: 24,
	},
	{
		Target: "neon", Prec: 64, Size: 64,
		Forward:   "arm64.ForwardNEONSize64Radix2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize64Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix2_neon", Priority: 22,
	},
	{
		Target: "neon", Prec: 64, Size: 128,
		Forward:   "arm64.ForwardNEONSize128Radix2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize128Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix2_neon", Priority: 20,
	},
	{
		Target: "neon", Prec: 64, Size: 128,
		Forward:   "arm64.ForwardNEONSize128Radix4Then2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize128Radix4Then2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix4_then2_neon", Priority: 24,
	},
	{
		Target: "neon", Prec: 64, Size: 256,
		Forward:   "arm64.ForwardNEONSize256Radix2Complex64Asm",
		Inverse:   "arm64.InverseNEONSize256Radix2Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix2_neon", Priority: 18,
	},
	{
		Target: "neon", Prec: 64, Size: 256,
		Forward:   "arm64.ForwardNEONSize256Radix4Complex64Asm",
		Inverse:   "arm64.InverseNEONSize256Radix4Complex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix4_neon", Priority: 28,
	},
	{
		Target: "neon", Prec: 64, Size: 512,
		Forward:   "arm64.ForwardNEONComplex64Asm",
		Inverse:   "arm64.InverseNEONComplex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit512_radix2_neon", Priority: 1,
	},
	{
		Target: "neon", Prec: 64, Size: 1024,
		Forward:   "arm64.ForwardNEONComplex64Asm",
		Inverse:   "arm64.InverseNEONComplex64Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit1024_radix2_neon", Priority: 1,
	},
	{
		Target: "neon", Prec: 128, Size: 4,
		Forward:   "arm64.ForwardNEONSize4Radix4Complex128Asm",
		Inverse:   "arm64.InverseNEONSize4Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit4_radix4_neon", Priority: 10,
	},
	{
		Target: "neon", Prec: 128, Size: 8,
		Forward:   "arm64.ForwardNEONSize8Radix2Complex128Asm",
		Inverse:   "arm64.InverseNEONSize8Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit8_radix2_neon", Priority: 20,
	},
	{
		Target: "neon", Prec: 128, Size: 8,
		Forward:   "arm64.ForwardNEONSize8Radix4Complex128Asm",
		Inverse:   "arm64.InverseNEONSize8Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit8_radix4_neon", Priority: 25,
	},
	{
		Target: "neon", Prec: 128, Size: 16,
		Forward:   "arm64.ForwardNEONSize16Complex128Asm",
		Inverse:   "arm64.InverseNEONSize16Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix2_neon", Priority: 22,
	},
	{
		Target: "neon", Prec: 128, Size: 16,
		Forward:   "arm64.ForwardNEONSize16Radix4Complex128Asm",
		Inverse:   "arm64.InverseNEONSize16Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit16_radix4_neon", Priority: 28,
	},
	{
		Target: "neon", Prec: 128, Size: 32,
		Forward:   "arm64.ForwardNEONComplex128Asm",
		Inverse:   "arm64.InverseNEONComplex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit32_generic_neon", Priority: 1,
	},
	{
		Target: "neon", Prec: 128, Size: 32,
		Forward:   "arm64.ForwardNEONSize32Complex128Asm",
		Inverse:   "arm64.InverseNEONSize32Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix2_neon", Priority: 20,
	},
	{
		Target: "neon", Prec: 128, Size: 32,
		Forward:   "arm64.ForwardNEONSize32Radix4Then2Complex128Asm",
		Inverse:   "arm64.InverseNEONSize32Radix4Then2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit32_radix4_then2_neon", Priority: 24,
	},
	{
		Target: "neon", Prec: 128, Size: 64,
		Forward:   "arm64.ForwardNEONSize64Radix2Complex128Asm",
		Inverse:   "arm64.InverseNEONSize64Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix2_neon", Priority: 20,
	},
	{
		Target: "neon", Prec: 128, Size: 64,
		Forward:   "arm64.ForwardNEONSize64Radix4Complex128Asm",
		Inverse:   "arm64.InverseNEONSize64Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit64_radix4_neon", Priority: 24,
	},
	{
		Target: "neon", Prec: 128, Size: 128,
		Forward:   "arm64.ForwardNEONSize128Radix2Complex128Asm",
		Inverse:   "arm64.InverseNEONSize128Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix2_neon", Priority: 20,
	},
	{
		Target: "neon", Prec: 128, Size: 128,
		Forward:   "arm64.ForwardNEONSize128Radix4Then2Complex128Asm",
		Inverse:   "arm64.InverseNEONSize128Radix4Then2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit128_radix4_then2_neon", Priority: 24,
	},
	{
		Target: "neon", Prec: 128, Size: 256,
		Forward:   "arm64.ForwardNEONSize256Radix2Complex128Asm",
		Inverse:   "arm64.InverseNEONSize256Radix2Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix2_neon", Priority: 18,
	},
	{
		Target: "neon", Prec: 128, Size: 256,
		Forward:   "arm64.ForwardNEONSize256Radix4Complex128Asm",
		Inverse:   "arm64.InverseNEONSize256Radix4Complex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit256_radix4_neon", Priority: 28,
	},
	{
		Target: "neon", Prec: 128, Size: 512,
		Forward:   "arm64.ForwardNEONComplex128Asm",
		Inverse:   "arm64.InverseNEONComplex128Asm",
		Algorithm: "KernelDIT", SIMDLevel: "SIMDNEON", KernelType: "KernelTypeDIT",
		Signature: "dit512_generic_neon", Priority: 1,
	},
}
