package asm
//go:build arm64 && fft_asm && !purego






























































































func inverseNEONSize256Radix2Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc forwardNEONSize256Radix2Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc inverseNEONSize128Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc forwardNEONSize128Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc inverseNEONSize64Radix4Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc forwardNEONSize64Radix4Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc inverseNEONSize64Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc forwardNEONSize64Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc inverseNEONSize32MixedRadix24Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc forwardNEONSize32MixedRadix24Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc inverseNEONSize32Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc forwardNEONSize32Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc inverseNEONSize16Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc forwardNEONSize16Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc inverseNEONSize16Radix4Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc forwardNEONSize16Radix4Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc inverseNEONSize8Radix8Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc forwardNEONSize8Radix8Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc inverseNEONSize8Radix4Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc forwardNEONSize8Radix4Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc inverseNEONSize8Radix2Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc forwardNEONSize8Radix2Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc inverseNEONSize4Radix4Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc forwardNEONSize4Radix4Complex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescape// Size-specific complex64 NEON kernels.func neonComplexMul2Asm(dst, a, b *complex64)//go:noescapefunc inverseNEONComplex128Asm(dst, src, twiddle, scratch []complex128, bitrev []int) bool//go:noescapefunc forwardNEONComplex128Asm(dst, src, twiddle, scratch []complex128, bitrev []int) bool//go:noescapefunc inverseNEONComplex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescapefunc forwardNEONComplex64Asm(dst, src, twiddle, scratch []complex64, bitrev []int) bool//go:noescape// the *.s files in this directory.// NOTE: These are Go declarations for ARM64 assembly routines implemented inpackage asm