//go:build amd64 && !purego

// ===========================================================================
// AVX-512 Size-64 radix-4 FFT codelets for AMD64 (complex128)
// ===========================================================================
//
// A ZMM register holds 4 complex128, so all 64 points live in 16 of the 32
// ZMM registers.  The whole transform is therefore register-resident: the data
// is loaded once, all three radix-4 stages run entirely in registers, and the
// result is stored once.  Nothing spills between stages, and no scratch buffer
// is used (dst == src works because every load precedes every store).  The
// AVX2 codelet at this size needs 32 YMM for the same data -- twice the
// register file -- which is why it loses to the SSE2 one here.
//
// INDEX DECOMPOSITION (64-point core)
// ----------------------------------
// Write the 64-point output index as three base-4 digits, i = 16a + 4b + c.
// DIT wants work[i] = src[bitrev(i)] = src[16c + 4b + a] (base-4 digit
// reversal), and the three stages butterfly over c, then b, then a.
//
// Layout L0 -- register k = 4c + b, lane index = a:
//
//	Z[4c+b] = { src[16c+4b+a] : a = 0..3 } = { work[16a+4b+c] : a = 0..3 }
//
// For contiguous input that is just block k into Zk, so the digit reversal is
// free: no bit-reversal table and no permutation instructions.  In L0 both
// stage 1 (over c: registers b, 4+b, 8+b, 12+b) and stage 2 (over b:
// registers 4c .. 4c+3) are cross-register, so every vector instruction
// performs four independent butterflies, one per lane.
//
// Stage 3 butterflies over a, which lives in the lanes in L0, so one 4x4
// transpose of 128-bit lanes (8 VSHUFF64X2 per group of four registers) moves
// digit a into the register index and digit c into the lanes:
//
// Layout L1 -- register k = 4a + b, lane index = c:
//
//	Z[4a+b] = { work[16a+4b+c] : c = 0..3 } = work[16a+4b .. 16a+4b+3]
//
// Stage 3 is cross-register again, and because L1 is lane-contiguous the
// result is block-contiguous: block number == register number, exactly as on
// load.  One transpose total.
//
// TWIDDLES
// --------
// Stage 1 has w == 1 throughout.  Stage 2 needs W64^(4bc) -- constant per
// group, identical in every lane.  Stage 3 needs W64^(a*(4b+c)), which depends
// on the lane, so those are per-lane vectors.  All of them are compile-time
// constants, so they are embedded here pre-splatted into real-part /
// imaginary-part vectors and used directly as memory operands.  That makes a
// complex multiply three instructions (VSHUFPD + VMULPD + VFMADDSUB231PD) with
// no twiddle gathering or splatting at run time, and the twiddle argument is
// unused (its length is still validated, to match the sibling codelets).
//
// The bit patterns are exactly what internal/math.ComputeTwiddleFactors
// produces: W_n^k = exp(-2*pi*i*k/n) via math.Sincos(-2*pi*k/n).
//
// COMPLEX MULTIPLY / BUTTERFLY
// ----------------------------
//	forward  z*w:       VSHUFPD $0x55 (swap re/im) ; VMULPD w.im ; VFMADDSUB231PD w.re
//	inverse  z*conj(w): same, with VFMSUBADD231PD
//	radix-4:  t0 = x0+x2, t1 = x0-x2, t2 = x1+x3, t3 = x1-x3
//	          u  = -i*t3 = [t3.im, -t3.re]  (VSHUFPD $0x55 + VPXORQ sign mask)
//	          y0 = t0+t2, y2 = t0-t2, y1 = t1+u, y3 = t1-u   (forward)
//	          y1 = t1-u,  y3 = t1+u                          (inverse)
//
// Only AVX512F is used (VPXORQ rather than the DQ-only VXORPD), so the kernels
// are valid on every AVX-512 CPU.  Callers gate on cpu.Features.HasAVX512.
//
// Generated by a throwaway generator whose virtual-instruction list was first
// interpreted against a naive DFT (forward, inverse and round trip) before
// being rendered to assembly.
//
// The inverse 1/64 is folded into the stage-3 twiddle constants (inputs
// a = 1,2,3); the untwiddled a = 0 inputs are scaled with an explicit VMULPD
// against a broadcast of the shared 1/64 constant, so every stage-3 input --
// and hence every output -- carries the factor.
//
// ===========================================================================

#include "textflag.h"

// ===========================================================================
// Forward transform, size 64, complex128, radix-4
// ===========================================================================
TEXT ·ForwardAVX512Size64Radix4Complex128Asm(SB), NOSPLIT, $0-97
	MOVQ src_len+32(FP), AX                   // n = len(src)
	CMPQ AX, $64
	JNE  avx512_f64_s64r4_false               // only n == 64
	MOVQ dst_len+8(FP), AX
	CMPQ AX, $64
	JL   avx512_f64_s64r4_false               // dst too short
	MOVQ twiddle_len+56(FP), AX
	CMPQ AX, $64
	JL   avx512_f64_s64r4_false               // twiddle too short
	MOVQ scratch_len+80(FP), AX
	CMPQ AX, $64
	JL   avx512_f64_s64r4_false               // scratch too short

	MOVQ dst+0(FP), R8                        // R8 = dst
	MOVQ src+24(FP), R9                       // R9 = src (dst == src is fine: every
	                                          // load happens before the first store)

// Load all 64 complex128 into Z0..Z15. Register k holds src[4k..4k+3];
// read as (c = k>>2, b = k&3) with the lane index carrying digit a, this IS
// the base-4 digit-reversed order, so no bitrev table is needed.
	VMOVUPD (R9), Z0                          // Z0 = src[0..3]
	VMOVUPD 64(R9), Z1                        // Z1 = src[4..7]
	VMOVUPD 128(R9), Z2                       // Z2 = src[8..11]
	VMOVUPD 192(R9), Z3                       // Z3 = src[12..15]
	VMOVUPD 256(R9), Z4                       // Z4 = src[16..19]
	VMOVUPD 320(R9), Z5                       // Z5 = src[20..23]
	VMOVUPD 384(R9), Z6                       // Z6 = src[24..27]
	VMOVUPD 448(R9), Z7                       // Z7 = src[28..31]
	VMOVUPD 512(R9), Z8                       // Z8 = src[32..35]
	VMOVUPD 576(R9), Z9                       // Z9 = src[36..39]
	VMOVUPD 640(R9), Z10                      // Z10 = src[40..43]
	VMOVUPD 704(R9), Z11                      // Z11 = src[44..47]
	VMOVUPD 768(R9), Z12                      // Z12 = src[48..51]
	VMOVUPD 832(R9), Z13                      // Z13 = src[52..55]
	VMOVUPD 896(R9), Z14                      // Z14 = src[56..59]
	VMOVUPD 960(R9), Z15                      // Z15 = src[60..63]
	VMOVUPD negodd<>(SB), Z31                 // sign mask for -i (negate odd doubles)

	// ----- Stage 1: 16 radix-4 butterflies over digit c (w == 1) -----
	// group b=0: Z0,Z4,Z8,Z12 (4 butterflies, one per lane)
	VADDPD Z8, Z0, Z16                        // t0 = x0 + x2
	VSUBPD Z8, Z0, Z17                        // t1 = x0 - x2
	VADDPD Z12, Z4, Z18                       // t2 = x1 + x3
	VSUBPD Z12, Z4, Z19                       // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z0                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z8                       // y2 = t0 - t2
	VADDPD Z20, Z17, Z4                       // y1 = t1 + u = t1 - i*t3
	VSUBPD Z20, Z17, Z12                      // y3 = t1 - u = t1 + i*t3
	// group b=1: Z1,Z5,Z9,Z13 (4 butterflies, one per lane)
	VADDPD Z9, Z1, Z16                        // t0 = x0 + x2
	VSUBPD Z9, Z1, Z17                        // t1 = x0 - x2
	VADDPD Z13, Z5, Z18                       // t2 = x1 + x3
	VSUBPD Z13, Z5, Z19                       // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z1                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z9                       // y2 = t0 - t2
	VADDPD Z20, Z17, Z5                       // y1 = t1 + u = t1 - i*t3
	VSUBPD Z20, Z17, Z13                      // y3 = t1 - u = t1 + i*t3
	// group b=2: Z2,Z6,Z10,Z14 (4 butterflies, one per lane)
	VADDPD Z10, Z2, Z16                       // t0 = x0 + x2
	VSUBPD Z10, Z2, Z17                       // t1 = x0 - x2
	VADDPD Z14, Z6, Z18                       // t2 = x1 + x3
	VSUBPD Z14, Z6, Z19                       // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z2                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z10                      // y2 = t0 - t2
	VADDPD Z20, Z17, Z6                       // y1 = t1 + u = t1 - i*t3
	VSUBPD Z20, Z17, Z14                      // y3 = t1 - u = t1 + i*t3
	// group b=3: Z3,Z7,Z11,Z15 (4 butterflies, one per lane)
	VADDPD Z11, Z3, Z16                       // t0 = x0 + x2
	VSUBPD Z11, Z3, Z17                       // t1 = x0 - x2
	VADDPD Z15, Z7, Z18                       // t2 = x1 + x3
	VSUBPD Z15, Z7, Z19                       // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z3                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z11                      // y2 = t0 - t2
	VADDPD Z20, Z17, Z7                       // y1 = t1 + u = t1 - i*t3
	VSUBPD Z20, Z17, Z15                      // y3 = t1 - u = t1 + i*t3

	// ----- Stage 2: 16 radix-4 butterflies over digit b, w = W64^(4*b*c) -----
	// group c=0: Z0..Z3, twiddles W64^0, W64^0, W64^0
	VADDPD Z2, Z0, Z16                        // t0 = x0 + x2
	VSUBPD Z2, Z0, Z17                        // t1 = x0 - x2
	VADDPD Z3, Z1, Z18                        // t2 = x1 + x3
	VSUBPD Z3, Z1, Z19                        // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z0                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z2                       // y2 = t0 - t2
	VADDPD Z20, Z17, Z1                       // y1 = t1 + u = t1 - i*t3
	VSUBPD Z20, Z17, Z3                       // y3 = t1 - u = t1 + i*t3
	// group c=1: Z4..Z7, twiddles W64^4, W64^8, W64^12
	VSHUFPD $0x55, Z5, Z5, Z21                // [im,re] of x1*w1 s2 c=1
	VMULPD s2c1b1_im<>(SB), Z21, Z21          // * w.im
	VFMADDSUB231PD s2c1b1_re<>(SB), Z5, Z21   // x1*w1 s2 c=1
	VSHUFPD $0x55, Z6, Z6, Z22                // [im,re] of x2*w2 s2 c=1
	VMULPD s2c1b2_im<>(SB), Z22, Z22          // * w.im
	VFMADDSUB231PD s2c1b2_re<>(SB), Z6, Z22   // x2*w2 s2 c=1
	VSHUFPD $0x55, Z7, Z7, Z23                // [im,re] of x3*w3 s2 c=1
	VMULPD s2c1b3_im<>(SB), Z23, Z23          // * w.im
	VFMADDSUB231PD s2c1b3_re<>(SB), Z7, Z23   // x3*w3 s2 c=1
	VADDPD Z22, Z4, Z16                       // t0 = x0 + x2
	VSUBPD Z22, Z4, Z17                       // t1 = x0 - x2
	VADDPD Z23, Z21, Z18                      // t2 = x1 + x3
	VSUBPD Z23, Z21, Z19                      // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z4                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z6                       // y2 = t0 - t2
	VADDPD Z20, Z17, Z5                       // y1 = t1 + u = t1 - i*t3
	VSUBPD Z20, Z17, Z7                       // y3 = t1 - u = t1 + i*t3
	// group c=2: Z8..Z11, twiddles W64^8, W64^16, W64^24
	VSHUFPD $0x55, Z9, Z9, Z21                // [im,re] of x1*w1 s2 c=2
	VMULPD s2c2b1_im<>(SB), Z21, Z21          // * w.im
	VFMADDSUB231PD s2c2b1_re<>(SB), Z9, Z21   // x1*w1 s2 c=2
	VSHUFPD $0x55, Z10, Z10, Z22              // [im,re] of x2*w2 s2 c=2
	VMULPD s2c2b2_im<>(SB), Z22, Z22          // * w.im
	VFMADDSUB231PD s2c2b2_re<>(SB), Z10, Z22  // x2*w2 s2 c=2
	VSHUFPD $0x55, Z11, Z11, Z23              // [im,re] of x3*w3 s2 c=2
	VMULPD s2c2b3_im<>(SB), Z23, Z23          // * w.im
	VFMADDSUB231PD s2c2b3_re<>(SB), Z11, Z23  // x3*w3 s2 c=2
	VADDPD Z22, Z8, Z16                       // t0 = x0 + x2
	VSUBPD Z22, Z8, Z17                       // t1 = x0 - x2
	VADDPD Z23, Z21, Z18                      // t2 = x1 + x3
	VSUBPD Z23, Z21, Z19                      // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z8                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z10                      // y2 = t0 - t2
	VADDPD Z20, Z17, Z9                       // y1 = t1 + u = t1 - i*t3
	VSUBPD Z20, Z17, Z11                      // y3 = t1 - u = t1 + i*t3
	// group c=3: Z12..Z15, twiddles W64^12, W64^24, W64^36
	VSHUFPD $0x55, Z13, Z13, Z21              // [im,re] of x1*w1 s2 c=3
	VMULPD s2c3b1_im<>(SB), Z21, Z21          // * w.im
	VFMADDSUB231PD s2c3b1_re<>(SB), Z13, Z21  // x1*w1 s2 c=3
	VSHUFPD $0x55, Z14, Z14, Z22              // [im,re] of x2*w2 s2 c=3
	VMULPD s2c3b2_im<>(SB), Z22, Z22          // * w.im
	VFMADDSUB231PD s2c3b2_re<>(SB), Z14, Z22  // x2*w2 s2 c=3
	VSHUFPD $0x55, Z15, Z15, Z23              // [im,re] of x3*w3 s2 c=3
	VMULPD s2c3b3_im<>(SB), Z23, Z23          // * w.im
	VFMADDSUB231PD s2c3b3_re<>(SB), Z15, Z23  // x3*w3 s2 c=3
	VADDPD Z22, Z12, Z16                      // t0 = x0 + x2
	VSUBPD Z22, Z12, Z17                      // t1 = x0 - x2
	VADDPD Z23, Z21, Z18                      // t2 = x1 + x3
	VSUBPD Z23, Z21, Z19                      // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z12                      // y0 = t0 + t2
	VSUBPD Z18, Z16, Z14                      // y2 = t0 - t2
	VADDPD Z20, Z17, Z13                      // y1 = t1 + u = t1 - i*t3
	VSUBPD Z20, Z17, Z15                      // y3 = t1 - u = t1 + i*t3

	// ----- Lane transpose: move digit a into the register index and digit c
	// into the lanes, so stage 3 is cross-register and the result is
	// lane-contiguous.  Register 4c+b (lane a) -> register 4a+b (lane c).
	// group b=0: Z0,Z4,Z8,Z12
	VSHUFF64X2 $0x44, Z4, Z0, Z16             // [a0,a1,b0,b1]
	VSHUFF64X2 $0xEE, Z4, Z0, Z17             // [a2,a3,b2,b3]
	VSHUFF64X2 $0x44, Z12, Z8, Z18            // [c0,c1,d0,d1]
	VSHUFF64X2 $0xEE, Z12, Z8, Z19            // [c2,c3,d2,d3]
	VSHUFF64X2 $0x88, Z18, Z16, Z0            // [a0,b0,c0,d0]
	VSHUFF64X2 $0xDD, Z18, Z16, Z4            // [a1,b1,c1,d1]
	VSHUFF64X2 $0x88, Z19, Z17, Z8            // [a2,b2,c2,d2]
	VSHUFF64X2 $0xDD, Z19, Z17, Z12           // [a3,b3,c3,d3]
	// group b=1: Z1,Z5,Z9,Z13
	VSHUFF64X2 $0x44, Z5, Z1, Z16             // [a0,a1,b0,b1]
	VSHUFF64X2 $0xEE, Z5, Z1, Z17             // [a2,a3,b2,b3]
	VSHUFF64X2 $0x44, Z13, Z9, Z18            // [c0,c1,d0,d1]
	VSHUFF64X2 $0xEE, Z13, Z9, Z19            // [c2,c3,d2,d3]
	VSHUFF64X2 $0x88, Z18, Z16, Z1            // [a0,b0,c0,d0]
	VSHUFF64X2 $0xDD, Z18, Z16, Z5            // [a1,b1,c1,d1]
	VSHUFF64X2 $0x88, Z19, Z17, Z9            // [a2,b2,c2,d2]
	VSHUFF64X2 $0xDD, Z19, Z17, Z13           // [a3,b3,c3,d3]
	// group b=2: Z2,Z6,Z10,Z14
	VSHUFF64X2 $0x44, Z6, Z2, Z16             // [a0,a1,b0,b1]
	VSHUFF64X2 $0xEE, Z6, Z2, Z17             // [a2,a3,b2,b3]
	VSHUFF64X2 $0x44, Z14, Z10, Z18           // [c0,c1,d0,d1]
	VSHUFF64X2 $0xEE, Z14, Z10, Z19           // [c2,c3,d2,d3]
	VSHUFF64X2 $0x88, Z18, Z16, Z2            // [a0,b0,c0,d0]
	VSHUFF64X2 $0xDD, Z18, Z16, Z6            // [a1,b1,c1,d1]
	VSHUFF64X2 $0x88, Z19, Z17, Z10           // [a2,b2,c2,d2]
	VSHUFF64X2 $0xDD, Z19, Z17, Z14           // [a3,b3,c3,d3]
	// group b=3: Z3,Z7,Z11,Z15
	VSHUFF64X2 $0x44, Z7, Z3, Z16             // [a0,a1,b0,b1]
	VSHUFF64X2 $0xEE, Z7, Z3, Z17             // [a2,a3,b2,b3]
	VSHUFF64X2 $0x44, Z15, Z11, Z18           // [c0,c1,d0,d1]
	VSHUFF64X2 $0xEE, Z15, Z11, Z19           // [c2,c3,d2,d3]
	VSHUFF64X2 $0x88, Z18, Z16, Z3            // [a0,b0,c0,d0]
	VSHUFF64X2 $0xDD, Z18, Z16, Z7            // [a1,b1,c1,d1]
	VSHUFF64X2 $0x88, Z19, Z17, Z11           // [a2,b2,c2,d2]
	VSHUFF64X2 $0xDD, Z19, Z17, Z15           // [a3,b3,c3,d3]

	// ----- Stage 3: 16 radix-4 butterflies over digit a, w = W64^(a*(4b+c))
	// The exponent depends on the lane (c), so the twiddles are per-lane vectors.
	// group b=0: Z0,Z4,Z8,Z12, twiddle exponents a*(0+c)
	VSHUFPD $0x55, Z4, Z4, Z21                // [im,re] of x1*w1 s3 b=0
	VMULPD s3b0a1_im<>(SB), Z21, Z21          // * w.im
	VFMADDSUB231PD s3b0a1_re<>(SB), Z4, Z21   // x1*w1 s3 b=0
	VSHUFPD $0x55, Z8, Z8, Z22                // [im,re] of x2*w2 s3 b=0
	VMULPD s3b0a2_im<>(SB), Z22, Z22          // * w.im
	VFMADDSUB231PD s3b0a2_re<>(SB), Z8, Z22   // x2*w2 s3 b=0
	VSHUFPD $0x55, Z12, Z12, Z23              // [im,re] of x3*w3 s3 b=0
	VMULPD s3b0a3_im<>(SB), Z23, Z23          // * w.im
	VFMADDSUB231PD s3b0a3_re<>(SB), Z12, Z23  // x3*w3 s3 b=0
	VADDPD Z22, Z0, Z16                       // t0 = x0 + x2
	VSUBPD Z22, Z0, Z17                       // t1 = x0 - x2
	VADDPD Z23, Z21, Z18                      // t2 = x1 + x3
	VSUBPD Z23, Z21, Z19                      // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z0                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z8                       // y2 = t0 - t2
	VADDPD Z20, Z17, Z4                       // y1 = t1 + u = t1 - i*t3
	VSUBPD Z20, Z17, Z12                      // y3 = t1 - u = t1 + i*t3
	// group b=1: Z1,Z5,Z9,Z13, twiddle exponents a*(4+c)
	VSHUFPD $0x55, Z5, Z5, Z21                // [im,re] of x1*w1 s3 b=1
	VMULPD s3b1a1_im<>(SB), Z21, Z21          // * w.im
	VFMADDSUB231PD s3b1a1_re<>(SB), Z5, Z21   // x1*w1 s3 b=1
	VSHUFPD $0x55, Z9, Z9, Z22                // [im,re] of x2*w2 s3 b=1
	VMULPD s3b1a2_im<>(SB), Z22, Z22          // * w.im
	VFMADDSUB231PD s3b1a2_re<>(SB), Z9, Z22   // x2*w2 s3 b=1
	VSHUFPD $0x55, Z13, Z13, Z23              // [im,re] of x3*w3 s3 b=1
	VMULPD s3b1a3_im<>(SB), Z23, Z23          // * w.im
	VFMADDSUB231PD s3b1a3_re<>(SB), Z13, Z23  // x3*w3 s3 b=1
	VADDPD Z22, Z1, Z16                       // t0 = x0 + x2
	VSUBPD Z22, Z1, Z17                       // t1 = x0 - x2
	VADDPD Z23, Z21, Z18                      // t2 = x1 + x3
	VSUBPD Z23, Z21, Z19                      // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z1                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z9                       // y2 = t0 - t2
	VADDPD Z20, Z17, Z5                       // y1 = t1 + u = t1 - i*t3
	VSUBPD Z20, Z17, Z13                      // y3 = t1 - u = t1 + i*t3
	// group b=2: Z2,Z6,Z10,Z14, twiddle exponents a*(8+c)
	VSHUFPD $0x55, Z6, Z6, Z21                // [im,re] of x1*w1 s3 b=2
	VMULPD s3b2a1_im<>(SB), Z21, Z21          // * w.im
	VFMADDSUB231PD s3b2a1_re<>(SB), Z6, Z21   // x1*w1 s3 b=2
	VSHUFPD $0x55, Z10, Z10, Z22              // [im,re] of x2*w2 s3 b=2
	VMULPD s3b2a2_im<>(SB), Z22, Z22          // * w.im
	VFMADDSUB231PD s3b2a2_re<>(SB), Z10, Z22  // x2*w2 s3 b=2
	VSHUFPD $0x55, Z14, Z14, Z23              // [im,re] of x3*w3 s3 b=2
	VMULPD s3b2a3_im<>(SB), Z23, Z23          // * w.im
	VFMADDSUB231PD s3b2a3_re<>(SB), Z14, Z23  // x3*w3 s3 b=2
	VADDPD Z22, Z2, Z16                       // t0 = x0 + x2
	VSUBPD Z22, Z2, Z17                       // t1 = x0 - x2
	VADDPD Z23, Z21, Z18                      // t2 = x1 + x3
	VSUBPD Z23, Z21, Z19                      // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z2                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z10                      // y2 = t0 - t2
	VADDPD Z20, Z17, Z6                       // y1 = t1 + u = t1 - i*t3
	VSUBPD Z20, Z17, Z14                      // y3 = t1 - u = t1 + i*t3
	// group b=3: Z3,Z7,Z11,Z15, twiddle exponents a*(12+c)
	VSHUFPD $0x55, Z7, Z7, Z21                // [im,re] of x1*w1 s3 b=3
	VMULPD s3b3a1_im<>(SB), Z21, Z21          // * w.im
	VFMADDSUB231PD s3b3a1_re<>(SB), Z7, Z21   // x1*w1 s3 b=3
	VSHUFPD $0x55, Z11, Z11, Z22              // [im,re] of x2*w2 s3 b=3
	VMULPD s3b3a2_im<>(SB), Z22, Z22          // * w.im
	VFMADDSUB231PD s3b3a2_re<>(SB), Z11, Z22  // x2*w2 s3 b=3
	VSHUFPD $0x55, Z15, Z15, Z23              // [im,re] of x3*w3 s3 b=3
	VMULPD s3b3a3_im<>(SB), Z23, Z23          // * w.im
	VFMADDSUB231PD s3b3a3_re<>(SB), Z15, Z23  // x3*w3 s3 b=3
	VADDPD Z22, Z3, Z16                       // t0 = x0 + x2
	VSUBPD Z22, Z3, Z17                       // t1 = x0 - x2
	VADDPD Z23, Z21, Z18                      // t2 = x1 + x3
	VSUBPD Z23, Z21, Z19                      // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z3                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z11                      // y2 = t0 - t2
	VADDPD Z20, Z17, Z7                       // y1 = t1 + u = t1 - i*t3
	VSUBPD Z20, Z17, Z15                      // y3 = t1 - u = t1 + i*t3

	// Store: register 4a+b holds work[16a+4b .. 16a+4b+3], block number == register.
	VMOVUPD Z0, (R8)                          // dst[0..3] = Z0
	VMOVUPD Z1, 64(R8)                        // dst[4..7] = Z1
	VMOVUPD Z2, 128(R8)                       // dst[8..11] = Z2
	VMOVUPD Z3, 192(R8)                       // dst[12..15] = Z3
	VMOVUPD Z4, 256(R8)                       // dst[16..19] = Z4
	VMOVUPD Z5, 320(R8)                       // dst[20..23] = Z5
	VMOVUPD Z6, 384(R8)                       // dst[24..27] = Z6
	VMOVUPD Z7, 448(R8)                       // dst[28..31] = Z7
	VMOVUPD Z8, 512(R8)                       // dst[32..35] = Z8
	VMOVUPD Z9, 576(R8)                       // dst[36..39] = Z9
	VMOVUPD Z10, 640(R8)                      // dst[40..43] = Z10
	VMOVUPD Z11, 704(R8)                      // dst[44..47] = Z11
	VMOVUPD Z12, 768(R8)                      // dst[48..51] = Z12
	VMOVUPD Z13, 832(R8)                      // dst[52..55] = Z13
	VMOVUPD Z14, 896(R8)                      // dst[56..59] = Z14
	VMOVUPD Z15, 960(R8)                      // dst[60..63] = Z15

	VZEROUPPER
	MOVB $1, ret+96(FP)
	RET

avx512_f64_s64r4_false:
	VZEROUPPER
	MOVB $0, ret+96(FP)
	RET

// ===========================================================================
// Inverse transform, size 64, complex128, radix-4 (with 1/64 scaling)
// ===========================================================================
TEXT ·InverseAVX512Size64Radix4Complex128Asm(SB), NOSPLIT, $0-97
	MOVQ src_len+32(FP), AX                   // n = len(src)
	CMPQ AX, $64
	JNE  avx512_f64_s64r4_inv_false           // only n == 64
	MOVQ dst_len+8(FP), AX
	CMPQ AX, $64
	JL   avx512_f64_s64r4_inv_false           // dst too short
	MOVQ twiddle_len+56(FP), AX
	CMPQ AX, $64
	JL   avx512_f64_s64r4_inv_false           // twiddle too short
	MOVQ scratch_len+80(FP), AX
	CMPQ AX, $64
	JL   avx512_f64_s64r4_inv_false           // scratch too short

	MOVQ dst+0(FP), R8                        // R8 = dst
	MOVQ src+24(FP), R9                       // R9 = src (dst == src is fine: every
	                                          // load happens before the first store)

// Load all 64 complex128 into Z0..Z15. Register k holds src[4k..4k+3];
// read as (c = k>>2, b = k&3) with the lane index carrying digit a, this IS
// the base-4 digit-reversed order, so no bitrev table is needed.
	VMOVUPD (R9), Z0                          // Z0 = src[0..3]
	VMOVUPD 64(R9), Z1                        // Z1 = src[4..7]
	VMOVUPD 128(R9), Z2                       // Z2 = src[8..11]
	VMOVUPD 192(R9), Z3                       // Z3 = src[12..15]
	VMOVUPD 256(R9), Z4                       // Z4 = src[16..19]
	VMOVUPD 320(R9), Z5                       // Z5 = src[20..23]
	VMOVUPD 384(R9), Z6                       // Z6 = src[24..27]
	VMOVUPD 448(R9), Z7                       // Z7 = src[28..31]
	VMOVUPD 512(R9), Z8                       // Z8 = src[32..35]
	VMOVUPD 576(R9), Z9                       // Z9 = src[36..39]
	VMOVUPD 640(R9), Z10                      // Z10 = src[40..43]
	VMOVUPD 704(R9), Z11                      // Z11 = src[44..47]
	VMOVUPD 768(R9), Z12                      // Z12 = src[48..51]
	VMOVUPD 832(R9), Z13                      // Z13 = src[52..55]
	VMOVUPD 896(R9), Z14                      // Z14 = src[56..59]
	VMOVUPD 960(R9), Z15                      // Z15 = src[60..63]
	VMOVUPD negodd<>(SB), Z31                 // sign mask for -i (negate odd doubles)
	// 1/64 broadcast; folded into the stage-3 inputs (see below).
	MOVQ ·sixtyFourth64(SB), AX
	VMOVQ AX, X24
	VBROADCASTSD X24, Z24  // Z24 = [1/64 x8]

	// ----- Stage 1: 16 radix-4 butterflies over digit c (w == 1) -----
	// group b=0: Z0,Z4,Z8,Z12 (4 butterflies, one per lane)
	VADDPD Z8, Z0, Z16                        // t0 = x0 + x2
	VSUBPD Z8, Z0, Z17                        // t1 = x0 - x2
	VADDPD Z12, Z4, Z18                       // t2 = x1 + x3
	VSUBPD Z12, Z4, Z19                       // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z0                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z8                       // y2 = t0 - t2
	VSUBPD Z20, Z17, Z4                       // y1 = t1 - u = t1 + i*t3
	VADDPD Z20, Z17, Z12                      // y3 = t1 + u = t1 - i*t3
	// group b=1: Z1,Z5,Z9,Z13 (4 butterflies, one per lane)
	VADDPD Z9, Z1, Z16                        // t0 = x0 + x2
	VSUBPD Z9, Z1, Z17                        // t1 = x0 - x2
	VADDPD Z13, Z5, Z18                       // t2 = x1 + x3
	VSUBPD Z13, Z5, Z19                       // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z1                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z9                       // y2 = t0 - t2
	VSUBPD Z20, Z17, Z5                       // y1 = t1 - u = t1 + i*t3
	VADDPD Z20, Z17, Z13                      // y3 = t1 + u = t1 - i*t3
	// group b=2: Z2,Z6,Z10,Z14 (4 butterflies, one per lane)
	VADDPD Z10, Z2, Z16                       // t0 = x0 + x2
	VSUBPD Z10, Z2, Z17                       // t1 = x0 - x2
	VADDPD Z14, Z6, Z18                       // t2 = x1 + x3
	VSUBPD Z14, Z6, Z19                       // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z2                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z10                      // y2 = t0 - t2
	VSUBPD Z20, Z17, Z6                       // y1 = t1 - u = t1 + i*t3
	VADDPD Z20, Z17, Z14                      // y3 = t1 + u = t1 - i*t3
	// group b=3: Z3,Z7,Z11,Z15 (4 butterflies, one per lane)
	VADDPD Z11, Z3, Z16                       // t0 = x0 + x2
	VSUBPD Z11, Z3, Z17                       // t1 = x0 - x2
	VADDPD Z15, Z7, Z18                       // t2 = x1 + x3
	VSUBPD Z15, Z7, Z19                       // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z3                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z11                      // y2 = t0 - t2
	VSUBPD Z20, Z17, Z7                       // y1 = t1 - u = t1 + i*t3
	VADDPD Z20, Z17, Z15                      // y3 = t1 + u = t1 - i*t3

	// ----- Stage 2: 16 radix-4 butterflies over digit b, w = W64^(4*b*c) -----
	// group c=0: Z0..Z3, twiddles W64^0, W64^0, W64^0
	VADDPD Z2, Z0, Z16                        // t0 = x0 + x2
	VSUBPD Z2, Z0, Z17                        // t1 = x0 - x2
	VADDPD Z3, Z1, Z18                        // t2 = x1 + x3
	VSUBPD Z3, Z1, Z19                        // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z0                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z2                       // y2 = t0 - t2
	VSUBPD Z20, Z17, Z1                       // y1 = t1 - u = t1 + i*t3
	VADDPD Z20, Z17, Z3                       // y3 = t1 + u = t1 - i*t3
	// group c=1: Z4..Z7, twiddles W64^4, W64^8, W64^12
	VSHUFPD $0x55, Z5, Z5, Z21                // [im,re] of x1*w1 s2 c=1
	VMULPD s2c1b1_im<>(SB), Z21, Z21          // * w.im
	VFMSUBADD231PD s2c1b1_re<>(SB), Z5, Z21   // x1*w1 s2 c=1
	VSHUFPD $0x55, Z6, Z6, Z22                // [im,re] of x2*w2 s2 c=1
	VMULPD s2c1b2_im<>(SB), Z22, Z22          // * w.im
	VFMSUBADD231PD s2c1b2_re<>(SB), Z6, Z22   // x2*w2 s2 c=1
	VSHUFPD $0x55, Z7, Z7, Z23                // [im,re] of x3*w3 s2 c=1
	VMULPD s2c1b3_im<>(SB), Z23, Z23          // * w.im
	VFMSUBADD231PD s2c1b3_re<>(SB), Z7, Z23   // x3*w3 s2 c=1
	VADDPD Z22, Z4, Z16                       // t0 = x0 + x2
	VSUBPD Z22, Z4, Z17                       // t1 = x0 - x2
	VADDPD Z23, Z21, Z18                      // t2 = x1 + x3
	VSUBPD Z23, Z21, Z19                      // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z4                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z6                       // y2 = t0 - t2
	VSUBPD Z20, Z17, Z5                       // y1 = t1 - u = t1 + i*t3
	VADDPD Z20, Z17, Z7                       // y3 = t1 + u = t1 - i*t3
	// group c=2: Z8..Z11, twiddles W64^8, W64^16, W64^24
	VSHUFPD $0x55, Z9, Z9, Z21                // [im,re] of x1*w1 s2 c=2
	VMULPD s2c2b1_im<>(SB), Z21, Z21          // * w.im
	VFMSUBADD231PD s2c2b1_re<>(SB), Z9, Z21   // x1*w1 s2 c=2
	VSHUFPD $0x55, Z10, Z10, Z22              // [im,re] of x2*w2 s2 c=2
	VMULPD s2c2b2_im<>(SB), Z22, Z22          // * w.im
	VFMSUBADD231PD s2c2b2_re<>(SB), Z10, Z22  // x2*w2 s2 c=2
	VSHUFPD $0x55, Z11, Z11, Z23              // [im,re] of x3*w3 s2 c=2
	VMULPD s2c2b3_im<>(SB), Z23, Z23          // * w.im
	VFMSUBADD231PD s2c2b3_re<>(SB), Z11, Z23  // x3*w3 s2 c=2
	VADDPD Z22, Z8, Z16                       // t0 = x0 + x2
	VSUBPD Z22, Z8, Z17                       // t1 = x0 - x2
	VADDPD Z23, Z21, Z18                      // t2 = x1 + x3
	VSUBPD Z23, Z21, Z19                      // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z8                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z10                      // y2 = t0 - t2
	VSUBPD Z20, Z17, Z9                       // y1 = t1 - u = t1 + i*t3
	VADDPD Z20, Z17, Z11                      // y3 = t1 + u = t1 - i*t3
	// group c=3: Z12..Z15, twiddles W64^12, W64^24, W64^36
	VSHUFPD $0x55, Z13, Z13, Z21              // [im,re] of x1*w1 s2 c=3
	VMULPD s2c3b1_im<>(SB), Z21, Z21          // * w.im
	VFMSUBADD231PD s2c3b1_re<>(SB), Z13, Z21  // x1*w1 s2 c=3
	VSHUFPD $0x55, Z14, Z14, Z22              // [im,re] of x2*w2 s2 c=3
	VMULPD s2c3b2_im<>(SB), Z22, Z22          // * w.im
	VFMSUBADD231PD s2c3b2_re<>(SB), Z14, Z22  // x2*w2 s2 c=3
	VSHUFPD $0x55, Z15, Z15, Z23              // [im,re] of x3*w3 s2 c=3
	VMULPD s2c3b3_im<>(SB), Z23, Z23          // * w.im
	VFMSUBADD231PD s2c3b3_re<>(SB), Z15, Z23  // x3*w3 s2 c=3
	VADDPD Z22, Z12, Z16                      // t0 = x0 + x2
	VSUBPD Z22, Z12, Z17                      // t1 = x0 - x2
	VADDPD Z23, Z21, Z18                      // t2 = x1 + x3
	VSUBPD Z23, Z21, Z19                      // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z12                      // y0 = t0 + t2
	VSUBPD Z18, Z16, Z14                      // y2 = t0 - t2
	VSUBPD Z20, Z17, Z13                      // y1 = t1 - u = t1 + i*t3
	VADDPD Z20, Z17, Z15                      // y3 = t1 + u = t1 - i*t3

	// ----- Lane transpose: move digit a into the register index and digit c
	// into the lanes, so stage 3 is cross-register and the result is
	// lane-contiguous.  Register 4c+b (lane a) -> register 4a+b (lane c).
	// group b=0: Z0,Z4,Z8,Z12
	VSHUFF64X2 $0x44, Z4, Z0, Z16             // [a0,a1,b0,b1]
	VSHUFF64X2 $0xEE, Z4, Z0, Z17             // [a2,a3,b2,b3]
	VSHUFF64X2 $0x44, Z12, Z8, Z18            // [c0,c1,d0,d1]
	VSHUFF64X2 $0xEE, Z12, Z8, Z19            // [c2,c3,d2,d3]
	VSHUFF64X2 $0x88, Z18, Z16, Z0            // [a0,b0,c0,d0]
	VSHUFF64X2 $0xDD, Z18, Z16, Z4            // [a1,b1,c1,d1]
	VSHUFF64X2 $0x88, Z19, Z17, Z8            // [a2,b2,c2,d2]
	VSHUFF64X2 $0xDD, Z19, Z17, Z12           // [a3,b3,c3,d3]
	// group b=1: Z1,Z5,Z9,Z13
	VSHUFF64X2 $0x44, Z5, Z1, Z16             // [a0,a1,b0,b1]
	VSHUFF64X2 $0xEE, Z5, Z1, Z17             // [a2,a3,b2,b3]
	VSHUFF64X2 $0x44, Z13, Z9, Z18            // [c0,c1,d0,d1]
	VSHUFF64X2 $0xEE, Z13, Z9, Z19            // [c2,c3,d2,d3]
	VSHUFF64X2 $0x88, Z18, Z16, Z1            // [a0,b0,c0,d0]
	VSHUFF64X2 $0xDD, Z18, Z16, Z5            // [a1,b1,c1,d1]
	VSHUFF64X2 $0x88, Z19, Z17, Z9            // [a2,b2,c2,d2]
	VSHUFF64X2 $0xDD, Z19, Z17, Z13           // [a3,b3,c3,d3]
	// group b=2: Z2,Z6,Z10,Z14
	VSHUFF64X2 $0x44, Z6, Z2, Z16             // [a0,a1,b0,b1]
	VSHUFF64X2 $0xEE, Z6, Z2, Z17             // [a2,a3,b2,b3]
	VSHUFF64X2 $0x44, Z14, Z10, Z18           // [c0,c1,d0,d1]
	VSHUFF64X2 $0xEE, Z14, Z10, Z19           // [c2,c3,d2,d3]
	VSHUFF64X2 $0x88, Z18, Z16, Z2            // [a0,b0,c0,d0]
	VSHUFF64X2 $0xDD, Z18, Z16, Z6            // [a1,b1,c1,d1]
	VSHUFF64X2 $0x88, Z19, Z17, Z10           // [a2,b2,c2,d2]
	VSHUFF64X2 $0xDD, Z19, Z17, Z14           // [a3,b3,c3,d3]
	// group b=3: Z3,Z7,Z11,Z15
	VSHUFF64X2 $0x44, Z7, Z3, Z16             // [a0,a1,b0,b1]
	VSHUFF64X2 $0xEE, Z7, Z3, Z17             // [a2,a3,b2,b3]
	VSHUFF64X2 $0x44, Z15, Z11, Z18           // [c0,c1,d0,d1]
	VSHUFF64X2 $0xEE, Z15, Z11, Z19           // [c2,c3,d2,d3]
	VSHUFF64X2 $0x88, Z18, Z16, Z3            // [a0,b0,c0,d0]
	VSHUFF64X2 $0xDD, Z18, Z16, Z7            // [a1,b1,c1,d1]
	VSHUFF64X2 $0x88, Z19, Z17, Z11           // [a2,b2,c2,d2]
	VSHUFF64X2 $0xDD, Z19, Z17, Z15           // [a3,b3,c3,d3]

	// ----- Stage 3: 16 radix-4 butterflies over digit a, w = W64^(a*(4b+c))
	// The exponent depends on the lane (c), so the twiddles are per-lane vectors.
	// The 1/64 scale is folded into the stage-3 twiddles (a=1,2,3); the
	// untwiddled a=0 inputs (Z0..Z3) are scaled explicitly, so every stage-3
	// input -- and therefore every output -- carries the 1/64 factor.
	VMULPD Z24, Z0, Z0                        // Z0 *= 1/64 (a=0 input, b=0)
	VMULPD Z24, Z1, Z1                        // Z1 *= 1/64 (a=0 input, b=1)
	VMULPD Z24, Z2, Z2                        // Z2 *= 1/64 (a=0 input, b=2)
	VMULPD Z24, Z3, Z3                        // Z3 *= 1/64 (a=0 input, b=3)
	// group b=0: Z0,Z4,Z8,Z12, twiddle exponents a*(0+c)
	VSHUFPD $0x55, Z4, Z4, Z21                // [im,re] of x1*w1 s3 b=0
	VMULPD s3b0a1_im_inv<>(SB), Z21, Z21      // * w.im
	VFMSUBADD231PD s3b0a1_re_inv<>(SB), Z4, Z21 // x1*w1 s3 b=0
	VSHUFPD $0x55, Z8, Z8, Z22                // [im,re] of x2*w2 s3 b=0
	VMULPD s3b0a2_im_inv<>(SB), Z22, Z22      // * w.im
	VFMSUBADD231PD s3b0a2_re_inv<>(SB), Z8, Z22 // x2*w2 s3 b=0
	VSHUFPD $0x55, Z12, Z12, Z23              // [im,re] of x3*w3 s3 b=0
	VMULPD s3b0a3_im_inv<>(SB), Z23, Z23      // * w.im
	VFMSUBADD231PD s3b0a3_re_inv<>(SB), Z12, Z23 // x3*w3 s3 b=0
	VADDPD Z22, Z0, Z16                       // t0 = x0 + x2
	VSUBPD Z22, Z0, Z17                       // t1 = x0 - x2
	VADDPD Z23, Z21, Z18                      // t2 = x1 + x3
	VSUBPD Z23, Z21, Z19                      // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z0                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z8                       // y2 = t0 - t2
	VSUBPD Z20, Z17, Z4                       // y1 = t1 - u = t1 + i*t3
	VADDPD Z20, Z17, Z12                      // y3 = t1 + u = t1 - i*t3
	// group b=1: Z1,Z5,Z9,Z13, twiddle exponents a*(4+c)
	VSHUFPD $0x55, Z5, Z5, Z21                // [im,re] of x1*w1 s3 b=1
	VMULPD s3b1a1_im_inv<>(SB), Z21, Z21      // * w.im
	VFMSUBADD231PD s3b1a1_re_inv<>(SB), Z5, Z21 // x1*w1 s3 b=1
	VSHUFPD $0x55, Z9, Z9, Z22                // [im,re] of x2*w2 s3 b=1
	VMULPD s3b1a2_im_inv<>(SB), Z22, Z22      // * w.im
	VFMSUBADD231PD s3b1a2_re_inv<>(SB), Z9, Z22 // x2*w2 s3 b=1
	VSHUFPD $0x55, Z13, Z13, Z23              // [im,re] of x3*w3 s3 b=1
	VMULPD s3b1a3_im_inv<>(SB), Z23, Z23      // * w.im
	VFMSUBADD231PD s3b1a3_re_inv<>(SB), Z13, Z23 // x3*w3 s3 b=1
	VADDPD Z22, Z1, Z16                       // t0 = x0 + x2
	VSUBPD Z22, Z1, Z17                       // t1 = x0 - x2
	VADDPD Z23, Z21, Z18                      // t2 = x1 + x3
	VSUBPD Z23, Z21, Z19                      // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z1                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z9                       // y2 = t0 - t2
	VSUBPD Z20, Z17, Z5                       // y1 = t1 - u = t1 + i*t3
	VADDPD Z20, Z17, Z13                      // y3 = t1 + u = t1 - i*t3
	// group b=2: Z2,Z6,Z10,Z14, twiddle exponents a*(8+c)
	VSHUFPD $0x55, Z6, Z6, Z21                // [im,re] of x1*w1 s3 b=2
	VMULPD s3b2a1_im_inv<>(SB), Z21, Z21      // * w.im
	VFMSUBADD231PD s3b2a1_re_inv<>(SB), Z6, Z21 // x1*w1 s3 b=2
	VSHUFPD $0x55, Z10, Z10, Z22              // [im,re] of x2*w2 s3 b=2
	VMULPD s3b2a2_im_inv<>(SB), Z22, Z22      // * w.im
	VFMSUBADD231PD s3b2a2_re_inv<>(SB), Z10, Z22 // x2*w2 s3 b=2
	VSHUFPD $0x55, Z14, Z14, Z23              // [im,re] of x3*w3 s3 b=2
	VMULPD s3b2a3_im_inv<>(SB), Z23, Z23      // * w.im
	VFMSUBADD231PD s3b2a3_re_inv<>(SB), Z14, Z23 // x3*w3 s3 b=2
	VADDPD Z22, Z2, Z16                       // t0 = x0 + x2
	VSUBPD Z22, Z2, Z17                       // t1 = x0 - x2
	VADDPD Z23, Z21, Z18                      // t2 = x1 + x3
	VSUBPD Z23, Z21, Z19                      // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z2                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z10                      // y2 = t0 - t2
	VSUBPD Z20, Z17, Z6                       // y1 = t1 - u = t1 + i*t3
	VADDPD Z20, Z17, Z14                      // y3 = t1 + u = t1 - i*t3
	// group b=3: Z3,Z7,Z11,Z15, twiddle exponents a*(12+c)
	VSHUFPD $0x55, Z7, Z7, Z21                // [im,re] of x1*w1 s3 b=3
	VMULPD s3b3a1_im_inv<>(SB), Z21, Z21      // * w.im
	VFMSUBADD231PD s3b3a1_re_inv<>(SB), Z7, Z21 // x1*w1 s3 b=3
	VSHUFPD $0x55, Z11, Z11, Z22              // [im,re] of x2*w2 s3 b=3
	VMULPD s3b3a2_im_inv<>(SB), Z22, Z22      // * w.im
	VFMSUBADD231PD s3b3a2_re_inv<>(SB), Z11, Z22 // x2*w2 s3 b=3
	VSHUFPD $0x55, Z15, Z15, Z23              // [im,re] of x3*w3 s3 b=3
	VMULPD s3b3a3_im_inv<>(SB), Z23, Z23      // * w.im
	VFMSUBADD231PD s3b3a3_re_inv<>(SB), Z15, Z23 // x3*w3 s3 b=3
	VADDPD Z22, Z3, Z16                       // t0 = x0 + x2
	VSUBPD Z22, Z3, Z17                       // t1 = x0 - x2
	VADDPD Z23, Z21, Z18                      // t2 = x1 + x3
	VSUBPD Z23, Z21, Z19                      // t3 = x1 - x3
	VSHUFPD $0x55, Z19, Z19, Z20              // [t3.im, t3.re]
	VPXORQ Z31, Z20, Z20                      // u = -i*t3 = [t3.im, -t3.re]
	VADDPD Z18, Z16, Z3                       // y0 = t0 + t2
	VSUBPD Z18, Z16, Z11                      // y2 = t0 - t2
	VSUBPD Z20, Z17, Z7                       // y1 = t1 - u = t1 + i*t3
	VADDPD Z20, Z17, Z15                      // y3 = t1 + u = t1 - i*t3

	// Store: register 4a+b holds work[16a+4b .. 16a+4b+3], block number == register.
	VMOVUPD Z0, (R8)                          // dst[0..3] = Z0
	VMOVUPD Z1, 64(R8)                        // dst[4..7] = Z1
	VMOVUPD Z2, 128(R8)                       // dst[8..11] = Z2
	VMOVUPD Z3, 192(R8)                       // dst[12..15] = Z3
	VMOVUPD Z4, 256(R8)                       // dst[16..19] = Z4
	VMOVUPD Z5, 320(R8)                       // dst[20..23] = Z5
	VMOVUPD Z6, 384(R8)                       // dst[24..27] = Z6
	VMOVUPD Z7, 448(R8)                       // dst[28..31] = Z7
	VMOVUPD Z8, 512(R8)                       // dst[32..35] = Z8
	VMOVUPD Z9, 576(R8)                       // dst[36..39] = Z9
	VMOVUPD Z10, 640(R8)                      // dst[40..43] = Z10
	VMOVUPD Z11, 704(R8)                      // dst[44..47] = Z11
	VMOVUPD Z12, 768(R8)                      // dst[48..51] = Z12
	VMOVUPD Z13, 832(R8)                      // dst[52..55] = Z13
	VMOVUPD Z14, 896(R8)                      // dst[56..59] = Z14
	VMOVUPD Z15, 960(R8)                      // dst[60..63] = Z15

	VZEROUPPER
	MOVB $1, ret+96(FP)
	RET

avx512_f64_s64r4_inv_false:
	VZEROUPPER
	MOVB $0, ret+96(FP)
	RET

// ===========================================================================
// DATA: sign mask and pre-splatted twiddle constants (file-scoped).
//   s2c<c>b<b>_{re,im} = W64^(4*b*c), broadcast to all four lanes
//   s3b<b>a<a>_{re,im} = [ W64^(a*(4b+c)) : c = 0..3 ], one per lane
//   *_inv              = the same, pre-multiplied by 1/64
// ===========================================================================

DATA negodd<>+0(SB)/8, $0x0000000000000000
DATA negodd<>+8(SB)/8, $0x8000000000000000
DATA negodd<>+16(SB)/8, $0x0000000000000000
DATA negodd<>+24(SB)/8, $0x8000000000000000
DATA negodd<>+32(SB)/8, $0x0000000000000000
DATA negodd<>+40(SB)/8, $0x8000000000000000
DATA negodd<>+48(SB)/8, $0x0000000000000000
DATA negodd<>+56(SB)/8, $0x8000000000000000
GLOBL negodd<>(SB), RODATA|NOPTR, $64

DATA s2c1b1_im<>+0(SB)/8, $0xbfd87de2a6aea963
DATA s2c1b1_im<>+8(SB)/8, $0xbfd87de2a6aea963
DATA s2c1b1_im<>+16(SB)/8, $0xbfd87de2a6aea963
DATA s2c1b1_im<>+24(SB)/8, $0xbfd87de2a6aea963
DATA s2c1b1_im<>+32(SB)/8, $0xbfd87de2a6aea963
DATA s2c1b1_im<>+40(SB)/8, $0xbfd87de2a6aea963
DATA s2c1b1_im<>+48(SB)/8, $0xbfd87de2a6aea963
DATA s2c1b1_im<>+56(SB)/8, $0xbfd87de2a6aea963
GLOBL s2c1b1_im<>(SB), RODATA|NOPTR, $64

DATA s2c1b1_re<>+0(SB)/8, $0x3fed906bcf328d46
DATA s2c1b1_re<>+8(SB)/8, $0x3fed906bcf328d46
DATA s2c1b1_re<>+16(SB)/8, $0x3fed906bcf328d46
DATA s2c1b1_re<>+24(SB)/8, $0x3fed906bcf328d46
DATA s2c1b1_re<>+32(SB)/8, $0x3fed906bcf328d46
DATA s2c1b1_re<>+40(SB)/8, $0x3fed906bcf328d46
DATA s2c1b1_re<>+48(SB)/8, $0x3fed906bcf328d46
DATA s2c1b1_re<>+56(SB)/8, $0x3fed906bcf328d46
GLOBL s2c1b1_re<>(SB), RODATA|NOPTR, $64

DATA s2c1b2_im<>+0(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c1b2_im<>+8(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c1b2_im<>+16(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c1b2_im<>+24(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c1b2_im<>+32(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c1b2_im<>+40(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c1b2_im<>+48(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c1b2_im<>+56(SB)/8, $0xbfe6a09e667f3bcc
GLOBL s2c1b2_im<>(SB), RODATA|NOPTR, $64

DATA s2c1b2_re<>+0(SB)/8, $0x3fe6a09e667f3bcd
DATA s2c1b2_re<>+8(SB)/8, $0x3fe6a09e667f3bcd
DATA s2c1b2_re<>+16(SB)/8, $0x3fe6a09e667f3bcd
DATA s2c1b2_re<>+24(SB)/8, $0x3fe6a09e667f3bcd
DATA s2c1b2_re<>+32(SB)/8, $0x3fe6a09e667f3bcd
DATA s2c1b2_re<>+40(SB)/8, $0x3fe6a09e667f3bcd
DATA s2c1b2_re<>+48(SB)/8, $0x3fe6a09e667f3bcd
DATA s2c1b2_re<>+56(SB)/8, $0x3fe6a09e667f3bcd
GLOBL s2c1b2_re<>(SB), RODATA|NOPTR, $64

DATA s2c1b3_im<>+0(SB)/8, $0xbfed906bcf328d46
DATA s2c1b3_im<>+8(SB)/8, $0xbfed906bcf328d46
DATA s2c1b3_im<>+16(SB)/8, $0xbfed906bcf328d46
DATA s2c1b3_im<>+24(SB)/8, $0xbfed906bcf328d46
DATA s2c1b3_im<>+32(SB)/8, $0xbfed906bcf328d46
DATA s2c1b3_im<>+40(SB)/8, $0xbfed906bcf328d46
DATA s2c1b3_im<>+48(SB)/8, $0xbfed906bcf328d46
DATA s2c1b3_im<>+56(SB)/8, $0xbfed906bcf328d46
GLOBL s2c1b3_im<>(SB), RODATA|NOPTR, $64

DATA s2c1b3_re<>+0(SB)/8, $0x3fd87de2a6aea964
DATA s2c1b3_re<>+8(SB)/8, $0x3fd87de2a6aea964
DATA s2c1b3_re<>+16(SB)/8, $0x3fd87de2a6aea964
DATA s2c1b3_re<>+24(SB)/8, $0x3fd87de2a6aea964
DATA s2c1b3_re<>+32(SB)/8, $0x3fd87de2a6aea964
DATA s2c1b3_re<>+40(SB)/8, $0x3fd87de2a6aea964
DATA s2c1b3_re<>+48(SB)/8, $0x3fd87de2a6aea964
DATA s2c1b3_re<>+56(SB)/8, $0x3fd87de2a6aea964
GLOBL s2c1b3_re<>(SB), RODATA|NOPTR, $64

DATA s2c2b1_im<>+0(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c2b1_im<>+8(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c2b1_im<>+16(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c2b1_im<>+24(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c2b1_im<>+32(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c2b1_im<>+40(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c2b1_im<>+48(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c2b1_im<>+56(SB)/8, $0xbfe6a09e667f3bcc
GLOBL s2c2b1_im<>(SB), RODATA|NOPTR, $64

DATA s2c2b1_re<>+0(SB)/8, $0x3fe6a09e667f3bcd
DATA s2c2b1_re<>+8(SB)/8, $0x3fe6a09e667f3bcd
DATA s2c2b1_re<>+16(SB)/8, $0x3fe6a09e667f3bcd
DATA s2c2b1_re<>+24(SB)/8, $0x3fe6a09e667f3bcd
DATA s2c2b1_re<>+32(SB)/8, $0x3fe6a09e667f3bcd
DATA s2c2b1_re<>+40(SB)/8, $0x3fe6a09e667f3bcd
DATA s2c2b1_re<>+48(SB)/8, $0x3fe6a09e667f3bcd
DATA s2c2b1_re<>+56(SB)/8, $0x3fe6a09e667f3bcd
GLOBL s2c2b1_re<>(SB), RODATA|NOPTR, $64

DATA s2c2b2_im<>+0(SB)/8, $0xbff0000000000000
DATA s2c2b2_im<>+8(SB)/8, $0xbff0000000000000
DATA s2c2b2_im<>+16(SB)/8, $0xbff0000000000000
DATA s2c2b2_im<>+24(SB)/8, $0xbff0000000000000
DATA s2c2b2_im<>+32(SB)/8, $0xbff0000000000000
DATA s2c2b2_im<>+40(SB)/8, $0xbff0000000000000
DATA s2c2b2_im<>+48(SB)/8, $0xbff0000000000000
DATA s2c2b2_im<>+56(SB)/8, $0xbff0000000000000
GLOBL s2c2b2_im<>(SB), RODATA|NOPTR, $64

DATA s2c2b2_re<>+0(SB)/8, $0x3c91a62633145c00
DATA s2c2b2_re<>+8(SB)/8, $0x3c91a62633145c00
DATA s2c2b2_re<>+16(SB)/8, $0x3c91a62633145c00
DATA s2c2b2_re<>+24(SB)/8, $0x3c91a62633145c00
DATA s2c2b2_re<>+32(SB)/8, $0x3c91a62633145c00
DATA s2c2b2_re<>+40(SB)/8, $0x3c91a62633145c00
DATA s2c2b2_re<>+48(SB)/8, $0x3c91a62633145c00
DATA s2c2b2_re<>+56(SB)/8, $0x3c91a62633145c00
GLOBL s2c2b2_re<>(SB), RODATA|NOPTR, $64

DATA s2c2b3_im<>+0(SB)/8, $0xbfe6a09e667f3bcd
DATA s2c2b3_im<>+8(SB)/8, $0xbfe6a09e667f3bcd
DATA s2c2b3_im<>+16(SB)/8, $0xbfe6a09e667f3bcd
DATA s2c2b3_im<>+24(SB)/8, $0xbfe6a09e667f3bcd
DATA s2c2b3_im<>+32(SB)/8, $0xbfe6a09e667f3bcd
DATA s2c2b3_im<>+40(SB)/8, $0xbfe6a09e667f3bcd
DATA s2c2b3_im<>+48(SB)/8, $0xbfe6a09e667f3bcd
DATA s2c2b3_im<>+56(SB)/8, $0xbfe6a09e667f3bcd
GLOBL s2c2b3_im<>(SB), RODATA|NOPTR, $64

DATA s2c2b3_re<>+0(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c2b3_re<>+8(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c2b3_re<>+16(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c2b3_re<>+24(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c2b3_re<>+32(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c2b3_re<>+40(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c2b3_re<>+48(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c2b3_re<>+56(SB)/8, $0xbfe6a09e667f3bcc
GLOBL s2c2b3_re<>(SB), RODATA|NOPTR, $64

DATA s2c3b1_im<>+0(SB)/8, $0xbfed906bcf328d46
DATA s2c3b1_im<>+8(SB)/8, $0xbfed906bcf328d46
DATA s2c3b1_im<>+16(SB)/8, $0xbfed906bcf328d46
DATA s2c3b1_im<>+24(SB)/8, $0xbfed906bcf328d46
DATA s2c3b1_im<>+32(SB)/8, $0xbfed906bcf328d46
DATA s2c3b1_im<>+40(SB)/8, $0xbfed906bcf328d46
DATA s2c3b1_im<>+48(SB)/8, $0xbfed906bcf328d46
DATA s2c3b1_im<>+56(SB)/8, $0xbfed906bcf328d46
GLOBL s2c3b1_im<>(SB), RODATA|NOPTR, $64

DATA s2c3b1_re<>+0(SB)/8, $0x3fd87de2a6aea964
DATA s2c3b1_re<>+8(SB)/8, $0x3fd87de2a6aea964
DATA s2c3b1_re<>+16(SB)/8, $0x3fd87de2a6aea964
DATA s2c3b1_re<>+24(SB)/8, $0x3fd87de2a6aea964
DATA s2c3b1_re<>+32(SB)/8, $0x3fd87de2a6aea964
DATA s2c3b1_re<>+40(SB)/8, $0x3fd87de2a6aea964
DATA s2c3b1_re<>+48(SB)/8, $0x3fd87de2a6aea964
DATA s2c3b1_re<>+56(SB)/8, $0x3fd87de2a6aea964
GLOBL s2c3b1_re<>(SB), RODATA|NOPTR, $64

DATA s2c3b2_im<>+0(SB)/8, $0xbfe6a09e667f3bcd
DATA s2c3b2_im<>+8(SB)/8, $0xbfe6a09e667f3bcd
DATA s2c3b2_im<>+16(SB)/8, $0xbfe6a09e667f3bcd
DATA s2c3b2_im<>+24(SB)/8, $0xbfe6a09e667f3bcd
DATA s2c3b2_im<>+32(SB)/8, $0xbfe6a09e667f3bcd
DATA s2c3b2_im<>+40(SB)/8, $0xbfe6a09e667f3bcd
DATA s2c3b2_im<>+48(SB)/8, $0xbfe6a09e667f3bcd
DATA s2c3b2_im<>+56(SB)/8, $0xbfe6a09e667f3bcd
GLOBL s2c3b2_im<>(SB), RODATA|NOPTR, $64

DATA s2c3b2_re<>+0(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c3b2_re<>+8(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c3b2_re<>+16(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c3b2_re<>+24(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c3b2_re<>+32(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c3b2_re<>+40(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c3b2_re<>+48(SB)/8, $0xbfe6a09e667f3bcc
DATA s2c3b2_re<>+56(SB)/8, $0xbfe6a09e667f3bcc
GLOBL s2c3b2_re<>(SB), RODATA|NOPTR, $64

DATA s2c3b3_im<>+0(SB)/8, $0x3fd87de2a6aea961
DATA s2c3b3_im<>+8(SB)/8, $0x3fd87de2a6aea961
DATA s2c3b3_im<>+16(SB)/8, $0x3fd87de2a6aea961
DATA s2c3b3_im<>+24(SB)/8, $0x3fd87de2a6aea961
DATA s2c3b3_im<>+32(SB)/8, $0x3fd87de2a6aea961
DATA s2c3b3_im<>+40(SB)/8, $0x3fd87de2a6aea961
DATA s2c3b3_im<>+48(SB)/8, $0x3fd87de2a6aea961
DATA s2c3b3_im<>+56(SB)/8, $0x3fd87de2a6aea961
GLOBL s2c3b3_im<>(SB), RODATA|NOPTR, $64

DATA s2c3b3_re<>+0(SB)/8, $0xbfed906bcf328d47
DATA s2c3b3_re<>+8(SB)/8, $0xbfed906bcf328d47
DATA s2c3b3_re<>+16(SB)/8, $0xbfed906bcf328d47
DATA s2c3b3_re<>+24(SB)/8, $0xbfed906bcf328d47
DATA s2c3b3_re<>+32(SB)/8, $0xbfed906bcf328d47
DATA s2c3b3_re<>+40(SB)/8, $0xbfed906bcf328d47
DATA s2c3b3_re<>+48(SB)/8, $0xbfed906bcf328d47
DATA s2c3b3_re<>+56(SB)/8, $0xbfed906bcf328d47
GLOBL s2c3b3_re<>(SB), RODATA|NOPTR, $64

DATA s3b0a1_im<>+0(SB)/8, $0x8000000000000000
DATA s3b0a1_im<>+8(SB)/8, $0x8000000000000000
DATA s3b0a1_im<>+16(SB)/8, $0xbfb917a6bc29b42c
DATA s3b0a1_im<>+24(SB)/8, $0xbfb917a6bc29b42c
DATA s3b0a1_im<>+32(SB)/8, $0xbfc8f8b83c69a60a
DATA s3b0a1_im<>+40(SB)/8, $0xbfc8f8b83c69a60a
DATA s3b0a1_im<>+48(SB)/8, $0xbfd294062ed59f05
DATA s3b0a1_im<>+56(SB)/8, $0xbfd294062ed59f05
GLOBL s3b0a1_im<>(SB), RODATA|NOPTR, $64

DATA s3b0a1_im_inv<>+0(SB)/8, $0x8000000000000000
DATA s3b0a1_im_inv<>+8(SB)/8, $0x8000000000000000
DATA s3b0a1_im_inv<>+16(SB)/8, $0xbf5917a6bc29b42c
DATA s3b0a1_im_inv<>+24(SB)/8, $0xbf5917a6bc29b42c
DATA s3b0a1_im_inv<>+32(SB)/8, $0xbf68f8b83c69a60a
DATA s3b0a1_im_inv<>+40(SB)/8, $0xbf68f8b83c69a60a
DATA s3b0a1_im_inv<>+48(SB)/8, $0xbf7294062ed59f05
DATA s3b0a1_im_inv<>+56(SB)/8, $0xbf7294062ed59f05
GLOBL s3b0a1_im_inv<>(SB), RODATA|NOPTR, $64

DATA s3b0a1_re<>+0(SB)/8, $0x3ff0000000000000
DATA s3b0a1_re<>+8(SB)/8, $0x3ff0000000000000
DATA s3b0a1_re<>+16(SB)/8, $0x3fefd88da3d12525
DATA s3b0a1_re<>+24(SB)/8, $0x3fefd88da3d12525
DATA s3b0a1_re<>+32(SB)/8, $0x3fef6297cff75cb0
DATA s3b0a1_re<>+40(SB)/8, $0x3fef6297cff75cb0
DATA s3b0a1_re<>+48(SB)/8, $0x3fee9f4156c62dda
DATA s3b0a1_re<>+56(SB)/8, $0x3fee9f4156c62dda
GLOBL s3b0a1_re<>(SB), RODATA|NOPTR, $64

DATA s3b0a1_re_inv<>+0(SB)/8, $0x3f90000000000000
DATA s3b0a1_re_inv<>+8(SB)/8, $0x3f90000000000000
DATA s3b0a1_re_inv<>+16(SB)/8, $0x3f8fd88da3d12525
DATA s3b0a1_re_inv<>+24(SB)/8, $0x3f8fd88da3d12525
DATA s3b0a1_re_inv<>+32(SB)/8, $0x3f8f6297cff75cb0
DATA s3b0a1_re_inv<>+40(SB)/8, $0x3f8f6297cff75cb0
DATA s3b0a1_re_inv<>+48(SB)/8, $0x3f8e9f4156c62dda
DATA s3b0a1_re_inv<>+56(SB)/8, $0x3f8e9f4156c62dda
GLOBL s3b0a1_re_inv<>(SB), RODATA|NOPTR, $64

DATA s3b0a2_im<>+0(SB)/8, $0x8000000000000000
DATA s3b0a2_im<>+8(SB)/8, $0x8000000000000000
DATA s3b0a2_im<>+16(SB)/8, $0xbfc8f8b83c69a60a
DATA s3b0a2_im<>+24(SB)/8, $0xbfc8f8b83c69a60a
DATA s3b0a2_im<>+32(SB)/8, $0xbfd87de2a6aea963
DATA s3b0a2_im<>+40(SB)/8, $0xbfd87de2a6aea963
DATA s3b0a2_im<>+48(SB)/8, $0xbfe1c73b39ae68c8
DATA s3b0a2_im<>+56(SB)/8, $0xbfe1c73b39ae68c8
GLOBL s3b0a2_im<>(SB), RODATA|NOPTR, $64

DATA s3b0a2_im_inv<>+0(SB)/8, $0x8000000000000000
DATA s3b0a2_im_inv<>+8(SB)/8, $0x8000000000000000
DATA s3b0a2_im_inv<>+16(SB)/8, $0xbf68f8b83c69a60a
DATA s3b0a2_im_inv<>+24(SB)/8, $0xbf68f8b83c69a60a
DATA s3b0a2_im_inv<>+32(SB)/8, $0xbf787de2a6aea963
DATA s3b0a2_im_inv<>+40(SB)/8, $0xbf787de2a6aea963
DATA s3b0a2_im_inv<>+48(SB)/8, $0xbf81c73b39ae68c8
DATA s3b0a2_im_inv<>+56(SB)/8, $0xbf81c73b39ae68c8
GLOBL s3b0a2_im_inv<>(SB), RODATA|NOPTR, $64

DATA s3b0a2_re<>+0(SB)/8, $0x3ff0000000000000
DATA s3b0a2_re<>+8(SB)/8, $0x3ff0000000000000
DATA s3b0a2_re<>+16(SB)/8, $0x3fef6297cff75cb0
DATA s3b0a2_re<>+24(SB)/8, $0x3fef6297cff75cb0
DATA s3b0a2_re<>+32(SB)/8, $0x3fed906bcf328d46
DATA s3b0a2_re<>+40(SB)/8, $0x3fed906bcf328d46
DATA s3b0a2_re<>+48(SB)/8, $0x3fea9b66290ea1a4
DATA s3b0a2_re<>+56(SB)/8, $0x3fea9b66290ea1a4
GLOBL s3b0a2_re<>(SB), RODATA|NOPTR, $64

DATA s3b0a2_re_inv<>+0(SB)/8, $0x3f90000000000000
DATA s3b0a2_re_inv<>+8(SB)/8, $0x3f90000000000000
DATA s3b0a2_re_inv<>+16(SB)/8, $0x3f8f6297cff75cb0
DATA s3b0a2_re_inv<>+24(SB)/8, $0x3f8f6297cff75cb0
DATA s3b0a2_re_inv<>+32(SB)/8, $0x3f8d906bcf328d46
DATA s3b0a2_re_inv<>+40(SB)/8, $0x3f8d906bcf328d46
DATA s3b0a2_re_inv<>+48(SB)/8, $0x3f8a9b66290ea1a4
DATA s3b0a2_re_inv<>+56(SB)/8, $0x3f8a9b66290ea1a4
GLOBL s3b0a2_re_inv<>(SB), RODATA|NOPTR, $64

DATA s3b0a3_im<>+0(SB)/8, $0x8000000000000000
DATA s3b0a3_im<>+8(SB)/8, $0x8000000000000000
DATA s3b0a3_im<>+16(SB)/8, $0xbfd294062ed59f05
DATA s3b0a3_im<>+24(SB)/8, $0xbfd294062ed59f05
DATA s3b0a3_im<>+32(SB)/8, $0xbfe1c73b39ae68c8
DATA s3b0a3_im<>+40(SB)/8, $0xbfe1c73b39ae68c8
DATA s3b0a3_im<>+48(SB)/8, $0xbfe8bc806b151740
DATA s3b0a3_im<>+56(SB)/8, $0xbfe8bc806b151740
GLOBL s3b0a3_im<>(SB), RODATA|NOPTR, $64

DATA s3b0a3_im_inv<>+0(SB)/8, $0x8000000000000000
DATA s3b0a3_im_inv<>+8(SB)/8, $0x8000000000000000
DATA s3b0a3_im_inv<>+16(SB)/8, $0xbf7294062ed59f05
DATA s3b0a3_im_inv<>+24(SB)/8, $0xbf7294062ed59f05
DATA s3b0a3_im_inv<>+32(SB)/8, $0xbf81c73b39ae68c8
DATA s3b0a3_im_inv<>+40(SB)/8, $0xbf81c73b39ae68c8
DATA s3b0a3_im_inv<>+48(SB)/8, $0xbf88bc806b151740
DATA s3b0a3_im_inv<>+56(SB)/8, $0xbf88bc806b151740
GLOBL s3b0a3_im_inv<>(SB), RODATA|NOPTR, $64

DATA s3b0a3_re<>+0(SB)/8, $0x3ff0000000000000
DATA s3b0a3_re<>+8(SB)/8, $0x3ff0000000000000
DATA s3b0a3_re<>+16(SB)/8, $0x3fee9f4156c62dda
DATA s3b0a3_re<>+24(SB)/8, $0x3fee9f4156c62dda
DATA s3b0a3_re<>+32(SB)/8, $0x3fea9b66290ea1a4
DATA s3b0a3_re<>+40(SB)/8, $0x3fea9b66290ea1a4
DATA s3b0a3_re<>+48(SB)/8, $0x3fe44cf325091dd7
DATA s3b0a3_re<>+56(SB)/8, $0x3fe44cf325091dd7
GLOBL s3b0a3_re<>(SB), RODATA|NOPTR, $64

DATA s3b0a3_re_inv<>+0(SB)/8, $0x3f90000000000000
DATA s3b0a3_re_inv<>+8(SB)/8, $0x3f90000000000000
DATA s3b0a3_re_inv<>+16(SB)/8, $0x3f8e9f4156c62dda
DATA s3b0a3_re_inv<>+24(SB)/8, $0x3f8e9f4156c62dda
DATA s3b0a3_re_inv<>+32(SB)/8, $0x3f8a9b66290ea1a4
DATA s3b0a3_re_inv<>+40(SB)/8, $0x3f8a9b66290ea1a4
DATA s3b0a3_re_inv<>+48(SB)/8, $0x3f844cf325091dd7
DATA s3b0a3_re_inv<>+56(SB)/8, $0x3f844cf325091dd7
GLOBL s3b0a3_re_inv<>(SB), RODATA|NOPTR, $64

DATA s3b1a1_im<>+0(SB)/8, $0xbfd87de2a6aea963
DATA s3b1a1_im<>+8(SB)/8, $0xbfd87de2a6aea963
DATA s3b1a1_im<>+16(SB)/8, $0xbfde2b5d3806f63b
DATA s3b1a1_im<>+24(SB)/8, $0xbfde2b5d3806f63b
DATA s3b1a1_im<>+32(SB)/8, $0xbfe1c73b39ae68c8
DATA s3b1a1_im<>+40(SB)/8, $0xbfe1c73b39ae68c8
DATA s3b1a1_im<>+48(SB)/8, $0xbfe44cf325091dd6
DATA s3b1a1_im<>+56(SB)/8, $0xbfe44cf325091dd6
GLOBL s3b1a1_im<>(SB), RODATA|NOPTR, $64

DATA s3b1a1_im_inv<>+0(SB)/8, $0xbf787de2a6aea963
DATA s3b1a1_im_inv<>+8(SB)/8, $0xbf787de2a6aea963
DATA s3b1a1_im_inv<>+16(SB)/8, $0xbf7e2b5d3806f63b
DATA s3b1a1_im_inv<>+24(SB)/8, $0xbf7e2b5d3806f63b
DATA s3b1a1_im_inv<>+32(SB)/8, $0xbf81c73b39ae68c8
DATA s3b1a1_im_inv<>+40(SB)/8, $0xbf81c73b39ae68c8
DATA s3b1a1_im_inv<>+48(SB)/8, $0xbf844cf325091dd6
DATA s3b1a1_im_inv<>+56(SB)/8, $0xbf844cf325091dd6
GLOBL s3b1a1_im_inv<>(SB), RODATA|NOPTR, $64

DATA s3b1a1_re<>+0(SB)/8, $0x3fed906bcf328d46
DATA s3b1a1_re<>+8(SB)/8, $0x3fed906bcf328d46
DATA s3b1a1_re<>+16(SB)/8, $0x3fec38b2f180bdb1
DATA s3b1a1_re<>+24(SB)/8, $0x3fec38b2f180bdb1
DATA s3b1a1_re<>+32(SB)/8, $0x3fea9b66290ea1a4
DATA s3b1a1_re<>+40(SB)/8, $0x3fea9b66290ea1a4
DATA s3b1a1_re<>+48(SB)/8, $0x3fe8bc806b151741
DATA s3b1a1_re<>+56(SB)/8, $0x3fe8bc806b151741
GLOBL s3b1a1_re<>(SB), RODATA|NOPTR, $64

DATA s3b1a1_re_inv<>+0(SB)/8, $0x3f8d906bcf328d46
DATA s3b1a1_re_inv<>+8(SB)/8, $0x3f8d906bcf328d46
DATA s3b1a1_re_inv<>+16(SB)/8, $0x3f8c38b2f180bdb1
DATA s3b1a1_re_inv<>+24(SB)/8, $0x3f8c38b2f180bdb1
DATA s3b1a1_re_inv<>+32(SB)/8, $0x3f8a9b66290ea1a4
DATA s3b1a1_re_inv<>+40(SB)/8, $0x3f8a9b66290ea1a4
DATA s3b1a1_re_inv<>+48(SB)/8, $0x3f88bc806b151741
DATA s3b1a1_re_inv<>+56(SB)/8, $0x3f88bc806b151741
GLOBL s3b1a1_re_inv<>(SB), RODATA|NOPTR, $64

DATA s3b1a2_im<>+0(SB)/8, $0xbfe6a09e667f3bcc
DATA s3b1a2_im<>+8(SB)/8, $0xbfe6a09e667f3bcc
DATA s3b1a2_im<>+16(SB)/8, $0xbfea9b66290ea1a3
DATA s3b1a2_im<>+24(SB)/8, $0xbfea9b66290ea1a3
DATA s3b1a2_im<>+32(SB)/8, $0xbfed906bcf328d46
DATA s3b1a2_im<>+40(SB)/8, $0xbfed906bcf328d46
DATA s3b1a2_im<>+48(SB)/8, $0xbfef6297cff75cb0
DATA s3b1a2_im<>+56(SB)/8, $0xbfef6297cff75cb0
GLOBL s3b1a2_im<>(SB), RODATA|NOPTR, $64

DATA s3b1a2_im_inv<>+0(SB)/8, $0xbf86a09e667f3bcc
DATA s3b1a2_im_inv<>+8(SB)/8, $0xbf86a09e667f3bcc
DATA s3b1a2_im_inv<>+16(SB)/8, $0xbf8a9b66290ea1a3
DATA s3b1a2_im_inv<>+24(SB)/8, $0xbf8a9b66290ea1a3
DATA s3b1a2_im_inv<>+32(SB)/8, $0xbf8d906bcf328d46
DATA s3b1a2_im_inv<>+40(SB)/8, $0xbf8d906bcf328d46
DATA s3b1a2_im_inv<>+48(SB)/8, $0xbf8f6297cff75cb0
DATA s3b1a2_im_inv<>+56(SB)/8, $0xbf8f6297cff75cb0
GLOBL s3b1a2_im_inv<>(SB), RODATA|NOPTR, $64

DATA s3b1a2_re<>+0(SB)/8, $0x3fe6a09e667f3bcd
DATA s3b1a2_re<>+8(SB)/8, $0x3fe6a09e667f3bcd
DATA s3b1a2_re<>+16(SB)/8, $0x3fe1c73b39ae68c9
DATA s3b1a2_re<>+24(SB)/8, $0x3fe1c73b39ae68c9
DATA s3b1a2_re<>+32(SB)/8, $0x3fd87de2a6aea964
DATA s3b1a2_re<>+40(SB)/8, $0x3fd87de2a6aea964
DATA s3b1a2_re<>+48(SB)/8, $0x3fc8f8b83c69a60c
DATA s3b1a2_re<>+56(SB)/8, $0x3fc8f8b83c69a60c
GLOBL s3b1a2_re<>(SB), RODATA|NOPTR, $64

DATA s3b1a2_re_inv<>+0(SB)/8, $0x3f86a09e667f3bcd
DATA s3b1a2_re_inv<>+8(SB)/8, $0x3f86a09e667f3bcd
DATA s3b1a2_re_inv<>+16(SB)/8, $0x3f81c73b39ae68c9
DATA s3b1a2_re_inv<>+24(SB)/8, $0x3f81c73b39ae68c9
DATA s3b1a2_re_inv<>+32(SB)/8, $0x3f787de2a6aea964
DATA s3b1a2_re_inv<>+40(SB)/8, $0x3f787de2a6aea964
DATA s3b1a2_re_inv<>+48(SB)/8, $0x3f68f8b83c69a60c
DATA s3b1a2_re_inv<>+56(SB)/8, $0x3f68f8b83c69a60c
GLOBL s3b1a2_re_inv<>(SB), RODATA|NOPTR, $64

DATA s3b1a3_im<>+0(SB)/8, $0xbfed906bcf328d46
DATA s3b1a3_im<>+8(SB)/8, $0xbfed906bcf328d46
DATA s3b1a3_im<>+16(SB)/8, $0xbfefd88da3d12525
DATA s3b1a3_im<>+24(SB)/8, $0xbfefd88da3d12525
DATA s3b1a3_im<>+32(SB)/8, $0xbfef6297cff75cb0
DATA s3b1a3_im<>+40(SB)/8, $0xbfef6297cff75cb0
DATA s3b1a3_im<>+48(SB)/8, $0xbfec38b2f180bdb0
DATA s3b1a3_im<>+56(SB)/8, $0xbfec38b2f180bdb0
GLOBL s3b1a3_im<>(SB), RODATA|NOPTR, $64

DATA s3b1a3_im_inv<>+0(SB)/8, $0xbf8d906bcf328d46
DATA s3b1a3_im_inv<>+8(SB)/8, $0xbf8d906bcf328d46
DATA s3b1a3_im_inv<>+16(SB)/8, $0xbf8fd88da3d12525
DATA s3b1a3_im_inv<>+24(SB)/8, $0xbf8fd88da3d12525
DATA s3b1a3_im_inv<>+32(SB)/8, $0xbf8f6297cff75cb0
DATA s3b1a3_im_inv<>+40(SB)/8, $0xbf8f6297cff75cb0
DATA s3b1a3_im_inv<>+48(SB)/8, $0xbf8c38b2f180bdb0
DATA s3b1a3_im_inv<>+56(SB)/8, $0xbf8c38b2f180bdb0
GLOBL s3b1a3_im_inv<>(SB), RODATA|NOPTR, $64

DATA s3b1a3_re<>+0(SB)/8, $0x3fd87de2a6aea964
DATA s3b1a3_re<>+8(SB)/8, $0x3fd87de2a6aea964
DATA s3b1a3_re<>+16(SB)/8, $0x3fb917a6bc29b438
DATA s3b1a3_re<>+24(SB)/8, $0x3fb917a6bc29b438
DATA s3b1a3_re<>+32(SB)/8, $0xbfc8f8b83c69a608
DATA s3b1a3_re<>+40(SB)/8, $0xbfc8f8b83c69a608
DATA s3b1a3_re<>+48(SB)/8, $0xbfde2b5d3806f63c
DATA s3b1a3_re<>+56(SB)/8, $0xbfde2b5d3806f63c
GLOBL s3b1a3_re<>(SB), RODATA|NOPTR, $64

DATA s3b1a3_re_inv<>+0(SB)/8, $0x3f787de2a6aea964
DATA s3b1a3_re_inv<>+8(SB)/8, $0x3f787de2a6aea964
DATA s3b1a3_re_inv<>+16(SB)/8, $0x3f5917a6bc29b438
DATA s3b1a3_re_inv<>+24(SB)/8, $0x3f5917a6bc29b438
DATA s3b1a3_re_inv<>+32(SB)/8, $0xbf68f8b83c69a608
DATA s3b1a3_re_inv<>+40(SB)/8, $0xbf68f8b83c69a608
DATA s3b1a3_re_inv<>+48(SB)/8, $0xbf7e2b5d3806f63c
DATA s3b1a3_re_inv<>+56(SB)/8, $0xbf7e2b5d3806f63c
GLOBL s3b1a3_re_inv<>(SB), RODATA|NOPTR, $64

DATA s3b2a1_im<>+0(SB)/8, $0xbfe6a09e667f3bcc
DATA s3b2a1_im<>+8(SB)/8, $0xbfe6a09e667f3bcc
DATA s3b2a1_im<>+16(SB)/8, $0xbfe8bc806b151740
DATA s3b2a1_im<>+24(SB)/8, $0xbfe8bc806b151740
DATA s3b2a1_im<>+32(SB)/8, $0xbfea9b66290ea1a3
DATA s3b2a1_im<>+40(SB)/8, $0xbfea9b66290ea1a3
DATA s3b2a1_im<>+48(SB)/8, $0xbfec38b2f180bdb0
DATA s3b2a1_im<>+56(SB)/8, $0xbfec38b2f180bdb0
GLOBL s3b2a1_im<>(SB), RODATA|NOPTR, $64

DATA s3b2a1_im_inv<>+0(SB)/8, $0xbf86a09e667f3bcc
DATA s3b2a1_im_inv<>+8(SB)/8, $0xbf86a09e667f3bcc
DATA s3b2a1_im_inv<>+16(SB)/8, $0xbf88bc806b151740
DATA s3b2a1_im_inv<>+24(SB)/8, $0xbf88bc806b151740
DATA s3b2a1_im_inv<>+32(SB)/8, $0xbf8a9b66290ea1a3
DATA s3b2a1_im_inv<>+40(SB)/8, $0xbf8a9b66290ea1a3
DATA s3b2a1_im_inv<>+48(SB)/8, $0xbf8c38b2f180bdb0
DATA s3b2a1_im_inv<>+56(SB)/8, $0xbf8c38b2f180bdb0
GLOBL s3b2a1_im_inv<>(SB), RODATA|NOPTR, $64

DATA s3b2a1_re<>+0(SB)/8, $0x3fe6a09e667f3bcd
DATA s3b2a1_re<>+8(SB)/8, $0x3fe6a09e667f3bcd
DATA s3b2a1_re<>+16(SB)/8, $0x3fe44cf325091dd7
DATA s3b2a1_re<>+24(SB)/8, $0x3fe44cf325091dd7
DATA s3b2a1_re<>+32(SB)/8, $0x3fe1c73b39ae68c9
DATA s3b2a1_re<>+40(SB)/8, $0x3fe1c73b39ae68c9
DATA s3b2a1_re<>+48(SB)/8, $0x3fde2b5d3806f63e
DATA s3b2a1_re<>+56(SB)/8, $0x3fde2b5d3806f63e
GLOBL s3b2a1_re<>(SB), RODATA|NOPTR, $64

DATA s3b2a1_re_inv<>+0(SB)/8, $0x3f86a09e667f3bcd
DATA s3b2a1_re_inv<>+8(SB)/8, $0x3f86a09e667f3bcd
DATA s3b2a1_re_inv<>+16(SB)/8, $0x3f844cf325091dd7
DATA s3b2a1_re_inv<>+24(SB)/8, $0x3f844cf325091dd7
DATA s3b2a1_re_inv<>+32(SB)/8, $0x3f81c73b39ae68c9
DATA s3b2a1_re_inv<>+40(SB)/8, $0x3f81c73b39ae68c9
DATA s3b2a1_re_inv<>+48(SB)/8, $0x3f7e2b5d3806f63e
DATA s3b2a1_re_inv<>+56(SB)/8, $0x3f7e2b5d3806f63e
GLOBL s3b2a1_re_inv<>(SB), RODATA|NOPTR, $64

DATA s3b2a2_im<>+0(SB)/8, $0xbff0000000000000
DATA s3b2a2_im<>+8(SB)/8, $0xbff0000000000000
DATA s3b2a2_im<>+16(SB)/8, $0xbfef6297cff75cb0
DATA s3b2a2_im<>+24(SB)/8, $0xbfef6297cff75cb0
DATA s3b2a2_im<>+32(SB)/8, $0xbfed906bcf328d46
DATA s3b2a2_im<>+40(SB)/8, $0xbfed906bcf328d46
DATA s3b2a2_im<>+48(SB)/8, $0xbfea9b66290ea1a4
DATA s3b2a2_im<>+56(SB)/8, $0xbfea9b66290ea1a4
GLOBL s3b2a2_im<>(SB), RODATA|NOPTR, $64

DATA s3b2a2_im_inv<>+0(SB)/8, $0xbf90000000000000
DATA s3b2a2_im_inv<>+8(SB)/8, $0xbf90000000000000
DATA s3b2a2_im_inv<>+16(SB)/8, $0xbf8f6297cff75cb0
DATA s3b2a2_im_inv<>+24(SB)/8, $0xbf8f6297cff75cb0
DATA s3b2a2_im_inv<>+32(SB)/8, $0xbf8d906bcf328d46
DATA s3b2a2_im_inv<>+40(SB)/8, $0xbf8d906bcf328d46
DATA s3b2a2_im_inv<>+48(SB)/8, $0xbf8a9b66290ea1a4
DATA s3b2a2_im_inv<>+56(SB)/8, $0xbf8a9b66290ea1a4
GLOBL s3b2a2_im_inv<>(SB), RODATA|NOPTR, $64

DATA s3b2a2_re<>+0(SB)/8, $0x3c91a62633145c00
DATA s3b2a2_re<>+8(SB)/8, $0x3c91a62633145c00
DATA s3b2a2_re<>+16(SB)/8, $0xbfc8f8b83c69a608
DATA s3b2a2_re<>+24(SB)/8, $0xbfc8f8b83c69a608
DATA s3b2a2_re<>+32(SB)/8, $0xbfd87de2a6aea962
DATA s3b2a2_re<>+40(SB)/8, $0xbfd87de2a6aea962
DATA s3b2a2_re<>+48(SB)/8, $0xbfe1c73b39ae68c6
DATA s3b2a2_re<>+56(SB)/8, $0xbfe1c73b39ae68c6
GLOBL s3b2a2_re<>(SB), RODATA|NOPTR, $64

DATA s3b2a2_re_inv<>+0(SB)/8, $0x3c31a62633145c00
DATA s3b2a2_re_inv<>+8(SB)/8, $0x3c31a62633145c00
DATA s3b2a2_re_inv<>+16(SB)/8, $0xbf68f8b83c69a608
DATA s3b2a2_re_inv<>+24(SB)/8, $0xbf68f8b83c69a608
DATA s3b2a2_re_inv<>+32(SB)/8, $0xbf787de2a6aea962
DATA s3b2a2_re_inv<>+40(SB)/8, $0xbf787de2a6aea962
DATA s3b2a2_re_inv<>+48(SB)/8, $0xbf81c73b39ae68c6
DATA s3b2a2_re_inv<>+56(SB)/8, $0xbf81c73b39ae68c6
GLOBL s3b2a2_re_inv<>(SB), RODATA|NOPTR, $64

DATA s3b2a3_im<>+0(SB)/8, $0xbfe6a09e667f3bcd
DATA s3b2a3_im<>+8(SB)/8, $0xbfe6a09e667f3bcd
DATA s3b2a3_im<>+16(SB)/8, $0xbfde2b5d3806f63e
DATA s3b2a3_im<>+24(SB)/8, $0xbfde2b5d3806f63e
DATA s3b2a3_im<>+32(SB)/8, $0xbfc8f8b83c69a616
DATA s3b2a3_im<>+40(SB)/8, $0xbfc8f8b83c69a616
DATA s3b2a3_im<>+48(SB)/8, $0x3fb917a6bc29b42b
DATA s3b2a3_im<>+56(SB)/8, $0x3fb917a6bc29b42b
GLOBL s3b2a3_im<>(SB), RODATA|NOPTR, $64

DATA s3b2a3_im_inv<>+0(SB)/8, $0xbf86a09e667f3bcd
DATA s3b2a3_im_inv<>+8(SB)/8, $0xbf86a09e667f3bcd
DATA s3b2a3_im_inv<>+16(SB)/8, $0xbf7e2b5d3806f63e
DATA s3b2a3_im_inv<>+24(SB)/8, $0xbf7e2b5d3806f63e
DATA s3b2a3_im_inv<>+32(SB)/8, $0xbf68f8b83c69a616
DATA s3b2a3_im_inv<>+40(SB)/8, $0xbf68f8b83c69a616
DATA s3b2a3_im_inv<>+48(SB)/8, $0x3f5917a6bc29b42b
DATA s3b2a3_im_inv<>+56(SB)/8, $0x3f5917a6bc29b42b
GLOBL s3b2a3_im_inv<>(SB), RODATA|NOPTR, $64

DATA s3b2a3_re<>+0(SB)/8, $0xbfe6a09e667f3bcc
DATA s3b2a3_re<>+8(SB)/8, $0xbfe6a09e667f3bcc
DATA s3b2a3_re<>+16(SB)/8, $0xbfec38b2f180bdb0
DATA s3b2a3_re<>+24(SB)/8, $0xbfec38b2f180bdb0
DATA s3b2a3_re<>+32(SB)/8, $0xbfef6297cff75caf
DATA s3b2a3_re<>+40(SB)/8, $0xbfef6297cff75caf
DATA s3b2a3_re<>+48(SB)/8, $0xbfefd88da3d12525
DATA s3b2a3_re<>+56(SB)/8, $0xbfefd88da3d12525
GLOBL s3b2a3_re<>(SB), RODATA|NOPTR, $64

DATA s3b2a3_re_inv<>+0(SB)/8, $0xbf86a09e667f3bcc
DATA s3b2a3_re_inv<>+8(SB)/8, $0xbf86a09e667f3bcc
DATA s3b2a3_re_inv<>+16(SB)/8, $0xbf8c38b2f180bdb0
DATA s3b2a3_re_inv<>+24(SB)/8, $0xbf8c38b2f180bdb0
DATA s3b2a3_re_inv<>+32(SB)/8, $0xbf8f6297cff75caf
DATA s3b2a3_re_inv<>+40(SB)/8, $0xbf8f6297cff75caf
DATA s3b2a3_re_inv<>+48(SB)/8, $0xbf8fd88da3d12525
DATA s3b2a3_re_inv<>+56(SB)/8, $0xbf8fd88da3d12525
GLOBL s3b2a3_re_inv<>(SB), RODATA|NOPTR, $64

DATA s3b3a1_im<>+0(SB)/8, $0xbfed906bcf328d46
DATA s3b3a1_im<>+8(SB)/8, $0xbfed906bcf328d46
DATA s3b3a1_im<>+16(SB)/8, $0xbfee9f4156c62ddb
DATA s3b3a1_im<>+24(SB)/8, $0xbfee9f4156c62ddb
DATA s3b3a1_im<>+32(SB)/8, $0xbfef6297cff75cb0
DATA s3b3a1_im<>+40(SB)/8, $0xbfef6297cff75cb0
DATA s3b3a1_im<>+48(SB)/8, $0xbfefd88da3d12525
DATA s3b3a1_im<>+56(SB)/8, $0xbfefd88da3d12525
GLOBL s3b3a1_im<>(SB), RODATA|NOPTR, $64

DATA s3b3a1_im_inv<>+0(SB)/8, $0xbf8d906bcf328d46
DATA s3b3a1_im_inv<>+8(SB)/8, $0xbf8d906bcf328d46
DATA s3b3a1_im_inv<>+16(SB)/8, $0xbf8e9f4156c62ddb
DATA s3b3a1_im_inv<>+24(SB)/8, $0xbf8e9f4156c62ddb
DATA s3b3a1_im_inv<>+32(SB)/8, $0xbf8f6297cff75cb0
DATA s3b3a1_im_inv<>+40(SB)/8, $0xbf8f6297cff75cb0
DATA s3b3a1_im_inv<>+48(SB)/8, $0xbf8fd88da3d12525
DATA s3b3a1_im_inv<>+56(SB)/8, $0xbf8fd88da3d12525
GLOBL s3b3a1_im_inv<>(SB), RODATA|NOPTR, $64

DATA s3b3a1_re<>+0(SB)/8, $0x3fd87de2a6aea964
DATA s3b3a1_re<>+8(SB)/8, $0x3fd87de2a6aea964
DATA s3b3a1_re<>+16(SB)/8, $0x3fd294062ed59f04
DATA s3b3a1_re<>+24(SB)/8, $0x3fd294062ed59f04
DATA s3b3a1_re<>+32(SB)/8, $0x3fc8f8b83c69a60c
DATA s3b3a1_re<>+40(SB)/8, $0x3fc8f8b83c69a60c
DATA s3b3a1_re<>+48(SB)/8, $0x3fb917a6bc29b438
DATA s3b3a1_re<>+56(SB)/8, $0x3fb917a6bc29b438
GLOBL s3b3a1_re<>(SB), RODATA|NOPTR, $64

DATA s3b3a1_re_inv<>+0(SB)/8, $0x3f787de2a6aea964
DATA s3b3a1_re_inv<>+8(SB)/8, $0x3f787de2a6aea964
DATA s3b3a1_re_inv<>+16(SB)/8, $0x3f7294062ed59f04
DATA s3b3a1_re_inv<>+24(SB)/8, $0x3f7294062ed59f04
DATA s3b3a1_re_inv<>+32(SB)/8, $0x3f68f8b83c69a60c
DATA s3b3a1_re_inv<>+40(SB)/8, $0x3f68f8b83c69a60c
DATA s3b3a1_re_inv<>+48(SB)/8, $0x3f5917a6bc29b438
DATA s3b3a1_re_inv<>+56(SB)/8, $0x3f5917a6bc29b438
GLOBL s3b3a1_re_inv<>(SB), RODATA|NOPTR, $64

DATA s3b3a2_im<>+0(SB)/8, $0xbfe6a09e667f3bcd
DATA s3b3a2_im<>+8(SB)/8, $0xbfe6a09e667f3bcd
DATA s3b3a2_im<>+16(SB)/8, $0xbfe1c73b39ae68c8
DATA s3b3a2_im<>+24(SB)/8, $0xbfe1c73b39ae68c8
DATA s3b3a2_im<>+32(SB)/8, $0xbfd87de2a6aea964
DATA s3b3a2_im<>+40(SB)/8, $0xbfd87de2a6aea964
DATA s3b3a2_im<>+48(SB)/8, $0xbfc8f8b83c69a616
DATA s3b3a2_im<>+56(SB)/8, $0xbfc8f8b83c69a616
GLOBL s3b3a2_im<>(SB), RODATA|NOPTR, $64

DATA s3b3a2_im_inv<>+0(SB)/8, $0xbf86a09e667f3bcd
DATA s3b3a2_im_inv<>+8(SB)/8, $0xbf86a09e667f3bcd
DATA s3b3a2_im_inv<>+16(SB)/8, $0xbf81c73b39ae68c8
DATA s3b3a2_im_inv<>+24(SB)/8, $0xbf81c73b39ae68c8
DATA s3b3a2_im_inv<>+32(SB)/8, $0xbf787de2a6aea964
DATA s3b3a2_im_inv<>+40(SB)/8, $0xbf787de2a6aea964
DATA s3b3a2_im_inv<>+48(SB)/8, $0xbf68f8b83c69a616
DATA s3b3a2_im_inv<>+56(SB)/8, $0xbf68f8b83c69a616
GLOBL s3b3a2_im_inv<>(SB), RODATA|NOPTR, $64

DATA s3b3a2_re<>+0(SB)/8, $0xbfe6a09e667f3bcc
DATA s3b3a2_re<>+8(SB)/8, $0xbfe6a09e667f3bcc
DATA s3b3a2_re<>+16(SB)/8, $0xbfea9b66290ea1a4
DATA s3b3a2_re<>+24(SB)/8, $0xbfea9b66290ea1a4
DATA s3b3a2_re<>+32(SB)/8, $0xbfed906bcf328d46
DATA s3b3a2_re<>+40(SB)/8, $0xbfed906bcf328d46
DATA s3b3a2_re<>+48(SB)/8, $0xbfef6297cff75caf
DATA s3b3a2_re<>+56(SB)/8, $0xbfef6297cff75caf
GLOBL s3b3a2_re<>(SB), RODATA|NOPTR, $64

DATA s3b3a2_re_inv<>+0(SB)/8, $0xbf86a09e667f3bcc
DATA s3b3a2_re_inv<>+8(SB)/8, $0xbf86a09e667f3bcc
DATA s3b3a2_re_inv<>+16(SB)/8, $0xbf8a9b66290ea1a4
DATA s3b3a2_re_inv<>+24(SB)/8, $0xbf8a9b66290ea1a4
DATA s3b3a2_re_inv<>+32(SB)/8, $0xbf8d906bcf328d46
DATA s3b3a2_re_inv<>+40(SB)/8, $0xbf8d906bcf328d46
DATA s3b3a2_re_inv<>+48(SB)/8, $0xbf8f6297cff75caf
DATA s3b3a2_re_inv<>+56(SB)/8, $0xbf8f6297cff75caf
GLOBL s3b3a2_re_inv<>(SB), RODATA|NOPTR, $64

DATA s3b3a3_im<>+0(SB)/8, $0x3fd87de2a6aea961
DATA s3b3a3_im<>+8(SB)/8, $0x3fd87de2a6aea961
DATA s3b3a3_im<>+16(SB)/8, $0x3fe44cf325091dd4
DATA s3b3a3_im<>+24(SB)/8, $0x3fe44cf325091dd4
DATA s3b3a3_im<>+32(SB)/8, $0x3fea9b66290ea1a4
DATA s3b3a3_im<>+40(SB)/8, $0x3fea9b66290ea1a4
DATA s3b3a3_im<>+48(SB)/8, $0x3fee9f4156c62dda
DATA s3b3a3_im<>+56(SB)/8, $0x3fee9f4156c62dda
GLOBL s3b3a3_im<>(SB), RODATA|NOPTR, $64

DATA s3b3a3_im_inv<>+0(SB)/8, $0x3f787de2a6aea961
DATA s3b3a3_im_inv<>+8(SB)/8, $0x3f787de2a6aea961
DATA s3b3a3_im_inv<>+16(SB)/8, $0x3f844cf325091dd4
DATA s3b3a3_im_inv<>+24(SB)/8, $0x3f844cf325091dd4
DATA s3b3a3_im_inv<>+32(SB)/8, $0x3f8a9b66290ea1a4
DATA s3b3a3_im_inv<>+40(SB)/8, $0x3f8a9b66290ea1a4
DATA s3b3a3_im_inv<>+48(SB)/8, $0x3f8e9f4156c62dda
DATA s3b3a3_im_inv<>+56(SB)/8, $0x3f8e9f4156c62dda
GLOBL s3b3a3_im_inv<>(SB), RODATA|NOPTR, $64

DATA s3b3a3_re<>+0(SB)/8, $0xbfed906bcf328d47
DATA s3b3a3_re<>+8(SB)/8, $0xbfed906bcf328d47
DATA s3b3a3_re<>+16(SB)/8, $0xbfe8bc806b151742
DATA s3b3a3_re<>+24(SB)/8, $0xbfe8bc806b151742
DATA s3b3a3_re<>+32(SB)/8, $0xbfe1c73b39ae68c8
DATA s3b3a3_re<>+40(SB)/8, $0xbfe1c73b39ae68c8
DATA s3b3a3_re<>+48(SB)/8, $0xbfd294062ed59f06
DATA s3b3a3_re<>+56(SB)/8, $0xbfd294062ed59f06
GLOBL s3b3a3_re<>(SB), RODATA|NOPTR, $64

DATA s3b3a3_re_inv<>+0(SB)/8, $0xbf8d906bcf328d47
DATA s3b3a3_re_inv<>+8(SB)/8, $0xbf8d906bcf328d47
DATA s3b3a3_re_inv<>+16(SB)/8, $0xbf88bc806b151742
DATA s3b3a3_re_inv<>+24(SB)/8, $0xbf88bc806b151742
DATA s3b3a3_re_inv<>+32(SB)/8, $0xbf81c73b39ae68c8
DATA s3b3a3_re_inv<>+40(SB)/8, $0xbf81c73b39ae68c8
DATA s3b3a3_re_inv<>+48(SB)/8, $0xbf7294062ed59f06
DATA s3b3a3_re_inv<>+56(SB)/8, $0xbf7294062ed59f06
GLOBL s3b3a3_re_inv<>(SB), RODATA|NOPTR, $64

