//go:build amd64 && !purego

// ===========================================================================
// AVX-512 Size-128 radix-8-then-2 FFT Kernels for AMD64 (complex64)
// ===========================================================================
//
// GENERATED by a throwaway generator that also interprets the emitted
// instruction stream in software and checks it against a naive DFT; see the
// c64s128 handoff report. Edit the generator, not this file, if the structure
// has to change.
//
// STRUCTURE
// ---------
// Radix-2 DIT, vectorised so that one ZMM holds 8 consecutive complex64 of the
// bit-reversed working array (a "group"). n=128 needs 16 ZMM for data.
//
//   1. Bit reversal. work[8g+k] = src[rev3(k)*(n/8) + revM(g)] is exactly an
//      8 x (n/8) transpose, so it is done as 2 in-register 8x8 transposes
//      (VUNPCKLPD/VUNPCKHPD + VSHUFF64X2, 24 instructions each). The two index
//      reversals are free: rev3 permutes the load addresses, revM permutes the
//      register naming. No bit-reversal table is used or needed.
//   2. DIT stages half = 1, 2, 4 act only inside a group, so they are fused
//      into one in-register 8-point DFT: 15 instructions per ZMM, using
//      VPERMILPS $0x4E / VSHUFF32X4 $0xB1 / VSHUFF32X4 $0x4E to bring the
//      butterfly partners together and merge-masked VSUBPS (K1..K3) to write
//      the "a-w*b" half without a second permute.
//   3. DIT stages half = 8 .. 64 act between whole ZMM registers: elementwise,
//      no shuffles, one twiddle vector per (stage, block).
//   4. Stage half=h multiplies butterfly j by W_128^(j*64/h) = W_(2h)^j, which
//      does not depend on the enclosing transform length. All those vectors are
//      therefore exact float32 rodata (avx512_f32_radix8_twiddle_const.s): no
//      strided twiddle gather, and no rounding drift from deriving them. Only
//      the last stage reads the caller's twiddle table, contiguously. The
//      constants are forward twiddles; the butterflies conjugate them for the
//      inverse (VFMSUBADD231PS).
//
// COMPLEX MULTIPLY (per ZMM, 8 complex64) - as in avx512_f32_generic.s:
//   VMOVSLDUP w -> w.re duplicated, VMOVSHDUP w -> w.im duplicated,
//   VSHUFPS $0xB1 b -> swapped, VMULPS, then VFMADDSUB231PS (forward) or
//   VFMSUBADD231PS (inverse, = multiply by conj(w)).
//
// Plan 9 operand order is src, dst: VSUBPS b, a, dst computes dst = a - b.
//
// n=128 is fully register resident: 16 ZMM of data, loaded once and
// stored once. The scratch slice is validated but never touched, so the
// in-place case (dst == src) needs no special handling.
// ===========================================================================

#include "textflag.h"

TEXT ·ForwardAVX512Size128Radix8Then2Complex64Asm(SB), NOSPLIT, $0-97
	MOVQ src+24(FP), R9      // R9  = src pointer
	MOVQ src_len+32(FP), AX
	CMPQ AX, $128
	JNE  fwd128_false            // only length 128 is handled
	MOVQ dst+0(FP), R8       // R8  = dst pointer
	MOVQ dst_len+8(FP), AX
	CMPQ AX, $128
	JL   fwd128_false            // dst too short
	MOVQ twiddle+48(FP), R10 // R10 = twiddle pointer
	MOVQ twiddle_len+56(FP), AX
	CMPQ AX, $128
	JL   fwd128_false            // twiddle too short
	MOVQ scratch+72(FP), R11 // R11 = scratch pointer
	MOVQ scratch_len+80(FP), AX
	CMPQ AX, $128
	JL   fwd128_false            // scratch too short
	MOVW $0xcccc, AX
	KMOVW AX, K1           // K1 = odd complex of each adjacent pair
	MOVW $0xf0f0, AX
	KMOVW AX, K2           // K2 = complex 2,3 of each group of 4
	MOVW $0xff00, AX
	KMOVW AX, K3           // K3 = complex 4..7

	VMOVUPS (R9), Z16                       // bitrev cols 0..7: src[0..] (row 0, cols 0..7)
	VMOVUPS 512(R9), Z17                    // bitrev cols 0..7: src[64..] (row 4, cols 0..7)
	VMOVUPS 256(R9), Z18                    // bitrev cols 0..7: src[32..] (row 2, cols 0..7)
	VMOVUPS 768(R9), Z19                    // bitrev cols 0..7: src[96..] (row 6, cols 0..7)
	VMOVUPS 128(R9), Z20                    // bitrev cols 0..7: src[16..] (row 1, cols 0..7)
	VMOVUPS 640(R9), Z21                    // bitrev cols 0..7: src[80..] (row 5, cols 0..7)
	VMOVUPS 384(R9), Z22                    // bitrev cols 0..7: src[48..] (row 3, cols 0..7)
	VMOVUPS 896(R9), Z23                    // bitrev cols 0..7: src[112..] (row 7, cols 0..7)
	VUNPCKLPD Z17, Z16, Z0                  // bitrev cols 0..7 L1
	VUNPCKHPD Z17, Z16, Z1                  // bitrev cols 0..7 L1
	VUNPCKLPD Z19, Z18, Z2                  // bitrev cols 0..7 L1
	VUNPCKHPD Z19, Z18, Z3                  // bitrev cols 0..7 L1
	VUNPCKLPD Z21, Z20, Z4                  // bitrev cols 0..7 L1
	VUNPCKHPD Z21, Z20, Z5                  // bitrev cols 0..7 L1
	VUNPCKLPD Z23, Z22, Z6                  // bitrev cols 0..7 L1
	VUNPCKHPD Z23, Z22, Z7                  // bitrev cols 0..7 L1
	VSHUFF64X2 $0x88, Z2, Z0, Z16           // bitrev cols 0..7 L2
	VSHUFF64X2 $0xdd, Z2, Z0, Z18           // bitrev cols 0..7 L2
	VSHUFF64X2 $0x88, Z3, Z1, Z17           // bitrev cols 0..7 L2
	VSHUFF64X2 $0xdd, Z3, Z1, Z19           // bitrev cols 0..7 L2
	VSHUFF64X2 $0x88, Z6, Z4, Z20           // bitrev cols 0..7 L2
	VSHUFF64X2 $0xdd, Z6, Z4, Z22           // bitrev cols 0..7 L2
	VSHUFF64X2 $0x88, Z7, Z5, Z21           // bitrev cols 0..7 L2
	VSHUFF64X2 $0xdd, Z7, Z5, Z23           // bitrev cols 0..7 L2
	VSHUFF64X2 $0x88, Z20, Z16, Z0          // bitrev cols 0..7 L3
	VSHUFF64X2 $0xdd, Z20, Z16, Z4          // bitrev cols 0..7 L3
	VSHUFF64X2 $0x88, Z21, Z17, Z1          // bitrev cols 0..7 L3
	VSHUFF64X2 $0xdd, Z21, Z17, Z5          // bitrev cols 0..7 L3
	VSHUFF64X2 $0x88, Z22, Z18, Z2          // bitrev cols 0..7 L3
	VSHUFF64X2 $0xdd, Z22, Z18, Z6          // bitrev cols 0..7 L3
	VSHUFF64X2 $0x88, Z23, Z19, Z3          // bitrev cols 0..7 L3
	VSHUFF64X2 $0xdd, Z23, Z19, Z7          // bitrev cols 0..7 L3
	VMOVUPS 64(R9), Z16                     // bitrev cols 8..15: src[8..] (row 0, cols 8..15)
	VMOVUPS 576(R9), Z17                    // bitrev cols 8..15: src[72..] (row 4, cols 8..15)
	VMOVUPS 320(R9), Z18                    // bitrev cols 8..15: src[40..] (row 2, cols 8..15)
	VMOVUPS 832(R9), Z19                    // bitrev cols 8..15: src[104..] (row 6, cols 8..15)
	VMOVUPS 192(R9), Z20                    // bitrev cols 8..15: src[24..] (row 1, cols 8..15)
	VMOVUPS 704(R9), Z21                    // bitrev cols 8..15: src[88..] (row 5, cols 8..15)
	VMOVUPS 448(R9), Z22                    // bitrev cols 8..15: src[56..] (row 3, cols 8..15)
	VMOVUPS 960(R9), Z23                    // bitrev cols 8..15: src[120..] (row 7, cols 8..15)
	VUNPCKLPD Z17, Z16, Z24                 // bitrev cols 8..15 L1
	VUNPCKHPD Z17, Z16, Z25                 // bitrev cols 8..15 L1
	VUNPCKLPD Z19, Z18, Z26                 // bitrev cols 8..15 L1
	VUNPCKHPD Z19, Z18, Z27                 // bitrev cols 8..15 L1
	VUNPCKLPD Z21, Z20, Z28                 // bitrev cols 8..15 L1
	VUNPCKHPD Z21, Z20, Z29                 // bitrev cols 8..15 L1
	VUNPCKLPD Z23, Z22, Z30                 // bitrev cols 8..15 L1
	VUNPCKHPD Z23, Z22, Z31                 // bitrev cols 8..15 L1
	VSHUFF64X2 $0x88, Z26, Z24, Z16         // bitrev cols 8..15 L2
	VSHUFF64X2 $0xdd, Z26, Z24, Z18         // bitrev cols 8..15 L2
	VSHUFF64X2 $0x88, Z27, Z25, Z17         // bitrev cols 8..15 L2
	VSHUFF64X2 $0xdd, Z27, Z25, Z19         // bitrev cols 8..15 L2
	VSHUFF64X2 $0x88, Z30, Z28, Z20         // bitrev cols 8..15 L2
	VSHUFF64X2 $0xdd, Z30, Z28, Z22         // bitrev cols 8..15 L2
	VSHUFF64X2 $0x88, Z31, Z29, Z21         // bitrev cols 8..15 L2
	VSHUFF64X2 $0xdd, Z31, Z29, Z23         // bitrev cols 8..15 L2
	VSHUFF64X2 $0x88, Z20, Z16, Z8          // bitrev cols 8..15 L3
	VSHUFF64X2 $0xdd, Z20, Z16, Z12         // bitrev cols 8..15 L3
	VSHUFF64X2 $0x88, Z21, Z17, Z9          // bitrev cols 8..15 L3
	VSHUFF64X2 $0xdd, Z21, Z17, Z13         // bitrev cols 8..15 L3
	VSHUFF64X2 $0x88, Z22, Z18, Z10         // bitrev cols 8..15 L3
	VSHUFF64X2 $0xdd, Z22, Z18, Z14         // bitrev cols 8..15 L3
	VSHUFF64X2 $0x88, Z23, Z19, Z11         // bitrev cols 8..15 L3
	VSHUFF64X2 $0xdd, Z23, Z19, Z15         // bitrev cols 8..15 L3
	VMOVUPS ·avx512f32Radix8W4(SB), Z16    // leaf half=2 w = [1,1,1,-i]
	VMOVSLDUP Z16, Z24                      // leaf half=2 w = [1,1,1,-i]: w.re -> both halves
	VMOVSHDUP Z16, Z25                      // leaf half=2 w = [1,1,1,-i]: w.im -> both halves
	VMOVUPS ·avx512f32Radix8W8(SB), Z16    // leaf half=4 w = [1,1,1,1,W8^0..3]
	VMOVSLDUP Z16, Z26                      // leaf half=4 w = [1,1,1,1,W8^0..3]: w.re -> both halves
	VMOVSHDUP Z16, Z27                      // leaf half=4 w = [1,1,1,1,W8^0..3]: w.im -> both halves
	VPERMILPS $0x4e, Z0, Z16                // leaf A: partner = adjacent complex
	VADDPS Z16, Z0, Z17                     // leaf A: a+p
	VSUBPS Z0, Z16, K1, Z17                 // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z1, Z18                // leaf A: partner = adjacent complex
	VADDPS Z18, Z1, Z19                     // leaf A: a+p
	VSUBPS Z1, Z18, K1, Z19                 // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z2, Z20                // leaf A: partner = adjacent complex
	VADDPS Z20, Z2, Z21                     // leaf A: a+p
	VSUBPS Z2, Z20, K1, Z21                 // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z3, Z22                // leaf A: partner = adjacent complex
	VADDPS Z22, Z3, Z23                     // leaf A: a+p
	VSUBPS Z3, Z22, K1, Z23                 // leaf A: odd complex := p-a
	VSHUFPS $0xb1, Z17, Z17, Z16            // leaf B: swap re/im of b
	VMULPS Z25, Z16, Z16                    // leaf B: w.im*swap(b)
	VFMADDSUB231PS Z24, Z17, Z16            // leaf B: w*b
	VSHUFF32X4 $0xb1, Z16, Z16, Z17         // leaf B: partner = 128-bit lane swap
	VADDPS Z17, Z16, Z0                     // leaf B: a+w*b
	VSUBPS Z16, Z17, K2, Z0                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z19, Z19, Z18            // leaf B: swap re/im of b
	VMULPS Z25, Z18, Z18                    // leaf B: w.im*swap(b)
	VFMADDSUB231PS Z24, Z19, Z18            // leaf B: w*b
	VSHUFF32X4 $0xb1, Z18, Z18, Z19         // leaf B: partner = 128-bit lane swap
	VADDPS Z19, Z18, Z1                     // leaf B: a+w*b
	VSUBPS Z18, Z19, K2, Z1                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z21, Z21, Z20            // leaf B: swap re/im of b
	VMULPS Z25, Z20, Z20                    // leaf B: w.im*swap(b)
	VFMADDSUB231PS Z24, Z21, Z20            // leaf B: w*b
	VSHUFF32X4 $0xb1, Z20, Z20, Z21         // leaf B: partner = 128-bit lane swap
	VADDPS Z21, Z20, Z2                     // leaf B: a+w*b
	VSUBPS Z20, Z21, K2, Z2                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z23, Z23, Z22            // leaf B: swap re/im of b
	VMULPS Z25, Z22, Z22                    // leaf B: w.im*swap(b)
	VFMADDSUB231PS Z24, Z23, Z22            // leaf B: w*b
	VSHUFF32X4 $0xb1, Z22, Z22, Z23         // leaf B: partner = 128-bit lane swap
	VADDPS Z23, Z22, Z3                     // leaf B: a+w*b
	VSUBPS Z22, Z23, K2, Z3                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z0, Z0, Z16              // leaf C: swap re/im of b
	VMULPS Z27, Z16, Z16                    // leaf C: w.im*swap(b)
	VFMADDSUB231PS Z26, Z0, Z16             // leaf C: w*b
	VSHUFF32X4 $0x4e, Z16, Z16, Z17         // leaf C: partner = 256-bit half swap
	VADDPS Z17, Z16, Z0                     // leaf C: a+w*b
	VSUBPS Z16, Z17, K3, Z0                 // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z1, Z1, Z18              // leaf C: swap re/im of b
	VMULPS Z27, Z18, Z18                    // leaf C: w.im*swap(b)
	VFMADDSUB231PS Z26, Z1, Z18             // leaf C: w*b
	VSHUFF32X4 $0x4e, Z18, Z18, Z19         // leaf C: partner = 256-bit half swap
	VADDPS Z19, Z18, Z1                     // leaf C: a+w*b
	VSUBPS Z18, Z19, K3, Z1                 // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z2, Z2, Z20              // leaf C: swap re/im of b
	VMULPS Z27, Z20, Z20                    // leaf C: w.im*swap(b)
	VFMADDSUB231PS Z26, Z2, Z20             // leaf C: w*b
	VSHUFF32X4 $0x4e, Z20, Z20, Z21         // leaf C: partner = 256-bit half swap
	VADDPS Z21, Z20, Z2                     // leaf C: a+w*b
	VSUBPS Z20, Z21, K3, Z2                 // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z3, Z3, Z22              // leaf C: swap re/im of b
	VMULPS Z27, Z22, Z22                    // leaf C: w.im*swap(b)
	VFMADDSUB231PS Z26, Z3, Z22             // leaf C: w*b
	VSHUFF32X4 $0x4e, Z22, Z22, Z23         // leaf C: partner = 256-bit half swap
	VADDPS Z23, Z22, Z3                     // leaf C: a+w*b
	VSUBPS Z22, Z23, K3, Z3                 // leaf C: complex 4..7 := a-w*b
	VPERMILPS $0x4e, Z4, Z16                // leaf A: partner = adjacent complex
	VADDPS Z16, Z4, Z17                     // leaf A: a+p
	VSUBPS Z4, Z16, K1, Z17                 // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z5, Z18                // leaf A: partner = adjacent complex
	VADDPS Z18, Z5, Z19                     // leaf A: a+p
	VSUBPS Z5, Z18, K1, Z19                 // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z6, Z20                // leaf A: partner = adjacent complex
	VADDPS Z20, Z6, Z21                     // leaf A: a+p
	VSUBPS Z6, Z20, K1, Z21                 // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z7, Z22                // leaf A: partner = adjacent complex
	VADDPS Z22, Z7, Z23                     // leaf A: a+p
	VSUBPS Z7, Z22, K1, Z23                 // leaf A: odd complex := p-a
	VSHUFPS $0xb1, Z17, Z17, Z16            // leaf B: swap re/im of b
	VMULPS Z25, Z16, Z16                    // leaf B: w.im*swap(b)
	VFMADDSUB231PS Z24, Z17, Z16            // leaf B: w*b
	VSHUFF32X4 $0xb1, Z16, Z16, Z17         // leaf B: partner = 128-bit lane swap
	VADDPS Z17, Z16, Z4                     // leaf B: a+w*b
	VSUBPS Z16, Z17, K2, Z4                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z19, Z19, Z18            // leaf B: swap re/im of b
	VMULPS Z25, Z18, Z18                    // leaf B: w.im*swap(b)
	VFMADDSUB231PS Z24, Z19, Z18            // leaf B: w*b
	VSHUFF32X4 $0xb1, Z18, Z18, Z19         // leaf B: partner = 128-bit lane swap
	VADDPS Z19, Z18, Z5                     // leaf B: a+w*b
	VSUBPS Z18, Z19, K2, Z5                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z21, Z21, Z20            // leaf B: swap re/im of b
	VMULPS Z25, Z20, Z20                    // leaf B: w.im*swap(b)
	VFMADDSUB231PS Z24, Z21, Z20            // leaf B: w*b
	VSHUFF32X4 $0xb1, Z20, Z20, Z21         // leaf B: partner = 128-bit lane swap
	VADDPS Z21, Z20, Z6                     // leaf B: a+w*b
	VSUBPS Z20, Z21, K2, Z6                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z23, Z23, Z22            // leaf B: swap re/im of b
	VMULPS Z25, Z22, Z22                    // leaf B: w.im*swap(b)
	VFMADDSUB231PS Z24, Z23, Z22            // leaf B: w*b
	VSHUFF32X4 $0xb1, Z22, Z22, Z23         // leaf B: partner = 128-bit lane swap
	VADDPS Z23, Z22, Z7                     // leaf B: a+w*b
	VSUBPS Z22, Z23, K2, Z7                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z4, Z4, Z16              // leaf C: swap re/im of b
	VMULPS Z27, Z16, Z16                    // leaf C: w.im*swap(b)
	VFMADDSUB231PS Z26, Z4, Z16             // leaf C: w*b
	VSHUFF32X4 $0x4e, Z16, Z16, Z17         // leaf C: partner = 256-bit half swap
	VADDPS Z17, Z16, Z4                     // leaf C: a+w*b
	VSUBPS Z16, Z17, K3, Z4                 // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z5, Z5, Z18              // leaf C: swap re/im of b
	VMULPS Z27, Z18, Z18                    // leaf C: w.im*swap(b)
	VFMADDSUB231PS Z26, Z5, Z18             // leaf C: w*b
	VSHUFF32X4 $0x4e, Z18, Z18, Z19         // leaf C: partner = 256-bit half swap
	VADDPS Z19, Z18, Z5                     // leaf C: a+w*b
	VSUBPS Z18, Z19, K3, Z5                 // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z6, Z6, Z20              // leaf C: swap re/im of b
	VMULPS Z27, Z20, Z20                    // leaf C: w.im*swap(b)
	VFMADDSUB231PS Z26, Z6, Z20             // leaf C: w*b
	VSHUFF32X4 $0x4e, Z20, Z20, Z21         // leaf C: partner = 256-bit half swap
	VADDPS Z21, Z20, Z6                     // leaf C: a+w*b
	VSUBPS Z20, Z21, K3, Z6                 // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z7, Z7, Z22              // leaf C: swap re/im of b
	VMULPS Z27, Z22, Z22                    // leaf C: w.im*swap(b)
	VFMADDSUB231PS Z26, Z7, Z22             // leaf C: w*b
	VSHUFF32X4 $0x4e, Z22, Z22, Z23         // leaf C: partner = 256-bit half swap
	VADDPS Z23, Z22, Z7                     // leaf C: a+w*b
	VSUBPS Z22, Z23, K3, Z7                 // leaf C: complex 4..7 := a-w*b
	VPERMILPS $0x4e, Z8, Z16                // leaf A: partner = adjacent complex
	VADDPS Z16, Z8, Z17                     // leaf A: a+p
	VSUBPS Z8, Z16, K1, Z17                 // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z9, Z18                // leaf A: partner = adjacent complex
	VADDPS Z18, Z9, Z19                     // leaf A: a+p
	VSUBPS Z9, Z18, K1, Z19                 // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z10, Z20               // leaf A: partner = adjacent complex
	VADDPS Z20, Z10, Z21                    // leaf A: a+p
	VSUBPS Z10, Z20, K1, Z21                // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z11, Z22               // leaf A: partner = adjacent complex
	VADDPS Z22, Z11, Z23                    // leaf A: a+p
	VSUBPS Z11, Z22, K1, Z23                // leaf A: odd complex := p-a
	VSHUFPS $0xb1, Z17, Z17, Z16            // leaf B: swap re/im of b
	VMULPS Z25, Z16, Z16                    // leaf B: w.im*swap(b)
	VFMADDSUB231PS Z24, Z17, Z16            // leaf B: w*b
	VSHUFF32X4 $0xb1, Z16, Z16, Z17         // leaf B: partner = 128-bit lane swap
	VADDPS Z17, Z16, Z8                     // leaf B: a+w*b
	VSUBPS Z16, Z17, K2, Z8                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z19, Z19, Z18            // leaf B: swap re/im of b
	VMULPS Z25, Z18, Z18                    // leaf B: w.im*swap(b)
	VFMADDSUB231PS Z24, Z19, Z18            // leaf B: w*b
	VSHUFF32X4 $0xb1, Z18, Z18, Z19         // leaf B: partner = 128-bit lane swap
	VADDPS Z19, Z18, Z9                     // leaf B: a+w*b
	VSUBPS Z18, Z19, K2, Z9                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z21, Z21, Z20            // leaf B: swap re/im of b
	VMULPS Z25, Z20, Z20                    // leaf B: w.im*swap(b)
	VFMADDSUB231PS Z24, Z21, Z20            // leaf B: w*b
	VSHUFF32X4 $0xb1, Z20, Z20, Z21         // leaf B: partner = 128-bit lane swap
	VADDPS Z21, Z20, Z10                    // leaf B: a+w*b
	VSUBPS Z20, Z21, K2, Z10                // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z23, Z23, Z22            // leaf B: swap re/im of b
	VMULPS Z25, Z22, Z22                    // leaf B: w.im*swap(b)
	VFMADDSUB231PS Z24, Z23, Z22            // leaf B: w*b
	VSHUFF32X4 $0xb1, Z22, Z22, Z23         // leaf B: partner = 128-bit lane swap
	VADDPS Z23, Z22, Z11                    // leaf B: a+w*b
	VSUBPS Z22, Z23, K2, Z11                // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z8, Z8, Z16              // leaf C: swap re/im of b
	VMULPS Z27, Z16, Z16                    // leaf C: w.im*swap(b)
	VFMADDSUB231PS Z26, Z8, Z16             // leaf C: w*b
	VSHUFF32X4 $0x4e, Z16, Z16, Z17         // leaf C: partner = 256-bit half swap
	VADDPS Z17, Z16, Z8                     // leaf C: a+w*b
	VSUBPS Z16, Z17, K3, Z8                 // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z9, Z9, Z18              // leaf C: swap re/im of b
	VMULPS Z27, Z18, Z18                    // leaf C: w.im*swap(b)
	VFMADDSUB231PS Z26, Z9, Z18             // leaf C: w*b
	VSHUFF32X4 $0x4e, Z18, Z18, Z19         // leaf C: partner = 256-bit half swap
	VADDPS Z19, Z18, Z9                     // leaf C: a+w*b
	VSUBPS Z18, Z19, K3, Z9                 // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z10, Z10, Z20            // leaf C: swap re/im of b
	VMULPS Z27, Z20, Z20                    // leaf C: w.im*swap(b)
	VFMADDSUB231PS Z26, Z10, Z20            // leaf C: w*b
	VSHUFF32X4 $0x4e, Z20, Z20, Z21         // leaf C: partner = 256-bit half swap
	VADDPS Z21, Z20, Z10                    // leaf C: a+w*b
	VSUBPS Z20, Z21, K3, Z10                // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z11, Z11, Z22            // leaf C: swap re/im of b
	VMULPS Z27, Z22, Z22                    // leaf C: w.im*swap(b)
	VFMADDSUB231PS Z26, Z11, Z22            // leaf C: w*b
	VSHUFF32X4 $0x4e, Z22, Z22, Z23         // leaf C: partner = 256-bit half swap
	VADDPS Z23, Z22, Z11                    // leaf C: a+w*b
	VSUBPS Z22, Z23, K3, Z11                // leaf C: complex 4..7 := a-w*b
	VPERMILPS $0x4e, Z12, Z16               // leaf A: partner = adjacent complex
	VADDPS Z16, Z12, Z17                    // leaf A: a+p
	VSUBPS Z12, Z16, K1, Z17                // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z13, Z18               // leaf A: partner = adjacent complex
	VADDPS Z18, Z13, Z19                    // leaf A: a+p
	VSUBPS Z13, Z18, K1, Z19                // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z14, Z20               // leaf A: partner = adjacent complex
	VADDPS Z20, Z14, Z21                    // leaf A: a+p
	VSUBPS Z14, Z20, K1, Z21                // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z15, Z22               // leaf A: partner = adjacent complex
	VADDPS Z22, Z15, Z23                    // leaf A: a+p
	VSUBPS Z15, Z22, K1, Z23                // leaf A: odd complex := p-a
	VSHUFPS $0xb1, Z17, Z17, Z16            // leaf B: swap re/im of b
	VMULPS Z25, Z16, Z16                    // leaf B: w.im*swap(b)
	VFMADDSUB231PS Z24, Z17, Z16            // leaf B: w*b
	VSHUFF32X4 $0xb1, Z16, Z16, Z17         // leaf B: partner = 128-bit lane swap
	VADDPS Z17, Z16, Z12                    // leaf B: a+w*b
	VSUBPS Z16, Z17, K2, Z12                // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z19, Z19, Z18            // leaf B: swap re/im of b
	VMULPS Z25, Z18, Z18                    // leaf B: w.im*swap(b)
	VFMADDSUB231PS Z24, Z19, Z18            // leaf B: w*b
	VSHUFF32X4 $0xb1, Z18, Z18, Z19         // leaf B: partner = 128-bit lane swap
	VADDPS Z19, Z18, Z13                    // leaf B: a+w*b
	VSUBPS Z18, Z19, K2, Z13                // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z21, Z21, Z20            // leaf B: swap re/im of b
	VMULPS Z25, Z20, Z20                    // leaf B: w.im*swap(b)
	VFMADDSUB231PS Z24, Z21, Z20            // leaf B: w*b
	VSHUFF32X4 $0xb1, Z20, Z20, Z21         // leaf B: partner = 128-bit lane swap
	VADDPS Z21, Z20, Z14                    // leaf B: a+w*b
	VSUBPS Z20, Z21, K2, Z14                // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z23, Z23, Z22            // leaf B: swap re/im of b
	VMULPS Z25, Z22, Z22                    // leaf B: w.im*swap(b)
	VFMADDSUB231PS Z24, Z23, Z22            // leaf B: w*b
	VSHUFF32X4 $0xb1, Z22, Z22, Z23         // leaf B: partner = 128-bit lane swap
	VADDPS Z23, Z22, Z15                    // leaf B: a+w*b
	VSUBPS Z22, Z23, K2, Z15                // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z12, Z12, Z16            // leaf C: swap re/im of b
	VMULPS Z27, Z16, Z16                    // leaf C: w.im*swap(b)
	VFMADDSUB231PS Z26, Z12, Z16            // leaf C: w*b
	VSHUFF32X4 $0x4e, Z16, Z16, Z17         // leaf C: partner = 256-bit half swap
	VADDPS Z17, Z16, Z12                    // leaf C: a+w*b
	VSUBPS Z16, Z17, K3, Z12                // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z13, Z13, Z18            // leaf C: swap re/im of b
	VMULPS Z27, Z18, Z18                    // leaf C: w.im*swap(b)
	VFMADDSUB231PS Z26, Z13, Z18            // leaf C: w*b
	VSHUFF32X4 $0x4e, Z18, Z18, Z19         // leaf C: partner = 256-bit half swap
	VADDPS Z19, Z18, Z13                    // leaf C: a+w*b
	VSUBPS Z18, Z19, K3, Z13                // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z14, Z14, Z20            // leaf C: swap re/im of b
	VMULPS Z27, Z20, Z20                    // leaf C: w.im*swap(b)
	VFMADDSUB231PS Z26, Z14, Z20            // leaf C: w*b
	VSHUFF32X4 $0x4e, Z20, Z20, Z21         // leaf C: partner = 256-bit half swap
	VADDPS Z21, Z20, Z14                    // leaf C: a+w*b
	VSUBPS Z20, Z21, K3, Z14                // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z15, Z15, Z22            // leaf C: swap re/im of b
	VMULPS Z27, Z22, Z22                    // leaf C: w.im*swap(b)
	VFMADDSUB231PS Z26, Z15, Z22            // leaf C: w*b
	VSHUFF32X4 $0x4e, Z22, Z22, Z23         // leaf C: partner = 256-bit half swap
	VADDPS Z23, Z22, Z15                    // leaf C: a+w*b
	VSUBPS Z22, Z23, K3, Z15                // leaf C: complex 4..7 := a-w*b
	VMOVUPS ·avx512f32Radix8W16(SB), Z18   // stage half=8 w = [W16^u]
	VMOVSLDUP Z18, Z16                      // stage half=8 w = [W16^u]: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=8 w = [W16^u]: w.im -> both halves
	VSHUFPS $0xb1, Z8, Z8, Z19              // half=8 m=0: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=8 m=0: w.im*swap(b)
	VFMADDSUB231PS Z16, Z8, Z19             // half=8 m=0: w*b
	VSUBPS Z19, Z0, Z8                      // half=8 m=0: b = a - w*b
	VADDPS Z19, Z0, Z0                      // half=8 m=0: a = a + w*b
	VSHUFPS $0xb1, Z12, Z12, Z20            // half=8 m=1: swap re/im of b
	VMULPS Z17, Z20, Z20                    // half=8 m=1: w.im*swap(b)
	VFMADDSUB231PS Z16, Z12, Z20            // half=8 m=1: w*b
	VSUBPS Z20, Z4, Z12                     // half=8 m=1: b = a - w*b
	VADDPS Z20, Z4, Z4                      // half=8 m=1: a = a + w*b
	VSHUFPS $0xb1, Z10, Z10, Z21            // half=8 m=2: swap re/im of b
	VMULPS Z17, Z21, Z21                    // half=8 m=2: w.im*swap(b)
	VFMADDSUB231PS Z16, Z10, Z21            // half=8 m=2: w*b
	VSUBPS Z21, Z2, Z10                     // half=8 m=2: b = a - w*b
	VADDPS Z21, Z2, Z2                      // half=8 m=2: a = a + w*b
	VSHUFPS $0xb1, Z14, Z14, Z22            // half=8 m=3: swap re/im of b
	VMULPS Z17, Z22, Z22                    // half=8 m=3: w.im*swap(b)
	VFMADDSUB231PS Z16, Z14, Z22            // half=8 m=3: w*b
	VSUBPS Z22, Z6, Z14                     // half=8 m=3: b = a - w*b
	VADDPS Z22, Z6, Z6                      // half=8 m=3: a = a + w*b
	VSHUFPS $0xb1, Z9, Z9, Z19              // half=8 m=4: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=8 m=4: w.im*swap(b)
	VFMADDSUB231PS Z16, Z9, Z19             // half=8 m=4: w*b
	VSUBPS Z19, Z1, Z9                      // half=8 m=4: b = a - w*b
	VADDPS Z19, Z1, Z1                      // half=8 m=4: a = a + w*b
	VSHUFPS $0xb1, Z13, Z13, Z20            // half=8 m=5: swap re/im of b
	VMULPS Z17, Z20, Z20                    // half=8 m=5: w.im*swap(b)
	VFMADDSUB231PS Z16, Z13, Z20            // half=8 m=5: w*b
	VSUBPS Z20, Z5, Z13                     // half=8 m=5: b = a - w*b
	VADDPS Z20, Z5, Z5                      // half=8 m=5: a = a + w*b
	VSHUFPS $0xb1, Z11, Z11, Z21            // half=8 m=6: swap re/im of b
	VMULPS Z17, Z21, Z21                    // half=8 m=6: w.im*swap(b)
	VFMADDSUB231PS Z16, Z11, Z21            // half=8 m=6: w*b
	VSUBPS Z21, Z3, Z11                     // half=8 m=6: b = a - w*b
	VADDPS Z21, Z3, Z3                      // half=8 m=6: a = a + w*b
	VSHUFPS $0xb1, Z15, Z15, Z22            // half=8 m=7: swap re/im of b
	VMULPS Z17, Z22, Z22                    // half=8 m=7: w.im*swap(b)
	VFMADDSUB231PS Z16, Z15, Z22            // half=8 m=7: w*b
	VSUBPS Z22, Z7, Z15                     // half=8 m=7: b = a - w*b
	VADDPS Z22, Z7, Z7                      // half=8 m=7: a = a + w*b
	VMOVUPS ·avx512f32Radix8W32(SB), Z18   // stage half=16 w = [W32^u]
	VMOVSLDUP Z18, Z16                      // stage half=16 w = [W32^u]: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=16 w = [W32^u]: w.im -> both halves
	VMOVUPS ·avx512f32Radix8W32+64(SB), Z21 // stage half=16 w = [W32^(8+u)]
	VMOVSLDUP Z21, Z19                      // stage half=16 w = [W32^(8+u)]: w.re -> both halves
	VMOVSHDUP Z21, Z20                      // stage half=16 w = [W32^(8+u)]: w.im -> both halves
	VSHUFPS $0xb1, Z4, Z4, Z22              // half=16 m=0 j<8: swap re/im of b
	VMULPS Z17, Z22, Z22                    // half=16 m=0 j<8: w.im*swap(b)
	VFMADDSUB231PS Z16, Z4, Z22             // half=16 m=0 j<8: w*b
	VSUBPS Z22, Z0, Z4                      // half=16 m=0 j<8: b = a - w*b
	VADDPS Z22, Z0, Z0                      // half=16 m=0 j<8: a = a + w*b
	VSHUFPS $0xb1, Z12, Z12, Z23            // half=16 m=0 j>=8: swap re/im of b
	VMULPS Z20, Z23, Z23                    // half=16 m=0 j>=8: w.im*swap(b)
	VFMADDSUB231PS Z19, Z12, Z23            // half=16 m=0 j>=8: w*b
	VSUBPS Z23, Z8, Z12                     // half=16 m=0 j>=8: b = a - w*b
	VADDPS Z23, Z8, Z8                      // half=16 m=0 j>=8: a = a + w*b
	VSHUFPS $0xb1, Z6, Z6, Z22              // half=16 m=1 j<8: swap re/im of b
	VMULPS Z17, Z22, Z22                    // half=16 m=1 j<8: w.im*swap(b)
	VFMADDSUB231PS Z16, Z6, Z22             // half=16 m=1 j<8: w*b
	VSUBPS Z22, Z2, Z6                      // half=16 m=1 j<8: b = a - w*b
	VADDPS Z22, Z2, Z2                      // half=16 m=1 j<8: a = a + w*b
	VSHUFPS $0xb1, Z14, Z14, Z23            // half=16 m=1 j>=8: swap re/im of b
	VMULPS Z20, Z23, Z23                    // half=16 m=1 j>=8: w.im*swap(b)
	VFMADDSUB231PS Z19, Z14, Z23            // half=16 m=1 j>=8: w*b
	VSUBPS Z23, Z10, Z14                    // half=16 m=1 j>=8: b = a - w*b
	VADDPS Z23, Z10, Z10                    // half=16 m=1 j>=8: a = a + w*b
	VSHUFPS $0xb1, Z5, Z5, Z22              // half=16 m=2 j<8: swap re/im of b
	VMULPS Z17, Z22, Z22                    // half=16 m=2 j<8: w.im*swap(b)
	VFMADDSUB231PS Z16, Z5, Z22             // half=16 m=2 j<8: w*b
	VSUBPS Z22, Z1, Z5                      // half=16 m=2 j<8: b = a - w*b
	VADDPS Z22, Z1, Z1                      // half=16 m=2 j<8: a = a + w*b
	VSHUFPS $0xb1, Z13, Z13, Z23            // half=16 m=2 j>=8: swap re/im of b
	VMULPS Z20, Z23, Z23                    // half=16 m=2 j>=8: w.im*swap(b)
	VFMADDSUB231PS Z19, Z13, Z23            // half=16 m=2 j>=8: w*b
	VSUBPS Z23, Z9, Z13                     // half=16 m=2 j>=8: b = a - w*b
	VADDPS Z23, Z9, Z9                      // half=16 m=2 j>=8: a = a + w*b
	VSHUFPS $0xb1, Z7, Z7, Z22              // half=16 m=3 j<8: swap re/im of b
	VMULPS Z17, Z22, Z22                    // half=16 m=3 j<8: w.im*swap(b)
	VFMADDSUB231PS Z16, Z7, Z22             // half=16 m=3 j<8: w*b
	VSUBPS Z22, Z3, Z7                      // half=16 m=3 j<8: b = a - w*b
	VADDPS Z22, Z3, Z3                      // half=16 m=3 j<8: a = a + w*b
	VSHUFPS $0xb1, Z15, Z15, Z23            // half=16 m=3 j>=8: swap re/im of b
	VMULPS Z20, Z23, Z23                    // half=16 m=3 j>=8: w.im*swap(b)
	VFMADDSUB231PS Z19, Z15, Z23            // half=16 m=3 j>=8: w*b
	VSUBPS Z23, Z11, Z15                    // half=16 m=3 j>=8: b = a - w*b
	VADDPS Z23, Z11, Z11                    // half=16 m=3 j>=8: a = a + w*b
	VMOVUPS ·avx512f32Radix8W64(SB), Z18   // stage half=32 t=0 w = [W64^(0+u)]
	VMOVSLDUP Z18, Z16                      // stage half=32 t=0 w = [W64^(0+u)]: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=32 t=0 w = [W64^(0+u)]: w.im -> both halves
	VSHUFPS $0xb1, Z2, Z2, Z19              // half=32 m=0 t=0: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=32 m=0 t=0: w.im*swap(b)
	VFMADDSUB231PS Z16, Z2, Z19             // half=32 m=0 t=0: w*b
	VSUBPS Z19, Z0, Z2                      // half=32 m=0 t=0: b = a - w*b
	VADDPS Z19, Z0, Z0                      // half=32 m=0 t=0: a = a + w*b
	VSHUFPS $0xb1, Z3, Z3, Z20              // half=32 m=1 t=0: swap re/im of b
	VMULPS Z17, Z20, Z20                    // half=32 m=1 t=0: w.im*swap(b)
	VFMADDSUB231PS Z16, Z3, Z20             // half=32 m=1 t=0: w*b
	VSUBPS Z20, Z1, Z3                      // half=32 m=1 t=0: b = a - w*b
	VADDPS Z20, Z1, Z1                      // half=32 m=1 t=0: a = a + w*b
	VMOVUPS ·avx512f32Radix8W64+64(SB), Z18 // stage half=32 t=1 w = [W64^(8+u)]
	VMOVSLDUP Z18, Z16                      // stage half=32 t=1 w = [W64^(8+u)]: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=32 t=1 w = [W64^(8+u)]: w.im -> both halves
	VSHUFPS $0xb1, Z10, Z10, Z19            // half=32 m=0 t=1: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=32 m=0 t=1: w.im*swap(b)
	VFMADDSUB231PS Z16, Z10, Z19            // half=32 m=0 t=1: w*b
	VSUBPS Z19, Z8, Z10                     // half=32 m=0 t=1: b = a - w*b
	VADDPS Z19, Z8, Z8                      // half=32 m=0 t=1: a = a + w*b
	VSHUFPS $0xb1, Z11, Z11, Z20            // half=32 m=1 t=1: swap re/im of b
	VMULPS Z17, Z20, Z20                    // half=32 m=1 t=1: w.im*swap(b)
	VFMADDSUB231PS Z16, Z11, Z20            // half=32 m=1 t=1: w*b
	VSUBPS Z20, Z9, Z11                     // half=32 m=1 t=1: b = a - w*b
	VADDPS Z20, Z9, Z9                      // half=32 m=1 t=1: a = a + w*b
	VMOVUPS ·avx512f32Radix8W64+128(SB), Z18 // stage half=32 t=2 w = [W64^(16+u)]
	VMOVSLDUP Z18, Z16                      // stage half=32 t=2 w = [W64^(16+u)]: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=32 t=2 w = [W64^(16+u)]: w.im -> both halves
	VSHUFPS $0xb1, Z6, Z6, Z19              // half=32 m=0 t=2: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=32 m=0 t=2: w.im*swap(b)
	VFMADDSUB231PS Z16, Z6, Z19             // half=32 m=0 t=2: w*b
	VSUBPS Z19, Z4, Z6                      // half=32 m=0 t=2: b = a - w*b
	VADDPS Z19, Z4, Z4                      // half=32 m=0 t=2: a = a + w*b
	VSHUFPS $0xb1, Z7, Z7, Z20              // half=32 m=1 t=2: swap re/im of b
	VMULPS Z17, Z20, Z20                    // half=32 m=1 t=2: w.im*swap(b)
	VFMADDSUB231PS Z16, Z7, Z20             // half=32 m=1 t=2: w*b
	VSUBPS Z20, Z5, Z7                      // half=32 m=1 t=2: b = a - w*b
	VADDPS Z20, Z5, Z5                      // half=32 m=1 t=2: a = a + w*b
	VMOVUPS ·avx512f32Radix8W64+192(SB), Z18 // stage half=32 t=3 w = [W64^(24+u)]
	VMOVSLDUP Z18, Z16                      // stage half=32 t=3 w = [W64^(24+u)]: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=32 t=3 w = [W64^(24+u)]: w.im -> both halves
	VSHUFPS $0xb1, Z14, Z14, Z19            // half=32 m=0 t=3: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=32 m=0 t=3: w.im*swap(b)
	VFMADDSUB231PS Z16, Z14, Z19            // half=32 m=0 t=3: w*b
	VSUBPS Z19, Z12, Z14                    // half=32 m=0 t=3: b = a - w*b
	VADDPS Z19, Z12, Z12                    // half=32 m=0 t=3: a = a + w*b
	VSHUFPS $0xb1, Z15, Z15, Z20            // half=32 m=1 t=3: swap re/im of b
	VMULPS Z17, Z20, Z20                    // half=32 m=1 t=3: w.im*swap(b)
	VFMADDSUB231PS Z16, Z15, Z20            // half=32 m=1 t=3: w*b
	VSUBPS Z20, Z13, Z15                    // half=32 m=1 t=3: b = a - w*b
	VADDPS Z20, Z13, Z13                    // half=32 m=1 t=3: a = a + w*b
	VMOVUPS (R10), Z18                      // stage half=64 t=0: twiddle[0..7]
	VMOVSLDUP Z18, Z16                      // stage half=64 t=0 w: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=64 t=0 w: w.im -> both halves
	VSHUFPS $0xb1, Z1, Z1, Z19              // half=64 t=0: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=64 t=0: w.im*swap(b)
	VFMADDSUB231PS Z16, Z1, Z19             // half=64 t=0: w*b
	VSUBPS Z19, Z0, Z1                      // half=64 t=0: b = a - w*b
	VADDPS Z19, Z0, Z0                      // half=64 t=0: a = a + w*b
	VMOVUPS 64(R10), Z18                    // stage half=64 t=1: twiddle[8..15]
	VMOVSLDUP Z18, Z16                      // stage half=64 t=1 w: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=64 t=1 w: w.im -> both halves
	VSHUFPS $0xb1, Z9, Z9, Z19              // half=64 t=1: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=64 t=1: w.im*swap(b)
	VFMADDSUB231PS Z16, Z9, Z19             // half=64 t=1: w*b
	VSUBPS Z19, Z8, Z9                      // half=64 t=1: b = a - w*b
	VADDPS Z19, Z8, Z8                      // half=64 t=1: a = a + w*b
	VMOVUPS 128(R10), Z18                   // stage half=64 t=2: twiddle[16..23]
	VMOVSLDUP Z18, Z16                      // stage half=64 t=2 w: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=64 t=2 w: w.im -> both halves
	VSHUFPS $0xb1, Z5, Z5, Z19              // half=64 t=2: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=64 t=2: w.im*swap(b)
	VFMADDSUB231PS Z16, Z5, Z19             // half=64 t=2: w*b
	VSUBPS Z19, Z4, Z5                      // half=64 t=2: b = a - w*b
	VADDPS Z19, Z4, Z4                      // half=64 t=2: a = a + w*b
	VMOVUPS 192(R10), Z18                   // stage half=64 t=3: twiddle[24..31]
	VMOVSLDUP Z18, Z16                      // stage half=64 t=3 w: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=64 t=3 w: w.im -> both halves
	VSHUFPS $0xb1, Z13, Z13, Z19            // half=64 t=3: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=64 t=3: w.im*swap(b)
	VFMADDSUB231PS Z16, Z13, Z19            // half=64 t=3: w*b
	VSUBPS Z19, Z12, Z13                    // half=64 t=3: b = a - w*b
	VADDPS Z19, Z12, Z12                    // half=64 t=3: a = a + w*b
	VMOVUPS 256(R10), Z18                   // stage half=64 t=4: twiddle[32..39]
	VMOVSLDUP Z18, Z16                      // stage half=64 t=4 w: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=64 t=4 w: w.im -> both halves
	VSHUFPS $0xb1, Z3, Z3, Z19              // half=64 t=4: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=64 t=4: w.im*swap(b)
	VFMADDSUB231PS Z16, Z3, Z19             // half=64 t=4: w*b
	VSUBPS Z19, Z2, Z3                      // half=64 t=4: b = a - w*b
	VADDPS Z19, Z2, Z2                      // half=64 t=4: a = a + w*b
	VMOVUPS 320(R10), Z18                   // stage half=64 t=5: twiddle[40..47]
	VMOVSLDUP Z18, Z16                      // stage half=64 t=5 w: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=64 t=5 w: w.im -> both halves
	VSHUFPS $0xb1, Z11, Z11, Z19            // half=64 t=5: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=64 t=5: w.im*swap(b)
	VFMADDSUB231PS Z16, Z11, Z19            // half=64 t=5: w*b
	VSUBPS Z19, Z10, Z11                    // half=64 t=5: b = a - w*b
	VADDPS Z19, Z10, Z10                    // half=64 t=5: a = a + w*b
	VMOVUPS 384(R10), Z18                   // stage half=64 t=6: twiddle[48..55]
	VMOVSLDUP Z18, Z16                      // stage half=64 t=6 w: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=64 t=6 w: w.im -> both halves
	VSHUFPS $0xb1, Z7, Z7, Z19              // half=64 t=6: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=64 t=6: w.im*swap(b)
	VFMADDSUB231PS Z16, Z7, Z19             // half=64 t=6: w*b
	VSUBPS Z19, Z6, Z7                      // half=64 t=6: b = a - w*b
	VADDPS Z19, Z6, Z6                      // half=64 t=6: a = a + w*b
	VMOVUPS 448(R10), Z18                   // stage half=64 t=7: twiddle[56..63]
	VMOVSLDUP Z18, Z16                      // stage half=64 t=7 w: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=64 t=7 w: w.im -> both halves
	VSHUFPS $0xb1, Z15, Z15, Z19            // half=64 t=7: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=64 t=7: w.im*swap(b)
	VFMADDSUB231PS Z16, Z15, Z19            // half=64 t=7: w*b
	VSUBPS Z19, Z14, Z15                    // half=64 t=7: b = a - w*b
	VADDPS Z19, Z14, Z14                    // half=64 t=7: a = a + w*b
	VMOVUPS Z0, (R8)                        // dst[0..7]
	VMOVUPS Z8, 64(R8)                      // dst[8..15]
	VMOVUPS Z4, 128(R8)                     // dst[16..23]
	VMOVUPS Z12, 192(R8)                    // dst[24..31]
	VMOVUPS Z2, 256(R8)                     // dst[32..39]
	VMOVUPS Z10, 320(R8)                    // dst[40..47]
	VMOVUPS Z6, 384(R8)                     // dst[48..55]
	VMOVUPS Z14, 448(R8)                    // dst[56..63]
	VMOVUPS Z1, 512(R8)                     // dst[64..71]
	VMOVUPS Z9, 576(R8)                     // dst[72..79]
	VMOVUPS Z5, 640(R8)                     // dst[80..87]
	VMOVUPS Z13, 704(R8)                    // dst[88..95]
	VMOVUPS Z3, 768(R8)                     // dst[96..103]
	VMOVUPS Z11, 832(R8)                    // dst[104..111]
	VMOVUPS Z7, 896(R8)                     // dst[112..119]
	VMOVUPS Z15, 960(R8)                    // dst[120..127]

	VZEROUPPER
	MOVB $1, ret+96(FP)
	RET

fwd128_false:
	VZEROUPPER
	MOVB $0, ret+96(FP)
	RET

TEXT ·InverseAVX512Size128Radix8Then2Complex64Asm(SB), NOSPLIT, $0-97
	MOVQ src+24(FP), R9      // R9  = src pointer
	MOVQ src_len+32(FP), AX
	CMPQ AX, $128
	JNE  inv128_false            // only length 128 is handled
	MOVQ dst+0(FP), R8       // R8  = dst pointer
	MOVQ dst_len+8(FP), AX
	CMPQ AX, $128
	JL   inv128_false            // dst too short
	MOVQ twiddle+48(FP), R10 // R10 = twiddle pointer
	MOVQ twiddle_len+56(FP), AX
	CMPQ AX, $128
	JL   inv128_false            // twiddle too short
	MOVQ scratch+72(FP), R11 // R11 = scratch pointer
	MOVQ scratch_len+80(FP), AX
	CMPQ AX, $128
	JL   inv128_false            // scratch too short
	MOVW $0xcccc, AX
	KMOVW AX, K1           // K1 = odd complex of each adjacent pair
	MOVW $0xf0f0, AX
	KMOVW AX, K2           // K2 = complex 2,3 of each group of 4
	MOVW $0xff00, AX
	KMOVW AX, K3           // K3 = complex 4..7

	VMOVUPS (R9), Z16                       // bitrev cols 0..7: src[0..] (row 0, cols 0..7)
	VMOVUPS 512(R9), Z17                    // bitrev cols 0..7: src[64..] (row 4, cols 0..7)
	VMOVUPS 256(R9), Z18                    // bitrev cols 0..7: src[32..] (row 2, cols 0..7)
	VMOVUPS 768(R9), Z19                    // bitrev cols 0..7: src[96..] (row 6, cols 0..7)
	VMOVUPS 128(R9), Z20                    // bitrev cols 0..7: src[16..] (row 1, cols 0..7)
	VMOVUPS 640(R9), Z21                    // bitrev cols 0..7: src[80..] (row 5, cols 0..7)
	VMOVUPS 384(R9), Z22                    // bitrev cols 0..7: src[48..] (row 3, cols 0..7)
	VMOVUPS 896(R9), Z23                    // bitrev cols 0..7: src[112..] (row 7, cols 0..7)
	VUNPCKLPD Z17, Z16, Z0                  // bitrev cols 0..7 L1
	VUNPCKHPD Z17, Z16, Z1                  // bitrev cols 0..7 L1
	VUNPCKLPD Z19, Z18, Z2                  // bitrev cols 0..7 L1
	VUNPCKHPD Z19, Z18, Z3                  // bitrev cols 0..7 L1
	VUNPCKLPD Z21, Z20, Z4                  // bitrev cols 0..7 L1
	VUNPCKHPD Z21, Z20, Z5                  // bitrev cols 0..7 L1
	VUNPCKLPD Z23, Z22, Z6                  // bitrev cols 0..7 L1
	VUNPCKHPD Z23, Z22, Z7                  // bitrev cols 0..7 L1
	VSHUFF64X2 $0x88, Z2, Z0, Z16           // bitrev cols 0..7 L2
	VSHUFF64X2 $0xdd, Z2, Z0, Z18           // bitrev cols 0..7 L2
	VSHUFF64X2 $0x88, Z3, Z1, Z17           // bitrev cols 0..7 L2
	VSHUFF64X2 $0xdd, Z3, Z1, Z19           // bitrev cols 0..7 L2
	VSHUFF64X2 $0x88, Z6, Z4, Z20           // bitrev cols 0..7 L2
	VSHUFF64X2 $0xdd, Z6, Z4, Z22           // bitrev cols 0..7 L2
	VSHUFF64X2 $0x88, Z7, Z5, Z21           // bitrev cols 0..7 L2
	VSHUFF64X2 $0xdd, Z7, Z5, Z23           // bitrev cols 0..7 L2
	VSHUFF64X2 $0x88, Z20, Z16, Z0          // bitrev cols 0..7 L3
	VSHUFF64X2 $0xdd, Z20, Z16, Z4          // bitrev cols 0..7 L3
	VSHUFF64X2 $0x88, Z21, Z17, Z1          // bitrev cols 0..7 L3
	VSHUFF64X2 $0xdd, Z21, Z17, Z5          // bitrev cols 0..7 L3
	VSHUFF64X2 $0x88, Z22, Z18, Z2          // bitrev cols 0..7 L3
	VSHUFF64X2 $0xdd, Z22, Z18, Z6          // bitrev cols 0..7 L3
	VSHUFF64X2 $0x88, Z23, Z19, Z3          // bitrev cols 0..7 L3
	VSHUFF64X2 $0xdd, Z23, Z19, Z7          // bitrev cols 0..7 L3
	VMOVUPS 64(R9), Z16                     // bitrev cols 8..15: src[8..] (row 0, cols 8..15)
	VMOVUPS 576(R9), Z17                    // bitrev cols 8..15: src[72..] (row 4, cols 8..15)
	VMOVUPS 320(R9), Z18                    // bitrev cols 8..15: src[40..] (row 2, cols 8..15)
	VMOVUPS 832(R9), Z19                    // bitrev cols 8..15: src[104..] (row 6, cols 8..15)
	VMOVUPS 192(R9), Z20                    // bitrev cols 8..15: src[24..] (row 1, cols 8..15)
	VMOVUPS 704(R9), Z21                    // bitrev cols 8..15: src[88..] (row 5, cols 8..15)
	VMOVUPS 448(R9), Z22                    // bitrev cols 8..15: src[56..] (row 3, cols 8..15)
	VMOVUPS 960(R9), Z23                    // bitrev cols 8..15: src[120..] (row 7, cols 8..15)
	VUNPCKLPD Z17, Z16, Z24                 // bitrev cols 8..15 L1
	VUNPCKHPD Z17, Z16, Z25                 // bitrev cols 8..15 L1
	VUNPCKLPD Z19, Z18, Z26                 // bitrev cols 8..15 L1
	VUNPCKHPD Z19, Z18, Z27                 // bitrev cols 8..15 L1
	VUNPCKLPD Z21, Z20, Z28                 // bitrev cols 8..15 L1
	VUNPCKHPD Z21, Z20, Z29                 // bitrev cols 8..15 L1
	VUNPCKLPD Z23, Z22, Z30                 // bitrev cols 8..15 L1
	VUNPCKHPD Z23, Z22, Z31                 // bitrev cols 8..15 L1
	VSHUFF64X2 $0x88, Z26, Z24, Z16         // bitrev cols 8..15 L2
	VSHUFF64X2 $0xdd, Z26, Z24, Z18         // bitrev cols 8..15 L2
	VSHUFF64X2 $0x88, Z27, Z25, Z17         // bitrev cols 8..15 L2
	VSHUFF64X2 $0xdd, Z27, Z25, Z19         // bitrev cols 8..15 L2
	VSHUFF64X2 $0x88, Z30, Z28, Z20         // bitrev cols 8..15 L2
	VSHUFF64X2 $0xdd, Z30, Z28, Z22         // bitrev cols 8..15 L2
	VSHUFF64X2 $0x88, Z31, Z29, Z21         // bitrev cols 8..15 L2
	VSHUFF64X2 $0xdd, Z31, Z29, Z23         // bitrev cols 8..15 L2
	VSHUFF64X2 $0x88, Z20, Z16, Z8          // bitrev cols 8..15 L3
	VSHUFF64X2 $0xdd, Z20, Z16, Z12         // bitrev cols 8..15 L3
	VSHUFF64X2 $0x88, Z21, Z17, Z9          // bitrev cols 8..15 L3
	VSHUFF64X2 $0xdd, Z21, Z17, Z13         // bitrev cols 8..15 L3
	VSHUFF64X2 $0x88, Z22, Z18, Z10         // bitrev cols 8..15 L3
	VSHUFF64X2 $0xdd, Z22, Z18, Z14         // bitrev cols 8..15 L3
	VSHUFF64X2 $0x88, Z23, Z19, Z11         // bitrev cols 8..15 L3
	VSHUFF64X2 $0xdd, Z23, Z19, Z15         // bitrev cols 8..15 L3
	VMOVUPS ·avx512f32Radix8W4(SB), Z16    // leaf half=2 w = [1,1,1,-i]
	VMOVSLDUP Z16, Z24                      // leaf half=2 w = [1,1,1,-i]: w.re -> both halves
	VMOVSHDUP Z16, Z25                      // leaf half=2 w = [1,1,1,-i]: w.im -> both halves
	VMOVUPS ·avx512f32Radix8W8(SB), Z16    // leaf half=4 w = [1,1,1,1,W8^0..3]
	VMOVSLDUP Z16, Z26                      // leaf half=4 w = [1,1,1,1,W8^0..3]: w.re -> both halves
	VMOVSHDUP Z16, Z27                      // leaf half=4 w = [1,1,1,1,W8^0..3]: w.im -> both halves
	VPERMILPS $0x4e, Z0, Z16                // leaf A: partner = adjacent complex
	VADDPS Z16, Z0, Z17                     // leaf A: a+p
	VSUBPS Z0, Z16, K1, Z17                 // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z1, Z18                // leaf A: partner = adjacent complex
	VADDPS Z18, Z1, Z19                     // leaf A: a+p
	VSUBPS Z1, Z18, K1, Z19                 // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z2, Z20                // leaf A: partner = adjacent complex
	VADDPS Z20, Z2, Z21                     // leaf A: a+p
	VSUBPS Z2, Z20, K1, Z21                 // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z3, Z22                // leaf A: partner = adjacent complex
	VADDPS Z22, Z3, Z23                     // leaf A: a+p
	VSUBPS Z3, Z22, K1, Z23                 // leaf A: odd complex := p-a
	VSHUFPS $0xb1, Z17, Z17, Z16            // leaf B: swap re/im of b
	VMULPS Z25, Z16, Z16                    // leaf B: w.im*swap(b)
	VFMSUBADD231PS Z24, Z17, Z16            // leaf B: conj(w)*b
	VSHUFF32X4 $0xb1, Z16, Z16, Z17         // leaf B: partner = 128-bit lane swap
	VADDPS Z17, Z16, Z0                     // leaf B: a+w*b
	VSUBPS Z16, Z17, K2, Z0                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z19, Z19, Z18            // leaf B: swap re/im of b
	VMULPS Z25, Z18, Z18                    // leaf B: w.im*swap(b)
	VFMSUBADD231PS Z24, Z19, Z18            // leaf B: conj(w)*b
	VSHUFF32X4 $0xb1, Z18, Z18, Z19         // leaf B: partner = 128-bit lane swap
	VADDPS Z19, Z18, Z1                     // leaf B: a+w*b
	VSUBPS Z18, Z19, K2, Z1                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z21, Z21, Z20            // leaf B: swap re/im of b
	VMULPS Z25, Z20, Z20                    // leaf B: w.im*swap(b)
	VFMSUBADD231PS Z24, Z21, Z20            // leaf B: conj(w)*b
	VSHUFF32X4 $0xb1, Z20, Z20, Z21         // leaf B: partner = 128-bit lane swap
	VADDPS Z21, Z20, Z2                     // leaf B: a+w*b
	VSUBPS Z20, Z21, K2, Z2                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z23, Z23, Z22            // leaf B: swap re/im of b
	VMULPS Z25, Z22, Z22                    // leaf B: w.im*swap(b)
	VFMSUBADD231PS Z24, Z23, Z22            // leaf B: conj(w)*b
	VSHUFF32X4 $0xb1, Z22, Z22, Z23         // leaf B: partner = 128-bit lane swap
	VADDPS Z23, Z22, Z3                     // leaf B: a+w*b
	VSUBPS Z22, Z23, K2, Z3                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z0, Z0, Z16              // leaf C: swap re/im of b
	VMULPS Z27, Z16, Z16                    // leaf C: w.im*swap(b)
	VFMSUBADD231PS Z26, Z0, Z16             // leaf C: conj(w)*b
	VSHUFF32X4 $0x4e, Z16, Z16, Z17         // leaf C: partner = 256-bit half swap
	VADDPS Z17, Z16, Z0                     // leaf C: a+w*b
	VSUBPS Z16, Z17, K3, Z0                 // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z1, Z1, Z18              // leaf C: swap re/im of b
	VMULPS Z27, Z18, Z18                    // leaf C: w.im*swap(b)
	VFMSUBADD231PS Z26, Z1, Z18             // leaf C: conj(w)*b
	VSHUFF32X4 $0x4e, Z18, Z18, Z19         // leaf C: partner = 256-bit half swap
	VADDPS Z19, Z18, Z1                     // leaf C: a+w*b
	VSUBPS Z18, Z19, K3, Z1                 // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z2, Z2, Z20              // leaf C: swap re/im of b
	VMULPS Z27, Z20, Z20                    // leaf C: w.im*swap(b)
	VFMSUBADD231PS Z26, Z2, Z20             // leaf C: conj(w)*b
	VSHUFF32X4 $0x4e, Z20, Z20, Z21         // leaf C: partner = 256-bit half swap
	VADDPS Z21, Z20, Z2                     // leaf C: a+w*b
	VSUBPS Z20, Z21, K3, Z2                 // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z3, Z3, Z22              // leaf C: swap re/im of b
	VMULPS Z27, Z22, Z22                    // leaf C: w.im*swap(b)
	VFMSUBADD231PS Z26, Z3, Z22             // leaf C: conj(w)*b
	VSHUFF32X4 $0x4e, Z22, Z22, Z23         // leaf C: partner = 256-bit half swap
	VADDPS Z23, Z22, Z3                     // leaf C: a+w*b
	VSUBPS Z22, Z23, K3, Z3                 // leaf C: complex 4..7 := a-w*b
	VPERMILPS $0x4e, Z4, Z16                // leaf A: partner = adjacent complex
	VADDPS Z16, Z4, Z17                     // leaf A: a+p
	VSUBPS Z4, Z16, K1, Z17                 // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z5, Z18                // leaf A: partner = adjacent complex
	VADDPS Z18, Z5, Z19                     // leaf A: a+p
	VSUBPS Z5, Z18, K1, Z19                 // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z6, Z20                // leaf A: partner = adjacent complex
	VADDPS Z20, Z6, Z21                     // leaf A: a+p
	VSUBPS Z6, Z20, K1, Z21                 // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z7, Z22                // leaf A: partner = adjacent complex
	VADDPS Z22, Z7, Z23                     // leaf A: a+p
	VSUBPS Z7, Z22, K1, Z23                 // leaf A: odd complex := p-a
	VSHUFPS $0xb1, Z17, Z17, Z16            // leaf B: swap re/im of b
	VMULPS Z25, Z16, Z16                    // leaf B: w.im*swap(b)
	VFMSUBADD231PS Z24, Z17, Z16            // leaf B: conj(w)*b
	VSHUFF32X4 $0xb1, Z16, Z16, Z17         // leaf B: partner = 128-bit lane swap
	VADDPS Z17, Z16, Z4                     // leaf B: a+w*b
	VSUBPS Z16, Z17, K2, Z4                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z19, Z19, Z18            // leaf B: swap re/im of b
	VMULPS Z25, Z18, Z18                    // leaf B: w.im*swap(b)
	VFMSUBADD231PS Z24, Z19, Z18            // leaf B: conj(w)*b
	VSHUFF32X4 $0xb1, Z18, Z18, Z19         // leaf B: partner = 128-bit lane swap
	VADDPS Z19, Z18, Z5                     // leaf B: a+w*b
	VSUBPS Z18, Z19, K2, Z5                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z21, Z21, Z20            // leaf B: swap re/im of b
	VMULPS Z25, Z20, Z20                    // leaf B: w.im*swap(b)
	VFMSUBADD231PS Z24, Z21, Z20            // leaf B: conj(w)*b
	VSHUFF32X4 $0xb1, Z20, Z20, Z21         // leaf B: partner = 128-bit lane swap
	VADDPS Z21, Z20, Z6                     // leaf B: a+w*b
	VSUBPS Z20, Z21, K2, Z6                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z23, Z23, Z22            // leaf B: swap re/im of b
	VMULPS Z25, Z22, Z22                    // leaf B: w.im*swap(b)
	VFMSUBADD231PS Z24, Z23, Z22            // leaf B: conj(w)*b
	VSHUFF32X4 $0xb1, Z22, Z22, Z23         // leaf B: partner = 128-bit lane swap
	VADDPS Z23, Z22, Z7                     // leaf B: a+w*b
	VSUBPS Z22, Z23, K2, Z7                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z4, Z4, Z16              // leaf C: swap re/im of b
	VMULPS Z27, Z16, Z16                    // leaf C: w.im*swap(b)
	VFMSUBADD231PS Z26, Z4, Z16             // leaf C: conj(w)*b
	VSHUFF32X4 $0x4e, Z16, Z16, Z17         // leaf C: partner = 256-bit half swap
	VADDPS Z17, Z16, Z4                     // leaf C: a+w*b
	VSUBPS Z16, Z17, K3, Z4                 // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z5, Z5, Z18              // leaf C: swap re/im of b
	VMULPS Z27, Z18, Z18                    // leaf C: w.im*swap(b)
	VFMSUBADD231PS Z26, Z5, Z18             // leaf C: conj(w)*b
	VSHUFF32X4 $0x4e, Z18, Z18, Z19         // leaf C: partner = 256-bit half swap
	VADDPS Z19, Z18, Z5                     // leaf C: a+w*b
	VSUBPS Z18, Z19, K3, Z5                 // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z6, Z6, Z20              // leaf C: swap re/im of b
	VMULPS Z27, Z20, Z20                    // leaf C: w.im*swap(b)
	VFMSUBADD231PS Z26, Z6, Z20             // leaf C: conj(w)*b
	VSHUFF32X4 $0x4e, Z20, Z20, Z21         // leaf C: partner = 256-bit half swap
	VADDPS Z21, Z20, Z6                     // leaf C: a+w*b
	VSUBPS Z20, Z21, K3, Z6                 // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z7, Z7, Z22              // leaf C: swap re/im of b
	VMULPS Z27, Z22, Z22                    // leaf C: w.im*swap(b)
	VFMSUBADD231PS Z26, Z7, Z22             // leaf C: conj(w)*b
	VSHUFF32X4 $0x4e, Z22, Z22, Z23         // leaf C: partner = 256-bit half swap
	VADDPS Z23, Z22, Z7                     // leaf C: a+w*b
	VSUBPS Z22, Z23, K3, Z7                 // leaf C: complex 4..7 := a-w*b
	VPERMILPS $0x4e, Z8, Z16                // leaf A: partner = adjacent complex
	VADDPS Z16, Z8, Z17                     // leaf A: a+p
	VSUBPS Z8, Z16, K1, Z17                 // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z9, Z18                // leaf A: partner = adjacent complex
	VADDPS Z18, Z9, Z19                     // leaf A: a+p
	VSUBPS Z9, Z18, K1, Z19                 // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z10, Z20               // leaf A: partner = adjacent complex
	VADDPS Z20, Z10, Z21                    // leaf A: a+p
	VSUBPS Z10, Z20, K1, Z21                // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z11, Z22               // leaf A: partner = adjacent complex
	VADDPS Z22, Z11, Z23                    // leaf A: a+p
	VSUBPS Z11, Z22, K1, Z23                // leaf A: odd complex := p-a
	VSHUFPS $0xb1, Z17, Z17, Z16            // leaf B: swap re/im of b
	VMULPS Z25, Z16, Z16                    // leaf B: w.im*swap(b)
	VFMSUBADD231PS Z24, Z17, Z16            // leaf B: conj(w)*b
	VSHUFF32X4 $0xb1, Z16, Z16, Z17         // leaf B: partner = 128-bit lane swap
	VADDPS Z17, Z16, Z8                     // leaf B: a+w*b
	VSUBPS Z16, Z17, K2, Z8                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z19, Z19, Z18            // leaf B: swap re/im of b
	VMULPS Z25, Z18, Z18                    // leaf B: w.im*swap(b)
	VFMSUBADD231PS Z24, Z19, Z18            // leaf B: conj(w)*b
	VSHUFF32X4 $0xb1, Z18, Z18, Z19         // leaf B: partner = 128-bit lane swap
	VADDPS Z19, Z18, Z9                     // leaf B: a+w*b
	VSUBPS Z18, Z19, K2, Z9                 // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z21, Z21, Z20            // leaf B: swap re/im of b
	VMULPS Z25, Z20, Z20                    // leaf B: w.im*swap(b)
	VFMSUBADD231PS Z24, Z21, Z20            // leaf B: conj(w)*b
	VSHUFF32X4 $0xb1, Z20, Z20, Z21         // leaf B: partner = 128-bit lane swap
	VADDPS Z21, Z20, Z10                    // leaf B: a+w*b
	VSUBPS Z20, Z21, K2, Z10                // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z23, Z23, Z22            // leaf B: swap re/im of b
	VMULPS Z25, Z22, Z22                    // leaf B: w.im*swap(b)
	VFMSUBADD231PS Z24, Z23, Z22            // leaf B: conj(w)*b
	VSHUFF32X4 $0xb1, Z22, Z22, Z23         // leaf B: partner = 128-bit lane swap
	VADDPS Z23, Z22, Z11                    // leaf B: a+w*b
	VSUBPS Z22, Z23, K2, Z11                // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z8, Z8, Z16              // leaf C: swap re/im of b
	VMULPS Z27, Z16, Z16                    // leaf C: w.im*swap(b)
	VFMSUBADD231PS Z26, Z8, Z16             // leaf C: conj(w)*b
	VSHUFF32X4 $0x4e, Z16, Z16, Z17         // leaf C: partner = 256-bit half swap
	VADDPS Z17, Z16, Z8                     // leaf C: a+w*b
	VSUBPS Z16, Z17, K3, Z8                 // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z9, Z9, Z18              // leaf C: swap re/im of b
	VMULPS Z27, Z18, Z18                    // leaf C: w.im*swap(b)
	VFMSUBADD231PS Z26, Z9, Z18             // leaf C: conj(w)*b
	VSHUFF32X4 $0x4e, Z18, Z18, Z19         // leaf C: partner = 256-bit half swap
	VADDPS Z19, Z18, Z9                     // leaf C: a+w*b
	VSUBPS Z18, Z19, K3, Z9                 // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z10, Z10, Z20            // leaf C: swap re/im of b
	VMULPS Z27, Z20, Z20                    // leaf C: w.im*swap(b)
	VFMSUBADD231PS Z26, Z10, Z20            // leaf C: conj(w)*b
	VSHUFF32X4 $0x4e, Z20, Z20, Z21         // leaf C: partner = 256-bit half swap
	VADDPS Z21, Z20, Z10                    // leaf C: a+w*b
	VSUBPS Z20, Z21, K3, Z10                // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z11, Z11, Z22            // leaf C: swap re/im of b
	VMULPS Z27, Z22, Z22                    // leaf C: w.im*swap(b)
	VFMSUBADD231PS Z26, Z11, Z22            // leaf C: conj(w)*b
	VSHUFF32X4 $0x4e, Z22, Z22, Z23         // leaf C: partner = 256-bit half swap
	VADDPS Z23, Z22, Z11                    // leaf C: a+w*b
	VSUBPS Z22, Z23, K3, Z11                // leaf C: complex 4..7 := a-w*b
	VPERMILPS $0x4e, Z12, Z16               // leaf A: partner = adjacent complex
	VADDPS Z16, Z12, Z17                    // leaf A: a+p
	VSUBPS Z12, Z16, K1, Z17                // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z13, Z18               // leaf A: partner = adjacent complex
	VADDPS Z18, Z13, Z19                    // leaf A: a+p
	VSUBPS Z13, Z18, K1, Z19                // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z14, Z20               // leaf A: partner = adjacent complex
	VADDPS Z20, Z14, Z21                    // leaf A: a+p
	VSUBPS Z14, Z20, K1, Z21                // leaf A: odd complex := p-a
	VPERMILPS $0x4e, Z15, Z22               // leaf A: partner = adjacent complex
	VADDPS Z22, Z15, Z23                    // leaf A: a+p
	VSUBPS Z15, Z22, K1, Z23                // leaf A: odd complex := p-a
	VSHUFPS $0xb1, Z17, Z17, Z16            // leaf B: swap re/im of b
	VMULPS Z25, Z16, Z16                    // leaf B: w.im*swap(b)
	VFMSUBADD231PS Z24, Z17, Z16            // leaf B: conj(w)*b
	VSHUFF32X4 $0xb1, Z16, Z16, Z17         // leaf B: partner = 128-bit lane swap
	VADDPS Z17, Z16, Z12                    // leaf B: a+w*b
	VSUBPS Z16, Z17, K2, Z12                // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z19, Z19, Z18            // leaf B: swap re/im of b
	VMULPS Z25, Z18, Z18                    // leaf B: w.im*swap(b)
	VFMSUBADD231PS Z24, Z19, Z18            // leaf B: conj(w)*b
	VSHUFF32X4 $0xb1, Z18, Z18, Z19         // leaf B: partner = 128-bit lane swap
	VADDPS Z19, Z18, Z13                    // leaf B: a+w*b
	VSUBPS Z18, Z19, K2, Z13                // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z21, Z21, Z20            // leaf B: swap re/im of b
	VMULPS Z25, Z20, Z20                    // leaf B: w.im*swap(b)
	VFMSUBADD231PS Z24, Z21, Z20            // leaf B: conj(w)*b
	VSHUFF32X4 $0xb1, Z20, Z20, Z21         // leaf B: partner = 128-bit lane swap
	VADDPS Z21, Z20, Z14                    // leaf B: a+w*b
	VSUBPS Z20, Z21, K2, Z14                // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z23, Z23, Z22            // leaf B: swap re/im of b
	VMULPS Z25, Z22, Z22                    // leaf B: w.im*swap(b)
	VFMSUBADD231PS Z24, Z23, Z22            // leaf B: conj(w)*b
	VSHUFF32X4 $0xb1, Z22, Z22, Z23         // leaf B: partner = 128-bit lane swap
	VADDPS Z23, Z22, Z15                    // leaf B: a+w*b
	VSUBPS Z22, Z23, K2, Z15                // leaf B: complex 2,3 := a-w*b
	VSHUFPS $0xb1, Z12, Z12, Z16            // leaf C: swap re/im of b
	VMULPS Z27, Z16, Z16                    // leaf C: w.im*swap(b)
	VFMSUBADD231PS Z26, Z12, Z16            // leaf C: conj(w)*b
	VSHUFF32X4 $0x4e, Z16, Z16, Z17         // leaf C: partner = 256-bit half swap
	VADDPS Z17, Z16, Z12                    // leaf C: a+w*b
	VSUBPS Z16, Z17, K3, Z12                // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z13, Z13, Z18            // leaf C: swap re/im of b
	VMULPS Z27, Z18, Z18                    // leaf C: w.im*swap(b)
	VFMSUBADD231PS Z26, Z13, Z18            // leaf C: conj(w)*b
	VSHUFF32X4 $0x4e, Z18, Z18, Z19         // leaf C: partner = 256-bit half swap
	VADDPS Z19, Z18, Z13                    // leaf C: a+w*b
	VSUBPS Z18, Z19, K3, Z13                // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z14, Z14, Z20            // leaf C: swap re/im of b
	VMULPS Z27, Z20, Z20                    // leaf C: w.im*swap(b)
	VFMSUBADD231PS Z26, Z14, Z20            // leaf C: conj(w)*b
	VSHUFF32X4 $0x4e, Z20, Z20, Z21         // leaf C: partner = 256-bit half swap
	VADDPS Z21, Z20, Z14                    // leaf C: a+w*b
	VSUBPS Z20, Z21, K3, Z14                // leaf C: complex 4..7 := a-w*b
	VSHUFPS $0xb1, Z15, Z15, Z22            // leaf C: swap re/im of b
	VMULPS Z27, Z22, Z22                    // leaf C: w.im*swap(b)
	VFMSUBADD231PS Z26, Z15, Z22            // leaf C: conj(w)*b
	VSHUFF32X4 $0x4e, Z22, Z22, Z23         // leaf C: partner = 256-bit half swap
	VADDPS Z23, Z22, Z15                    // leaf C: a+w*b
	VSUBPS Z22, Z23, K3, Z15                // leaf C: complex 4..7 := a-w*b
	VMOVUPS ·avx512f32Radix8W16(SB), Z18   // stage half=8 w = [W16^u]
	VMOVSLDUP Z18, Z16                      // stage half=8 w = [W16^u]: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=8 w = [W16^u]: w.im -> both halves
	VSHUFPS $0xb1, Z8, Z8, Z19              // half=8 m=0: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=8 m=0: w.im*swap(b)
	VFMSUBADD231PS Z16, Z8, Z19             // half=8 m=0: conj(w)*b
	VSUBPS Z19, Z0, Z8                      // half=8 m=0: b = a - w*b
	VADDPS Z19, Z0, Z0                      // half=8 m=0: a = a + w*b
	VSHUFPS $0xb1, Z12, Z12, Z20            // half=8 m=1: swap re/im of b
	VMULPS Z17, Z20, Z20                    // half=8 m=1: w.im*swap(b)
	VFMSUBADD231PS Z16, Z12, Z20            // half=8 m=1: conj(w)*b
	VSUBPS Z20, Z4, Z12                     // half=8 m=1: b = a - w*b
	VADDPS Z20, Z4, Z4                      // half=8 m=1: a = a + w*b
	VSHUFPS $0xb1, Z10, Z10, Z21            // half=8 m=2: swap re/im of b
	VMULPS Z17, Z21, Z21                    // half=8 m=2: w.im*swap(b)
	VFMSUBADD231PS Z16, Z10, Z21            // half=8 m=2: conj(w)*b
	VSUBPS Z21, Z2, Z10                     // half=8 m=2: b = a - w*b
	VADDPS Z21, Z2, Z2                      // half=8 m=2: a = a + w*b
	VSHUFPS $0xb1, Z14, Z14, Z22            // half=8 m=3: swap re/im of b
	VMULPS Z17, Z22, Z22                    // half=8 m=3: w.im*swap(b)
	VFMSUBADD231PS Z16, Z14, Z22            // half=8 m=3: conj(w)*b
	VSUBPS Z22, Z6, Z14                     // half=8 m=3: b = a - w*b
	VADDPS Z22, Z6, Z6                      // half=8 m=3: a = a + w*b
	VSHUFPS $0xb1, Z9, Z9, Z19              // half=8 m=4: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=8 m=4: w.im*swap(b)
	VFMSUBADD231PS Z16, Z9, Z19             // half=8 m=4: conj(w)*b
	VSUBPS Z19, Z1, Z9                      // half=8 m=4: b = a - w*b
	VADDPS Z19, Z1, Z1                      // half=8 m=4: a = a + w*b
	VSHUFPS $0xb1, Z13, Z13, Z20            // half=8 m=5: swap re/im of b
	VMULPS Z17, Z20, Z20                    // half=8 m=5: w.im*swap(b)
	VFMSUBADD231PS Z16, Z13, Z20            // half=8 m=5: conj(w)*b
	VSUBPS Z20, Z5, Z13                     // half=8 m=5: b = a - w*b
	VADDPS Z20, Z5, Z5                      // half=8 m=5: a = a + w*b
	VSHUFPS $0xb1, Z11, Z11, Z21            // half=8 m=6: swap re/im of b
	VMULPS Z17, Z21, Z21                    // half=8 m=6: w.im*swap(b)
	VFMSUBADD231PS Z16, Z11, Z21            // half=8 m=6: conj(w)*b
	VSUBPS Z21, Z3, Z11                     // half=8 m=6: b = a - w*b
	VADDPS Z21, Z3, Z3                      // half=8 m=6: a = a + w*b
	VSHUFPS $0xb1, Z15, Z15, Z22            // half=8 m=7: swap re/im of b
	VMULPS Z17, Z22, Z22                    // half=8 m=7: w.im*swap(b)
	VFMSUBADD231PS Z16, Z15, Z22            // half=8 m=7: conj(w)*b
	VSUBPS Z22, Z7, Z15                     // half=8 m=7: b = a - w*b
	VADDPS Z22, Z7, Z7                      // half=8 m=7: a = a + w*b
	VMOVUPS ·avx512f32Radix8W32(SB), Z18   // stage half=16 w = [W32^u]
	VMOVSLDUP Z18, Z16                      // stage half=16 w = [W32^u]: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=16 w = [W32^u]: w.im -> both halves
	VMOVUPS ·avx512f32Radix8W32+64(SB), Z21 // stage half=16 w = [W32^(8+u)]
	VMOVSLDUP Z21, Z19                      // stage half=16 w = [W32^(8+u)]: w.re -> both halves
	VMOVSHDUP Z21, Z20                      // stage half=16 w = [W32^(8+u)]: w.im -> both halves
	VSHUFPS $0xb1, Z4, Z4, Z22              // half=16 m=0 j<8: swap re/im of b
	VMULPS Z17, Z22, Z22                    // half=16 m=0 j<8: w.im*swap(b)
	VFMSUBADD231PS Z16, Z4, Z22             // half=16 m=0 j<8: conj(w)*b
	VSUBPS Z22, Z0, Z4                      // half=16 m=0 j<8: b = a - w*b
	VADDPS Z22, Z0, Z0                      // half=16 m=0 j<8: a = a + w*b
	VSHUFPS $0xb1, Z12, Z12, Z23            // half=16 m=0 j>=8: swap re/im of b
	VMULPS Z20, Z23, Z23                    // half=16 m=0 j>=8: w.im*swap(b)
	VFMSUBADD231PS Z19, Z12, Z23            // half=16 m=0 j>=8: conj(w)*b
	VSUBPS Z23, Z8, Z12                     // half=16 m=0 j>=8: b = a - w*b
	VADDPS Z23, Z8, Z8                      // half=16 m=0 j>=8: a = a + w*b
	VSHUFPS $0xb1, Z6, Z6, Z22              // half=16 m=1 j<8: swap re/im of b
	VMULPS Z17, Z22, Z22                    // half=16 m=1 j<8: w.im*swap(b)
	VFMSUBADD231PS Z16, Z6, Z22             // half=16 m=1 j<8: conj(w)*b
	VSUBPS Z22, Z2, Z6                      // half=16 m=1 j<8: b = a - w*b
	VADDPS Z22, Z2, Z2                      // half=16 m=1 j<8: a = a + w*b
	VSHUFPS $0xb1, Z14, Z14, Z23            // half=16 m=1 j>=8: swap re/im of b
	VMULPS Z20, Z23, Z23                    // half=16 m=1 j>=8: w.im*swap(b)
	VFMSUBADD231PS Z19, Z14, Z23            // half=16 m=1 j>=8: conj(w)*b
	VSUBPS Z23, Z10, Z14                    // half=16 m=1 j>=8: b = a - w*b
	VADDPS Z23, Z10, Z10                    // half=16 m=1 j>=8: a = a + w*b
	VSHUFPS $0xb1, Z5, Z5, Z22              // half=16 m=2 j<8: swap re/im of b
	VMULPS Z17, Z22, Z22                    // half=16 m=2 j<8: w.im*swap(b)
	VFMSUBADD231PS Z16, Z5, Z22             // half=16 m=2 j<8: conj(w)*b
	VSUBPS Z22, Z1, Z5                      // half=16 m=2 j<8: b = a - w*b
	VADDPS Z22, Z1, Z1                      // half=16 m=2 j<8: a = a + w*b
	VSHUFPS $0xb1, Z13, Z13, Z23            // half=16 m=2 j>=8: swap re/im of b
	VMULPS Z20, Z23, Z23                    // half=16 m=2 j>=8: w.im*swap(b)
	VFMSUBADD231PS Z19, Z13, Z23            // half=16 m=2 j>=8: conj(w)*b
	VSUBPS Z23, Z9, Z13                     // half=16 m=2 j>=8: b = a - w*b
	VADDPS Z23, Z9, Z9                      // half=16 m=2 j>=8: a = a + w*b
	VSHUFPS $0xb1, Z7, Z7, Z22              // half=16 m=3 j<8: swap re/im of b
	VMULPS Z17, Z22, Z22                    // half=16 m=3 j<8: w.im*swap(b)
	VFMSUBADD231PS Z16, Z7, Z22             // half=16 m=3 j<8: conj(w)*b
	VSUBPS Z22, Z3, Z7                      // half=16 m=3 j<8: b = a - w*b
	VADDPS Z22, Z3, Z3                      // half=16 m=3 j<8: a = a + w*b
	VSHUFPS $0xb1, Z15, Z15, Z23            // half=16 m=3 j>=8: swap re/im of b
	VMULPS Z20, Z23, Z23                    // half=16 m=3 j>=8: w.im*swap(b)
	VFMSUBADD231PS Z19, Z15, Z23            // half=16 m=3 j>=8: conj(w)*b
	VSUBPS Z23, Z11, Z15                    // half=16 m=3 j>=8: b = a - w*b
	VADDPS Z23, Z11, Z11                    // half=16 m=3 j>=8: a = a + w*b
	VMOVUPS ·avx512f32Radix8W64(SB), Z18   // stage half=32 t=0 w = [W64^(0+u)]
	VMOVSLDUP Z18, Z16                      // stage half=32 t=0 w = [W64^(0+u)]: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=32 t=0 w = [W64^(0+u)]: w.im -> both halves
	VSHUFPS $0xb1, Z2, Z2, Z19              // half=32 m=0 t=0: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=32 m=0 t=0: w.im*swap(b)
	VFMSUBADD231PS Z16, Z2, Z19             // half=32 m=0 t=0: conj(w)*b
	VSUBPS Z19, Z0, Z2                      // half=32 m=0 t=0: b = a - w*b
	VADDPS Z19, Z0, Z0                      // half=32 m=0 t=0: a = a + w*b
	VSHUFPS $0xb1, Z3, Z3, Z20              // half=32 m=1 t=0: swap re/im of b
	VMULPS Z17, Z20, Z20                    // half=32 m=1 t=0: w.im*swap(b)
	VFMSUBADD231PS Z16, Z3, Z20             // half=32 m=1 t=0: conj(w)*b
	VSUBPS Z20, Z1, Z3                      // half=32 m=1 t=0: b = a - w*b
	VADDPS Z20, Z1, Z1                      // half=32 m=1 t=0: a = a + w*b
	VMOVUPS ·avx512f32Radix8W64+64(SB), Z18 // stage half=32 t=1 w = [W64^(8+u)]
	VMOVSLDUP Z18, Z16                      // stage half=32 t=1 w = [W64^(8+u)]: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=32 t=1 w = [W64^(8+u)]: w.im -> both halves
	VSHUFPS $0xb1, Z10, Z10, Z19            // half=32 m=0 t=1: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=32 m=0 t=1: w.im*swap(b)
	VFMSUBADD231PS Z16, Z10, Z19            // half=32 m=0 t=1: conj(w)*b
	VSUBPS Z19, Z8, Z10                     // half=32 m=0 t=1: b = a - w*b
	VADDPS Z19, Z8, Z8                      // half=32 m=0 t=1: a = a + w*b
	VSHUFPS $0xb1, Z11, Z11, Z20            // half=32 m=1 t=1: swap re/im of b
	VMULPS Z17, Z20, Z20                    // half=32 m=1 t=1: w.im*swap(b)
	VFMSUBADD231PS Z16, Z11, Z20            // half=32 m=1 t=1: conj(w)*b
	VSUBPS Z20, Z9, Z11                     // half=32 m=1 t=1: b = a - w*b
	VADDPS Z20, Z9, Z9                      // half=32 m=1 t=1: a = a + w*b
	VMOVUPS ·avx512f32Radix8W64+128(SB), Z18 // stage half=32 t=2 w = [W64^(16+u)]
	VMOVSLDUP Z18, Z16                      // stage half=32 t=2 w = [W64^(16+u)]: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=32 t=2 w = [W64^(16+u)]: w.im -> both halves
	VSHUFPS $0xb1, Z6, Z6, Z19              // half=32 m=0 t=2: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=32 m=0 t=2: w.im*swap(b)
	VFMSUBADD231PS Z16, Z6, Z19             // half=32 m=0 t=2: conj(w)*b
	VSUBPS Z19, Z4, Z6                      // half=32 m=0 t=2: b = a - w*b
	VADDPS Z19, Z4, Z4                      // half=32 m=0 t=2: a = a + w*b
	VSHUFPS $0xb1, Z7, Z7, Z20              // half=32 m=1 t=2: swap re/im of b
	VMULPS Z17, Z20, Z20                    // half=32 m=1 t=2: w.im*swap(b)
	VFMSUBADD231PS Z16, Z7, Z20             // half=32 m=1 t=2: conj(w)*b
	VSUBPS Z20, Z5, Z7                      // half=32 m=1 t=2: b = a - w*b
	VADDPS Z20, Z5, Z5                      // half=32 m=1 t=2: a = a + w*b
	VMOVUPS ·avx512f32Radix8W64+192(SB), Z18 // stage half=32 t=3 w = [W64^(24+u)]
	VMOVSLDUP Z18, Z16                      // stage half=32 t=3 w = [W64^(24+u)]: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=32 t=3 w = [W64^(24+u)]: w.im -> both halves
	VSHUFPS $0xb1, Z14, Z14, Z19            // half=32 m=0 t=3: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=32 m=0 t=3: w.im*swap(b)
	VFMSUBADD231PS Z16, Z14, Z19            // half=32 m=0 t=3: conj(w)*b
	VSUBPS Z19, Z12, Z14                    // half=32 m=0 t=3: b = a - w*b
	VADDPS Z19, Z12, Z12                    // half=32 m=0 t=3: a = a + w*b
	VSHUFPS $0xb1, Z15, Z15, Z20            // half=32 m=1 t=3: swap re/im of b
	VMULPS Z17, Z20, Z20                    // half=32 m=1 t=3: w.im*swap(b)
	VFMSUBADD231PS Z16, Z15, Z20            // half=32 m=1 t=3: conj(w)*b
	VSUBPS Z20, Z13, Z15                    // half=32 m=1 t=3: b = a - w*b
	VADDPS Z20, Z13, Z13                    // half=32 m=1 t=3: a = a + w*b
	VMOVUPS (R10), Z18                      // stage half=64 t=0: twiddle[0..7]
	VMOVSLDUP Z18, Z16                      // stage half=64 t=0 w: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=64 t=0 w: w.im -> both halves
	VSHUFPS $0xb1, Z1, Z1, Z19              // half=64 t=0: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=64 t=0: w.im*swap(b)
	VFMSUBADD231PS Z16, Z1, Z19             // half=64 t=0: conj(w)*b
	VSUBPS Z19, Z0, Z1                      // half=64 t=0: b = a - w*b
	VADDPS Z19, Z0, Z0                      // half=64 t=0: a = a + w*b
	VMOVUPS 64(R10), Z18                    // stage half=64 t=1: twiddle[8..15]
	VMOVSLDUP Z18, Z16                      // stage half=64 t=1 w: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=64 t=1 w: w.im -> both halves
	VSHUFPS $0xb1, Z9, Z9, Z19              // half=64 t=1: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=64 t=1: w.im*swap(b)
	VFMSUBADD231PS Z16, Z9, Z19             // half=64 t=1: conj(w)*b
	VSUBPS Z19, Z8, Z9                      // half=64 t=1: b = a - w*b
	VADDPS Z19, Z8, Z8                      // half=64 t=1: a = a + w*b
	VMOVUPS 128(R10), Z18                   // stage half=64 t=2: twiddle[16..23]
	VMOVSLDUP Z18, Z16                      // stage half=64 t=2 w: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=64 t=2 w: w.im -> both halves
	VSHUFPS $0xb1, Z5, Z5, Z19              // half=64 t=2: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=64 t=2: w.im*swap(b)
	VFMSUBADD231PS Z16, Z5, Z19             // half=64 t=2: conj(w)*b
	VSUBPS Z19, Z4, Z5                      // half=64 t=2: b = a - w*b
	VADDPS Z19, Z4, Z4                      // half=64 t=2: a = a + w*b
	VMOVUPS 192(R10), Z18                   // stage half=64 t=3: twiddle[24..31]
	VMOVSLDUP Z18, Z16                      // stage half=64 t=3 w: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=64 t=3 w: w.im -> both halves
	VSHUFPS $0xb1, Z13, Z13, Z19            // half=64 t=3: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=64 t=3: w.im*swap(b)
	VFMSUBADD231PS Z16, Z13, Z19            // half=64 t=3: conj(w)*b
	VSUBPS Z19, Z12, Z13                    // half=64 t=3: b = a - w*b
	VADDPS Z19, Z12, Z12                    // half=64 t=3: a = a + w*b
	VMOVUPS 256(R10), Z18                   // stage half=64 t=4: twiddle[32..39]
	VMOVSLDUP Z18, Z16                      // stage half=64 t=4 w: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=64 t=4 w: w.im -> both halves
	VSHUFPS $0xb1, Z3, Z3, Z19              // half=64 t=4: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=64 t=4: w.im*swap(b)
	VFMSUBADD231PS Z16, Z3, Z19             // half=64 t=4: conj(w)*b
	VSUBPS Z19, Z2, Z3                      // half=64 t=4: b = a - w*b
	VADDPS Z19, Z2, Z2                      // half=64 t=4: a = a + w*b
	VMOVUPS 320(R10), Z18                   // stage half=64 t=5: twiddle[40..47]
	VMOVSLDUP Z18, Z16                      // stage half=64 t=5 w: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=64 t=5 w: w.im -> both halves
	VSHUFPS $0xb1, Z11, Z11, Z19            // half=64 t=5: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=64 t=5: w.im*swap(b)
	VFMSUBADD231PS Z16, Z11, Z19            // half=64 t=5: conj(w)*b
	VSUBPS Z19, Z10, Z11                    // half=64 t=5: b = a - w*b
	VADDPS Z19, Z10, Z10                    // half=64 t=5: a = a + w*b
	VMOVUPS 384(R10), Z18                   // stage half=64 t=6: twiddle[48..55]
	VMOVSLDUP Z18, Z16                      // stage half=64 t=6 w: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=64 t=6 w: w.im -> both halves
	VSHUFPS $0xb1, Z7, Z7, Z19              // half=64 t=6: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=64 t=6: w.im*swap(b)
	VFMSUBADD231PS Z16, Z7, Z19             // half=64 t=6: conj(w)*b
	VSUBPS Z19, Z6, Z7                      // half=64 t=6: b = a - w*b
	VADDPS Z19, Z6, Z6                      // half=64 t=6: a = a + w*b
	VMOVUPS 448(R10), Z18                   // stage half=64 t=7: twiddle[56..63]
	VMOVSLDUP Z18, Z16                      // stage half=64 t=7 w: w.re -> both halves
	VMOVSHDUP Z18, Z17                      // stage half=64 t=7 w: w.im -> both halves
	VSHUFPS $0xb1, Z15, Z15, Z19            // half=64 t=7: swap re/im of b
	VMULPS Z17, Z19, Z19                    // half=64 t=7: w.im*swap(b)
	VFMSUBADD231PS Z16, Z15, Z19            // half=64 t=7: conj(w)*b
	VSUBPS Z19, Z14, Z15                    // half=64 t=7: b = a - w*b
	VADDPS Z19, Z14, Z14                    // half=64 t=7: a = a + w*b
	VBROADCASTSS ·oneTwentyEighth32(SB), Z16 // 1/128
	VMULPS Z16, Z0, Z0                      // inverse scaling
	VMULPS Z16, Z1, Z1                      // inverse scaling
	VMULPS Z16, Z2, Z2                      // inverse scaling
	VMULPS Z16, Z3, Z3                      // inverse scaling
	VMULPS Z16, Z4, Z4                      // inverse scaling
	VMULPS Z16, Z5, Z5                      // inverse scaling
	VMULPS Z16, Z6, Z6                      // inverse scaling
	VMULPS Z16, Z7, Z7                      // inverse scaling
	VMULPS Z16, Z8, Z8                      // inverse scaling
	VMULPS Z16, Z9, Z9                      // inverse scaling
	VMULPS Z16, Z10, Z10                    // inverse scaling
	VMULPS Z16, Z11, Z11                    // inverse scaling
	VMULPS Z16, Z12, Z12                    // inverse scaling
	VMULPS Z16, Z13, Z13                    // inverse scaling
	VMULPS Z16, Z14, Z14                    // inverse scaling
	VMULPS Z16, Z15, Z15                    // inverse scaling
	VMOVUPS Z0, (R8)                        // dst[0..7]
	VMOVUPS Z8, 64(R8)                      // dst[8..15]
	VMOVUPS Z4, 128(R8)                     // dst[16..23]
	VMOVUPS Z12, 192(R8)                    // dst[24..31]
	VMOVUPS Z2, 256(R8)                     // dst[32..39]
	VMOVUPS Z10, 320(R8)                    // dst[40..47]
	VMOVUPS Z6, 384(R8)                     // dst[48..55]
	VMOVUPS Z14, 448(R8)                    // dst[56..63]
	VMOVUPS Z1, 512(R8)                     // dst[64..71]
	VMOVUPS Z9, 576(R8)                     // dst[72..79]
	VMOVUPS Z5, 640(R8)                     // dst[80..87]
	VMOVUPS Z13, 704(R8)                    // dst[88..95]
	VMOVUPS Z3, 768(R8)                     // dst[96..103]
	VMOVUPS Z11, 832(R8)                    // dst[104..111]
	VMOVUPS Z7, 896(R8)                     // dst[112..119]
	VMOVUPS Z15, 960(R8)                    // dst[120..127]

	VZEROUPPER
	MOVB $1, ret+96(FP)
	RET

inv128_false:
	VZEROUPPER
	MOVB $0, ret+96(FP)
	RET
