// Code generated by cmd/gencodelets; DO NOT EDIT.
// Source of truth: cmd/gencodelets/specs.go

//go:build amd64 && !purego

package kernels

import (
	amd64 "github.com/cwbudde/algo-fft/internal/asm/amd64"
	"github.com/cwbudde/algo-fft/internal/fftypes"
	"github.com/cwbudde/algo-fft/internal/registry"
)

// registerAVX2DITCodelets64 registers the AVX2 complex64 DIT codelets.
func registerAVX2DITCodelets64() {
	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       4,
		Forward:    amd64.ForwardAVX2Size4Radix4Complex64Asm,
		Inverse:    amd64.InverseAVX2Size4Radix4Complex64Asm,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDAVX2,
		Signature:  "dit4_radix4_avx2",
		Priority:   5,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       8,
		Forward:    amd64.ForwardAVX2Size8Radix2Complex64Asm,
		Inverse:    amd64.InverseAVX2Size8Radix2Complex64Asm,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDAVX2,
		Signature:  "dit8_radix2_avx2",
		Priority:   12,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       8,
		Forward:    amd64.ForwardAVX2Size8Radix4Complex64Asm,
		Inverse:    amd64.InverseAVX2Size8Radix4Complex64Asm,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDAVX2,
		Signature:  "dit8_radix4_avx2",
		Priority:   10,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       8,
		Forward:    amd64.ForwardAVX2Size8Radix8Complex64Asm,
		Inverse:    amd64.InverseAVX2Size8Radix8Complex64Asm,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDAVX2,
		Signature:  "dit8_radix8_avx2",
		Priority:   11,
		KernelType: fftypes.KernelTypeCore,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       16,
		Forward:    amd64.ForwardAVX2Size16Radix2Complex64Asm,
		Inverse:    amd64.InverseAVX2Size16Radix2Complex64Asm,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDAVX2,
		Signature:  "dit16_radix2_avx2",
		Priority:   55,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       16,
		Forward:    amd64.ForwardAVX2Size16Radix16Complex64Asm,
		Inverse:    amd64.InverseAVX2Size16Radix16Complex64Asm,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDAVX2,
		Signature:  "dit16_radix16_avx2",
		Priority:   50,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       32,
		Forward:    amd64.ForwardAVX2Size32Radix32Complex64Asm,
		Inverse:    amd64.InverseAVX2Size32Radix32Complex64Asm,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDAVX2,
		Signature:  "dit32_radix32_avx2",
		Priority:   25,
		KernelType: fftypes.KernelTypeCore,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       32,
		Forward:    amd64.ForwardAVX2Size32Radix2Complex64Asm,
		Inverse:    amd64.InverseAVX2Size32Radix2Complex64Asm,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDAVX2,
		Signature:  "dit32_radix2_avx2",
		Priority:   30,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       64,
		Forward:    amd64.ForwardAVX2Size64Radix2Complex64Asm,
		Inverse:    amd64.InverseAVX2Size64Radix2Complex64Asm,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDAVX2,
		Signature:  "dit64_radix2_avx2",
		Priority:   26,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       384,
		Forward:    forwardDIT384MixedComplex64,
		Inverse:    inverseDIT384MixedComplex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDAVX2,
		Signature:  "dit384_mixed_avx2",
		Priority:   25,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:           256,
		Forward:        forwardRadix4AVX2Complex64,
		Inverse:        inverseRadix4AVX2Complex64,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit256_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2,
		PrepareTwiddle: prepareTwiddleRadix4AVX2,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:           1024,
		Forward:        forwardRadix4AVX2Complex64,
		Inverse:        inverseRadix4AVX2Complex64,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit1024_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2,
		PrepareTwiddle: prepareTwiddleRadix4AVX2,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:           4096,
		Forward:        forwardRadix4AVX2Complex64,
		Inverse:        inverseRadix4AVX2Complex64,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit4096_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2,
		PrepareTwiddle: prepareTwiddleRadix4AVX2,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:           16384,
		Forward:        forwardRadix4AVX2Complex64,
		Inverse:        inverseRadix4AVX2Complex64,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit16384_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2,
		PrepareTwiddle: prepareTwiddleRadix4AVX2,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:           128,
		Forward:        forwardRadix4AVX2FusedComplex64,
		Inverse:        inverseRadix4AVX2FusedComplex64,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit128_radix4fused_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2,
		PrepareTwiddle: prepareTwiddleRadix4AVX2,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:           512,
		Forward:        forwardRadix4AVX2Complex64,
		Inverse:        inverseRadix4AVX2Complex64,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit512_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2,
		PrepareTwiddle: prepareTwiddleRadix4AVX2,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:           2048,
		Forward:        forwardRadix4AVX2FusedComplex64,
		Inverse:        inverseRadix4AVX2FusedComplex64,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit2048_radix4fused_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2,
		PrepareTwiddle: prepareTwiddleRadix4AVX2,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:           8192,
		Forward:        forwardRadix4AVX2Complex64,
		Inverse:        inverseRadix4AVX2Complex64,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit8192_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2,
		PrepareTwiddle: prepareTwiddleRadix4AVX2,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:           32768,
		Forward:        forwardRadix4AVX2Complex64,
		Inverse:        inverseRadix4AVX2Complex64,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit32768_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2,
		PrepareTwiddle: prepareTwiddleRadix4AVX2,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:           65536,
		Forward:        forwardRadix4AVX2Complex64,
		Inverse:        inverseRadix4AVX2Complex64,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit65536_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2,
		PrepareTwiddle: prepareTwiddleRadix4AVX2,
	})
}

// registerAVX2DITCodelets128 registers the AVX2 complex128 DIT codelets.
func registerAVX2DITCodelets128() {
	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       384,
		Forward:    forwardDIT384MixedComplex128,
		Inverse:    inverseDIT384MixedComplex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDAVX2,
		Signature:  "dit384_mixed_avx2",
		Priority:   25,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       4,
		Forward:    forwardDIT4Radix4Complex128,
		Inverse:    inverseDIT4Radix4Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDAVX2,
		Signature:  "dit4_radix4_avx2",
		Priority:   5,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       8,
		Forward:    amd64.ForwardAVX2Size8Radix8Complex128Asm,
		Inverse:    amd64.InverseAVX2Size8Radix8Complex128Asm,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDAVX2,
		Signature:  "dit8_radix8_avx2",
		Priority:   35,
		KernelType: fftypes.KernelTypeCore,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       8,
		Forward:    amd64.ForwardAVX2Size8Radix2Complex128Asm,
		Inverse:    amd64.InverseAVX2Size8Radix2Complex128Asm,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDAVX2,
		Signature:  "dit8_radix2_avx2",
		Priority:   25,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       8,
		Forward:    amd64.ForwardAVX2Size8Radix4Complex128Asm,
		Inverse:    amd64.InverseAVX2Size8Radix4Complex128Asm,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDAVX2,
		Signature:  "dit8_radix4_avx2",
		Priority:   30,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           16,
		Forward:        forwardRadix4AVX2Complex128,
		Inverse:        inverseRadix4AVX2Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit16_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2Complex128,
		PrepareTwiddle: prepareTwiddleRadix4AVX2Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           32,
		Forward:        forwardRadix4AVX2Complex128,
		Inverse:        inverseRadix4AVX2Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit32_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2Complex128,
		PrepareTwiddle: prepareTwiddleRadix4AVX2Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           64,
		Forward:        forwardRadix4AVX2Complex128,
		Inverse:        inverseRadix4AVX2Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit64_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2Complex128,
		PrepareTwiddle: prepareTwiddleRadix4AVX2Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           128,
		Forward:        forwardRadix4AVX2FusedComplex128,
		Inverse:        inverseRadix4AVX2FusedComplex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit128_radix4fused_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2Complex128,
		PrepareTwiddle: prepareTwiddleRadix4AVX2Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           256,
		Forward:        forwardRadix4AVX2Complex128,
		Inverse:        inverseRadix4AVX2Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit256_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2Complex128,
		PrepareTwiddle: prepareTwiddleRadix4AVX2Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           512,
		Forward:        forwardRadix4AVX2Complex128,
		Inverse:        inverseRadix4AVX2Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit512_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2Complex128,
		PrepareTwiddle: prepareTwiddleRadix4AVX2Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           1024,
		Forward:        forwardRadix4AVX2Complex128,
		Inverse:        inverseRadix4AVX2Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit1024_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2Complex128,
		PrepareTwiddle: prepareTwiddleRadix4AVX2Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           2048,
		Forward:        forwardRadix4AVX2Complex128,
		Inverse:        inverseRadix4AVX2Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit2048_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2Complex128,
		PrepareTwiddle: prepareTwiddleRadix4AVX2Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           4096,
		Forward:        forwardRadix4AVX2Complex128,
		Inverse:        inverseRadix4AVX2Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit4096_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2Complex128,
		PrepareTwiddle: prepareTwiddleRadix4AVX2Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           8192,
		Forward:        forwardRadix4AVX2Complex128,
		Inverse:        inverseRadix4AVX2Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit8192_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2Complex128,
		PrepareTwiddle: prepareTwiddleRadix4AVX2Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           16384,
		Forward:        forwardRadix4AVX2Complex128,
		Inverse:        inverseRadix4AVX2Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit16384_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2Complex128,
		PrepareTwiddle: prepareTwiddleRadix4AVX2Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           32768,
		Forward:        forwardRadix4AVX2Complex128,
		Inverse:        inverseRadix4AVX2Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit32768_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2Complex128,
		PrepareTwiddle: prepareTwiddleRadix4AVX2Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           65536,
		Forward:        forwardRadix4AVX2Complex128,
		Inverse:        inverseRadix4AVX2Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDAVX2,
		Signature:      "dit65536_radix4_avx2",
		Priority:       90,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix4AVX2Complex128,
		PrepareTwiddle: prepareTwiddleRadix4AVX2Complex128,
	})
}
