// Code generated by cmd/gencodelets; DO NOT EDIT.
// Source of truth: cmd/gencodelets/specs.go

//go:build amd64 && !purego

package kernels

import amd64 "github.com/cwbudde/algo-fft/internal/asm/amd64"

// registerSSE2DITCodelets64 registers the SSE2 complex64 DIT codelets.
func registerSSE2DITCodelets64() {
	Registry64.Register(CodeletEntry[complex64]{
		Size:       4,
		Forward:    wrapCodelet64(amd64.ForwardSSE2Size4Radix4Complex64Asm),
		Inverse:    wrapCodelet64(amd64.InverseSSE2Size4Radix4Complex64Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE2,
		Signature:  "dit4_radix4_sse2",
		Priority:   5,
		KernelType: KernelTypeDIT,
	})

	Registry64.Register(CodeletEntry[complex64]{
		Size:       8,
		Forward:    wrapCodelet64(amd64.ForwardSSE3Size8Radix2Complex64Asm),
		Inverse:    wrapCodelet64(amd64.InverseSSE3Size8Radix2Complex64Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE3,
		Signature:  "dit8_radix2_sse3",
		Priority:   18,
		KernelType: KernelTypeDIT,
	})

	Registry64.Register(CodeletEntry[complex64]{
		Size:       8,
		Forward:    wrapCodelet64(amd64.ForwardSSE3Size8Radix8Complex64Asm),
		Inverse:    wrapCodelet64(amd64.InverseSSE3Size8Radix8Complex64Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE3,
		Signature:  "dit8_radix8_sse3",
		Priority:   30,
		KernelType: KernelTypeCore,
	})

	Registry64.Register(CodeletEntry[complex64]{
		Size:       16,
		Forward:    wrapCodelet64(amd64.ForwardSSE3Size16Radix16Complex64Asm),
		Inverse:    wrapCodelet64(amd64.InverseSSE3Size16Radix16Complex64Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE3,
		Signature:  "dit16_radix16_sse3",
		Priority:   40,
		KernelType: KernelTypeDIT,
	})

	Registry64.Register(CodeletEntry[complex64]{
		Size:       16,
		Forward:    wrapCodelet64(amd64.ForwardSSE3Size16Radix2Complex64Asm),
		Inverse:    wrapCodelet64(amd64.InverseSSE3Size16Radix2Complex64Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE3,
		Signature:  "dit16_radix2_sse3",
		Priority:   17,
		KernelType: KernelTypeDIT,
	})

	Registry64.Register(CodeletEntry[complex64]{
		Size:       16,
		Forward:    wrapCodelet64(amd64.ForwardSSE3Size16Radix4Complex64Asm),
		Inverse:    wrapCodelet64(amd64.InverseSSE3Size16Radix4Complex64Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE3,
		Signature:  "dit16_radix4_sse3",
		Priority:   18,
		KernelType: KernelTypeDIT,
	})

	Registry64.Register(CodeletEntry[complex64]{
		Size:       32,
		Forward:    wrapCodelet64(amd64.ForwardSSE3Size32Radix2Complex64Asm),
		Inverse:    wrapCodelet64(amd64.InverseSSE3Size32Radix2Complex64Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE3,
		Signature:  "dit32_radix2_sse3",
		Priority:   17,
		KernelType: KernelTypeDIT,
	})

	Registry64.Register(CodeletEntry[complex64]{
		Size:       32,
		Forward:    wrapCodelet64(amd64.ForwardSSE3Size32Radix4Then2Complex64Asm),
		Inverse:    wrapCodelet64(amd64.InverseSSE3Size32Radix4Then2Complex64Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE3,
		Signature:  "dit32_radix4_then2_sse3",
		Priority:   19,
		KernelType: KernelTypeDIT,
	})

	Registry64.Register(CodeletEntry[complex64]{
		Size:       64,
		Forward:    wrapCodelet64(amd64.ForwardSSE3Size64Radix4Complex64Asm),
		Inverse:    wrapCodelet64(amd64.InverseSSE3Size64Radix4Complex64Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE3,
		Signature:  "dit64_radix4_sse3",
		Priority:   18,
		KernelType: KernelTypeDIT,
	})

	Registry64.Register(CodeletEntry[complex64]{
		Size:       64,
		Forward:    wrapCodelet64(amd64.ForwardSSE3Size64Radix2Complex64Asm),
		Inverse:    wrapCodelet64(amd64.InverseSSE3Size64Radix2Complex64Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE3,
		Signature:  "dit64_radix2_sse3",
		Priority:   17,
		KernelType: KernelTypeDIT,
	})

	Registry64.Register(CodeletEntry[complex64]{
		Size:       128,
		Forward:    wrapCodelet64(amd64.ForwardSSE3Size128Radix4Then2Complex64Asm),
		Inverse:    wrapCodelet64(amd64.InverseSSE3Size128Radix4Then2Complex64Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE3,
		Signature:  "dit128_radix4_then2_sse3",
		Priority:   17,
		KernelType: KernelTypeDIT,
	})

	Registry64.Register(CodeletEntry[complex64]{
		Size:       128,
		Forward:    wrapCodelet64(amd64.ForwardSSE3Size128Radix2Complex64Asm),
		Inverse:    wrapCodelet64(amd64.InverseSSE3Size128Radix2Complex64Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE3,
		Signature:  "dit128_radix2_sse3",
		Priority:   17,
		KernelType: KernelTypeDIT,
	})

	Registry64.Register(CodeletEntry[complex64]{
		Size:       512,
		Forward:    wrapCodelet64(amd64.ForwardSSE3Size512Radix2Complex64Asm),
		Inverse:    wrapCodelet64(amd64.InverseSSE3Size512Radix2Complex64Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE3,
		Signature:  "dit512_radix2_sse3",
		Priority:   10,
		KernelType: KernelTypeDIT,
	})
}

// registerSSE2DITCodelets128 registers the SSE2 complex128 DIT codelets.
func registerSSE2DITCodelets128() {
	Registry128.Register(CodeletEntry[complex128]{
		Size:       4,
		Forward:    wrapCodelet128(amd64.ForwardSSE2Size4Radix4Complex128Asm),
		Inverse:    wrapCodelet128(amd64.InverseSSE2Size4Radix4Complex128Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE2,
		Signature:  "dit4_radix4_sse2",
		Priority:   5,
		KernelType: KernelTypeDIT,
	})

	Registry128.Register(CodeletEntry[complex128]{
		Size:       8,
		Forward:    wrapCodelet128(amd64.ForwardSSE2Size8Radix2Complex128Asm),
		Inverse:    wrapCodelet128(amd64.InverseSSE2Size8Radix2Complex128Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE2,
		Signature:  "dit8_radix2_sse2",
		Priority:   17,
		KernelType: KernelTypeDIT,
	})

	Registry128.Register(CodeletEntry[complex128]{
		Size:       8,
		Forward:    wrapCodelet128(amd64.ForwardSSE2Size8Radix8Complex128Asm),
		Inverse:    wrapCodelet128(amd64.InverseSSE2Size8Radix8Complex128Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE2,
		Signature:  "dit8_radix8_sse2",
		Priority:   30,
		KernelType: KernelTypeCore,
	})

	Registry128.Register(CodeletEntry[complex128]{
		Size:       8,
		Forward:    wrapCodelet128(amd64.ForwardSSE2Size8Radix4Complex128Asm),
		Inverse:    wrapCodelet128(amd64.InverseSSE2Size8Radix4Complex128Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE2,
		Signature:  "dit8_radix4_sse2",
		Priority:   18,
		KernelType: KernelTypeDIT,
	})

	Registry128.Register(CodeletEntry[complex128]{
		Size:       16,
		Forward:    wrapCodelet128(amd64.ForwardSSE2Size16Radix2Complex128Asm),
		Inverse:    wrapCodelet128(amd64.InverseSSE2Size16Radix2Complex128Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE2,
		Signature:  "dit16_radix2_sse2",
		Priority:   17,
		KernelType: KernelTypeDIT,
	})

	Registry128.Register(CodeletEntry[complex128]{
		Size:       16,
		Forward:    wrapCodelet128(amd64.ForwardSSE2Size16Radix4Complex128Asm),
		Inverse:    wrapCodelet128(amd64.InverseSSE2Size16Radix4Complex128Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE2,
		Signature:  "dit16_radix4_sse2",
		Priority:   18,
		KernelType: KernelTypeDIT,
	})

	Registry128.Register(CodeletEntry[complex128]{
		Size:       32,
		Forward:    wrapCodelet128(amd64.ForwardSSE2Size32Radix2Complex128Asm),
		Inverse:    wrapCodelet128(amd64.InverseSSE2Size32Radix2Complex128Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE2,
		Signature:  "dit32_radix2_sse2",
		Priority:   17,
		KernelType: KernelTypeDIT,
	})

	Registry128.Register(CodeletEntry[complex128]{
		Size:       32,
		Forward:    wrapCodelet128(amd64.ForwardSSE2Size32Radix4Then2Complex128Asm),
		Inverse:    wrapCodelet128(amd64.InverseSSE2Size32Radix4Then2Complex128Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE2,
		Signature:  "dit32_radix4_then2_sse2",
		Priority:   19,
		KernelType: KernelTypeDIT,
	})

	Registry128.Register(CodeletEntry[complex128]{
		Size:       64,
		Forward:    wrapCodelet128(amd64.ForwardSSE2Size64Radix2Complex128Asm),
		Inverse:    wrapCodelet128(amd64.InverseSSE2Size64Radix2Complex128Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE2,
		Signature:  "dit64_radix2_sse2",
		Priority:   18,
		KernelType: KernelTypeDIT,
	})

	Registry128.Register(CodeletEntry[complex128]{
		Size:       64,
		Forward:    wrapCodelet128(amd64.ForwardSSE2Size64Radix4Complex128Asm),
		Inverse:    wrapCodelet128(amd64.InverseSSE2Size64Radix4Complex128Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE2,
		Signature:  "dit64_radix4_sse2",
		Priority:   18,
		KernelType: KernelTypeDIT,
	})

	Registry128.Register(CodeletEntry[complex128]{
		Size:       128,
		Forward:    wrapCodelet128(amd64.ForwardSSE2Size128Radix2Complex128Asm),
		Inverse:    wrapCodelet128(amd64.InverseSSE2Size128Radix2Complex128Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE2,
		Signature:  "dit128_radix2_sse2",
		Priority:   17,
		KernelType: KernelTypeDIT,
	})

	Registry128.Register(CodeletEntry[complex128]{
		Size:       128,
		Forward:    wrapCodelet128(amd64.ForwardSSE2Size128Radix4Then2Complex128Asm),
		Inverse:    wrapCodelet128(amd64.InverseSSE2Size128Radix4Then2Complex128Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE2,
		Signature:  "dit128_radix4_then2_sse2",
		Priority:   18,
		KernelType: KernelTypeDIT,
	})

	Registry128.Register(CodeletEntry[complex128]{
		Size:       256,
		Forward:    wrapCodelet128(amd64.ForwardSSE2Size256Radix2Complex128Asm),
		Inverse:    wrapCodelet128(amd64.InverseSSE2Size256Radix2Complex128Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE2,
		Signature:  "dit256_radix2_sse2",
		Priority:   12,
		KernelType: KernelTypeDIT,
	})

	Registry128.Register(CodeletEntry[complex128]{
		Size:       256,
		Forward:    wrapCodelet128(amd64.ForwardSSE2Size256Radix4Complex128Asm),
		Inverse:    wrapCodelet128(amd64.InverseSSE2Size256Radix4Complex128Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE2,
		Signature:  "dit256_radix4_sse2",
		Priority:   18,
		KernelType: KernelTypeDIT,
	})

	Registry128.Register(CodeletEntry[complex128]{
		Size:       512,
		Forward:    wrapCodelet128(amd64.ForwardSSE2Size512Radix2Complex128Asm),
		Inverse:    wrapCodelet128(amd64.InverseSSE2Size512Radix2Complex128Asm),
		Algorithm:  KernelDIT,
		SIMDLevel:  SIMDSSE2,
		Signature:  "dit512_radix2_sse2",
		Priority:   10,
		KernelType: KernelTypeDIT,
	})
}
