// Code generated by cmd/gencodelets; DO NOT EDIT.
// Source of truth: cmd/gencodelets/specs.go

package kernels

import (
	"github.com/cwbudde/algo-fft/internal/fftypes"
	"github.com/cwbudde/algo-fft/internal/registry"
)

// registerDITCodelets64 registers the generic complex64 DIT codelets.
func registerDITCodelets64() {
	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       4,
		Forward:    forwardDIT4Radix4Complex64,
		Inverse:    inverseDIT4Radix4Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit4_radix4_generic",
		Priority:   0,
		KernelType: fftypes.KernelTypeCore,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       8,
		Forward:    forwardDIT8Radix2Complex64,
		Inverse:    inverseDIT8Radix2Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit8_radix2_generic",
		Priority:   20,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       8,
		Forward:    forwardDIT8Radix8Complex64,
		Inverse:    inverseDIT8Radix8Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit8_radix8_generic",
		Priority:   30,
		KernelType: fftypes.KernelTypeCore,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       8,
		Forward:    forwardDIT8Radix4Complex64,
		Inverse:    inverseDIT8Radix4Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit8_mixedradix_generic",
		Priority:   25,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       16,
		Forward:    forwardDIT16Radix2Complex64,
		Inverse:    inverseDIT16Radix2Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit16_radix2_generic",
		Priority:   10,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       16,
		Forward:    forwardDIT16Radix4Complex64,
		Inverse:    inverseDIT16Radix4Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit16_radix4_generic",
		Priority:   20,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       16,
		Forward:    forwardDIT16Radix16Complex64,
		Inverse:    inverseDIT16Radix16Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit16_radix16_generic",
		Priority:   30,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       32,
		Forward:    forwardDIT32Radix2Complex64,
		Inverse:    inverseDIT32Radix2Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit32_radix2_generic",
		Priority:   0,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       32,
		Forward:    forwardDIT32Radix4Then2Complex64,
		Inverse:    inverseDIT32Radix4Then2Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit32_radix4_then2_generic",
		Priority:   10,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       32,
		Forward:    forwardDIT32Radix32Complex64,
		Inverse:    inverseDIT32Radix32Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit32_radix32_generic",
		Priority:   5,
		KernelType: fftypes.KernelTypeCore,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       64,
		Forward:    forwardDIT64Radix2Complex64,
		Inverse:    inverseDIT64Radix2Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit64_radix2_generic",
		Priority:   0,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       64,
		Forward:    forwardDIT64Radix4Complex64,
		Inverse:    inverseDIT64Radix4Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit64_radix4_generic",
		Priority:   20,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       128,
		Forward:    forwardDIT128Radix2Complex64,
		Inverse:    inverseDIT128Radix2Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit128_radix2_generic",
		Priority:   0,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       128,
		Forward:    forwardDIT128Radix4Then2Complex64,
		Inverse:    inverseDIT128Radix4Then2Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit128_radix4_then2_generic",
		Priority:   15,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       256,
		Forward:    forwardDIT256Complex64,
		Inverse:    inverseDIT256Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit256_radix2_generic",
		Priority:   10,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       256,
		Forward:    forwardDIT256Radix4Complex64,
		Inverse:    inverseDIT256Radix4Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit256_radix4_generic",
		Priority:   20,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:           256,
		Forward:        forwardRadix8Complex64,
		Inverse:        inverseRadix8Complex64,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDNone,
		Signature:      "dit256_radix8ladder_generic",
		Priority:       50,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix8,
		PrepareTwiddle: prepareTwiddleRadix8Complex64,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       384,
		Forward:    forwardDIT384MixedComplex64,
		Inverse:    inverseDIT384MixedComplex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit384_mixed_generic",
		Priority:   20,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       512,
		Forward:    forwardDIT512Complex64,
		Inverse:    inverseDIT512Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit512_radix2_generic",
		Priority:   10,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       512,
		Forward:    forwardDIT512Radix8Complex64,
		Inverse:    inverseDIT512Radix8Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit512_radix8_generic",
		Priority:   30,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       512,
		Forward:    forwardDIT512Radix4Then2Complex64,
		Inverse:    inverseDIT512Radix4Then2Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit512_radix4_then2_generic",
		Priority:   45,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       512,
		Forward:    forwardDIT512Mixed16x32Complex64,
		Inverse:    inverseDIT512Mixed16x32Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit512_radix16x32_generic",
		Priority:   35,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:           512,
		Forward:        forwardRadix8Complex64,
		Inverse:        inverseRadix8Complex64,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDNone,
		Signature:      "dit512_radix8ladder_generic",
		Priority:       50,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix8,
		PrepareTwiddle: prepareTwiddleRadix8Complex64,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       1024,
		Forward:    forwardDIT1024Radix4Complex64,
		Inverse:    inverseDIT1024Radix4Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit1024_radix4_generic",
		Priority:   30,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       1024,
		Forward:    forwardDIT1024Mixed32x32Complex64,
		Inverse:    inverseDIT1024Mixed32x32Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit1024_radix32x32_generic",
		Priority:   25,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:           1024,
		Forward:        forwardRadix8Complex64,
		Inverse:        inverseRadix8Complex64,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDNone,
		Signature:      "dit1024_radix8ladder_generic",
		Priority:       50,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix8,
		PrepareTwiddle: prepareTwiddleRadix8Complex64,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       2048,
		Forward:    forwardDIT2048Radix4Then2Complex64,
		Inverse:    inverseDIT2048Radix4Then2Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit2048_radix4_then2_generic",
		Priority:   20,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:           2048,
		Forward:        forwardRadix8Complex64,
		Inverse:        inverseRadix8Complex64,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDNone,
		Signature:      "dit2048_radix8ladder_generic",
		Priority:       50,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix8,
		PrepareTwiddle: prepareTwiddleRadix8Complex64,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       4096,
		Forward:    forwardDIT4096Radix4Complex64,
		Inverse:    inverseDIT4096Radix4Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit4096_radix4_generic",
		Priority:   30,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:           4096,
		Forward:        forwardRadix8Complex64,
		Inverse:        inverseRadix8Complex64,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDNone,
		Signature:      "dit4096_radix8ladder_generic",
		Priority:       50,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix8,
		PrepareTwiddle: prepareTwiddleRadix8Complex64,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       8192,
		Forward:    forwardDIT8192Radix4Then2Complex64,
		Inverse:    inverseDIT8192Radix4Then2Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit8192_radix4_then2_generic",
		Priority:   35,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:           8192,
		Forward:        forwardRadix8Complex64,
		Inverse:        inverseRadix8Complex64,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDNone,
		Signature:      "dit8192_radix8ladder_generic",
		Priority:       50,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix8,
		PrepareTwiddle: prepareTwiddleRadix8Complex64,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       16384,
		Forward:    forwardDIT16384Radix4Complex64,
		Inverse:    inverseDIT16384Radix4Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit16384_radix4_generic",
		Priority:   30,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:           16384,
		Forward:        forwardRadix8Complex64,
		Inverse:        inverseRadix8Complex64,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDNone,
		Signature:      "dit16384_radix8ladder_generic",
		Priority:       50,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix8,
		PrepareTwiddle: prepareTwiddleRadix8Complex64,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       32768,
		Forward:    forwardDIT32768Radix4Then2Complex64,
		Inverse:    inverseDIT32768Radix4Then2Complex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit32768_radix4_then2_generic",
		Priority:   20,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       256,
		Forward:    ForwardSplitRadixComplex64,
		Inverse:    InverseSplitRadixComplex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit256_splitradix_generic",
		Priority:   1,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       512,
		Forward:    ForwardSplitRadixComplex64,
		Inverse:    InverseSplitRadixComplex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit512_splitradix_generic",
		Priority:   1,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       1024,
		Forward:    ForwardSplitRadixComplex64,
		Inverse:    InverseSplitRadixComplex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit1024_splitradix_generic",
		Priority:   1,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       2048,
		Forward:    ForwardSplitRadixComplex64,
		Inverse:    InverseSplitRadixComplex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit2048_splitradix_generic",
		Priority:   1,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       4096,
		Forward:    ForwardSplitRadixComplex64,
		Inverse:    InverseSplitRadixComplex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit4096_splitradix_generic",
		Priority:   1,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       8192,
		Forward:    ForwardSplitRadixComplex64,
		Inverse:    InverseSplitRadixComplex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit8192_splitradix_generic",
		Priority:   1,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       16384,
		Forward:    ForwardSplitRadixComplex64,
		Inverse:    InverseSplitRadixComplex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit16384_splitradix_generic",
		Priority:   1,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry64.Register(registry.CodeletEntry[complex64]{
		Size:       32768,
		Forward:    ForwardSplitRadixComplex64,
		Inverse:    InverseSplitRadixComplex64,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit32768_splitradix_generic",
		Priority:   1,
		KernelType: fftypes.KernelTypeDIT,
	})
}

// registerDITCodelets128 registers the generic complex128 DIT codelets.
func registerDITCodelets128() {
	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       4,
		Forward:    forwardDIT4Radix4Complex128,
		Inverse:    inverseDIT4Radix4Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit4_radix4_generic",
		Priority:   0,
		KernelType: fftypes.KernelTypeCore,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       8,
		Forward:    forwardDIT8Radix2Complex128,
		Inverse:    inverseDIT8Radix2Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit8_radix2_generic",
		Priority:   20,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       8,
		Forward:    forwardDIT8Radix8Complex128,
		Inverse:    inverseDIT8Radix8Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit8_radix8_generic",
		Priority:   30,
		KernelType: fftypes.KernelTypeCore,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       8,
		Forward:    forwardDIT8Radix4Complex128,
		Inverse:    inverseDIT8Radix4Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit8_mixedradix_generic",
		Priority:   25,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       16,
		Forward:    forwardDIT16Radix2Complex128,
		Inverse:    inverseDIT16Radix2Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit16_radix2_generic",
		Priority:   10,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       16,
		Forward:    forwardDIT16Radix4Complex128,
		Inverse:    inverseDIT16Radix4Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit16_radix4_generic",
		Priority:   20,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       16,
		Forward:    forwardDIT16Radix16Complex128,
		Inverse:    inverseDIT16Radix16Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit16_radix16_generic",
		Priority:   30,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       32,
		Forward:    forwardDIT32Radix2Complex128,
		Inverse:    inverseDIT32Radix2Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit32_radix2_generic",
		Priority:   0,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       32,
		Forward:    forwardDIT32Radix4Then2Complex128,
		Inverse:    inverseDIT32Radix4Then2Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit32_radix4_then2_generic",
		Priority:   15,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       32,
		Forward:    forwardDIT32Radix32Complex128,
		Inverse:    inverseDIT32Radix32Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit32_radix32_generic",
		Priority:   5,
		KernelType: fftypes.KernelTypeCore,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       64,
		Forward:    forwardDIT64Radix2Complex128,
		Inverse:    inverseDIT64Radix2Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit64_radix2_generic",
		Priority:   0,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       64,
		Forward:    forwardDIT64Radix4Complex128,
		Inverse:    inverseDIT64Radix4Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit64_radix4_generic",
		Priority:   20,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       128,
		Forward:    forwardDIT128Radix2Complex128,
		Inverse:    inverseDIT128Radix2Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit128_radix2_generic",
		Priority:   0,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       128,
		Forward:    forwardDIT128Radix4Then2Complex128,
		Inverse:    inverseDIT128Radix4Then2Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit128_radix4_then2_generic",
		Priority:   15,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       256,
		Forward:    forwardDIT256Complex128,
		Inverse:    inverseDIT256Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit256_radix2_generic",
		Priority:   10,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       256,
		Forward:    forwardDIT256Radix4Complex128,
		Inverse:    inverseDIT256Radix4Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit256_radix4_generic",
		Priority:   20,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           256,
		Forward:        forwardRadix8Complex128,
		Inverse:        inverseRadix8Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDNone,
		Signature:      "dit256_radix8ladder_generic",
		Priority:       50,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix8,
		PrepareTwiddle: prepareTwiddleRadix8Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       384,
		Forward:    forwardDIT384MixedComplex128,
		Inverse:    inverseDIT384MixedComplex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit384_mixed_generic",
		Priority:   20,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       512,
		Forward:    forwardDIT512Complex128,
		Inverse:    inverseDIT512Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit512_radix2_generic",
		Priority:   10,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       512,
		Forward:    forwardDIT512Radix8Complex128,
		Inverse:    inverseDIT512Radix8Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit512_radix8_generic",
		Priority:   35,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       512,
		Forward:    forwardDIT512Radix4Then2Complex128,
		Inverse:    inverseDIT512Radix4Then2Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit512_radix4_then2_generic",
		Priority:   45,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       512,
		Forward:    forwardDIT512Mixed16x32Complex128,
		Inverse:    inverseDIT512Mixed16x32Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit512_radix16x32_generic",
		Priority:   30,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           512,
		Forward:        forwardRadix8Complex128,
		Inverse:        inverseRadix8Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDNone,
		Signature:      "dit512_radix8ladder_generic",
		Priority:       50,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix8,
		PrepareTwiddle: prepareTwiddleRadix8Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       1024,
		Forward:    forwardDIT1024Radix4Complex128,
		Inverse:    inverseDIT1024Radix4Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit1024_radix4_generic",
		Priority:   30,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       1024,
		Forward:    forwardDIT1024Mixed32x32Complex128,
		Inverse:    inverseDIT1024Mixed32x32Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit1024_radix32x32_generic",
		Priority:   25,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       2048,
		Forward:    forwardDIT2048Radix4Then2Complex128,
		Inverse:    inverseDIT2048Radix4Then2Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit2048_radix4_then2_generic",
		Priority:   20,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           2048,
		Forward:        forwardRadix8Complex128,
		Inverse:        inverseRadix8Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDNone,
		Signature:      "dit2048_radix8ladder_generic",
		Priority:       50,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix8,
		PrepareTwiddle: prepareTwiddleRadix8Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       4096,
		Forward:    forwardDIT4096Radix4Complex128,
		Inverse:    inverseDIT4096Radix4Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit4096_radix4_generic",
		Priority:   30,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           4096,
		Forward:        forwardRadix8Complex128,
		Inverse:        inverseRadix8Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDNone,
		Signature:      "dit4096_radix8ladder_generic",
		Priority:       50,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix8,
		PrepareTwiddle: prepareTwiddleRadix8Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       8192,
		Forward:    forwardDIT8192Radix4Then2Complex128,
		Inverse:    inverseDIT8192Radix4Then2Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit8192_radix4_then2_generic",
		Priority:   35,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           8192,
		Forward:        forwardRadix8Complex128,
		Inverse:        inverseRadix8Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDNone,
		Signature:      "dit8192_radix8ladder_generic",
		Priority:       50,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix8,
		PrepareTwiddle: prepareTwiddleRadix8Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       16384,
		Forward:    forwardDIT16384Radix4Complex128,
		Inverse:    inverseDIT16384Radix4Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit16384_radix4_generic",
		Priority:   30,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:           16384,
		Forward:        forwardRadix8Complex128,
		Inverse:        inverseRadix8Complex128,
		Algorithm:      fftypes.KernelDIT,
		SIMDLevel:      fftypes.SIMDNone,
		Signature:      "dit16384_radix8ladder_generic",
		Priority:       50,
		KernelType:     fftypes.KernelTypeDIT,
		TwiddleSize:    twiddleSizeRadix8,
		PrepareTwiddle: prepareTwiddleRadix8Complex128,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       32768,
		Forward:    forwardDIT32768Radix4Then2Complex128,
		Inverse:    inverseDIT32768Radix4Then2Complex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit32768_radix4_then2_generic",
		Priority:   20,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       256,
		Forward:    ForwardSplitRadixComplex128,
		Inverse:    InverseSplitRadixComplex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit256_splitradix_generic",
		Priority:   1,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       512,
		Forward:    ForwardSplitRadixComplex128,
		Inverse:    InverseSplitRadixComplex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit512_splitradix_generic",
		Priority:   1,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       1024,
		Forward:    ForwardSplitRadixComplex128,
		Inverse:    InverseSplitRadixComplex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit1024_splitradix_generic",
		Priority:   1,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       2048,
		Forward:    ForwardSplitRadixComplex128,
		Inverse:    InverseSplitRadixComplex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit2048_splitradix_generic",
		Priority:   1,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       4096,
		Forward:    ForwardSplitRadixComplex128,
		Inverse:    InverseSplitRadixComplex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit4096_splitradix_generic",
		Priority:   1,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       8192,
		Forward:    ForwardSplitRadixComplex128,
		Inverse:    InverseSplitRadixComplex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit8192_splitradix_generic",
		Priority:   1,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       16384,
		Forward:    ForwardSplitRadixComplex128,
		Inverse:    InverseSplitRadixComplex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit16384_splitradix_generic",
		Priority:   1,
		KernelType: fftypes.KernelTypeDIT,
	})

	registry.Registry128.Register(registry.CodeletEntry[complex128]{
		Size:       32768,
		Forward:    ForwardSplitRadixComplex128,
		Inverse:    InverseSplitRadixComplex128,
		Algorithm:  fftypes.KernelDIT,
		SIMDLevel:  fftypes.SIMDNone,
		Signature:  "dit32768_splitradix_generic",
		Priority:   1,
		KernelType: fftypes.KernelTypeDIT,
	})
}
