// Code generated by genkernels from dit_32768_radix4_then2.go. DO NOT EDIT.

package kernels

import (
	mathpkg "github.com/cwbudde/algo-fft/internal/math"
)

// forwardDIT32768Radix4Then2Complex128 computes a 32768-point forward FFT using
// radix-4-then-2 Decimation-in-Time (DIT) algorithm for complex128 data.
//
// For n = 32768 = 2 × 4^7, this uses 8 stages instead of 15:
//   - Stages 1-7: radix-4 (8192, 2048, 512, 128, 32, 8, 2 groups)
//   - Stage 8: radix-2 (final combination of two 16384-point halves)
//
// Unlike the smaller radix-4-then-2 codelets, the stage buffers ping-pong
// between scratch and dst: a per-stage stack backing would exceed the
// compiler's 128 KiB stack-allocation limit (512 KiB as complex128) and
// silently heap-allocate. src is fully consumed by the bit-reversed loads in
// stage 1, so dst is safe to reuse from stage 2 onward even in-place.
func forwardDIT32768Radix4Then2Complex128(dst, src, twiddle, scratch []complex128) bool {
	const n = 32768

	if len(dst) < n || len(twiddle) < n || len(scratch) < n || len(src) < n {
		return false
	}

	// Bounds hints
	br := bitrevSize32768Radix4Then2[:n]
	s := src[:n]
	tw := twiddle[:n]

	bufA := scratch[:n] // stages 1, 3, 5, 7
	bufB := dst[:n]     // stages 2, 4, 6, 8

	// Stage 1: 8192 radix-4 butterflies with fused bit-reversal
	// No twiddle multiplies (all W^0 = 1)
	for base := 0; base < n; base += 4 {
		a0 := s[br[base]]
		a1 := s[br[base+1]]
		a2 := s[br[base+2]]
		a3 := s[br[base+3]]

		t0 := a0 + a2
		t1 := a0 - a2
		t2 := a1 + a3
		t3 := a1 - a3

		bufA[base] = t0 + t2
		bufA[base+2] = t0 - t2
		bufA[base+1] = t1 + complex(imag(t3), -real(t3))
		bufA[base+3] = t1 + complex(-imag(t3), real(t3))
	}

	// Stage 2: 2048 radix-4 groups × 4 butterflies each
	for base := 0; base < n; base += 16 {
		for j := range 4 {
			w1 := tw[j*2048]
			w2 := tw[2*j*2048]
			w3 := tw[3*j*2048]

			idx0 := base + j
			idx1 := idx0 + 4
			idx2 := idx0 + 8
			idx3 := idx0 + 12

			a0 := bufA[idx0]
			a1 := mathpkg.MulComplex128(w1, bufA[idx1])
			a2 := mathpkg.MulComplex128(w2, bufA[idx2])
			a3 := mathpkg.MulComplex128(w3, bufA[idx3])

			t0 := a0 + a2
			t1 := a0 - a2
			t2 := a1 + a3
			t3 := a1 - a3

			bufB[idx0] = t0 + t2
			bufB[idx2] = t0 - t2
			bufB[idx1] = t1 + complex(imag(t3), -real(t3))
			bufB[idx3] = t1 + complex(-imag(t3), real(t3))
		}
	}

	// Stage 3: 512 radix-4 groups × 16 butterflies each
	for base := 0; base < n; base += 64 {
		for j := range 16 {
			w1 := tw[j*512]
			w2 := tw[2*j*512]
			w3 := tw[3*j*512]

			idx0 := base + j
			idx1 := idx0 + 16
			idx2 := idx0 + 32
			idx3 := idx0 + 48

			a0 := bufB[idx0]
			a1 := mathpkg.MulComplex128(w1, bufB[idx1])
			a2 := mathpkg.MulComplex128(w2, bufB[idx2])
			a3 := mathpkg.MulComplex128(w3, bufB[idx3])

			t0 := a0 + a2
			t1 := a0 - a2
			t2 := a1 + a3
			t3 := a1 - a3

			bufA[idx0] = t0 + t2
			bufA[idx2] = t0 - t2
			bufA[idx1] = t1 + complex(imag(t3), -real(t3))
			bufA[idx3] = t1 + complex(-imag(t3), real(t3))
		}
	}

	// Stage 4: 128 radix-4 groups × 64 butterflies each
	for base := 0; base < n; base += 256 {
		for j := range 64 {
			w1 := tw[j*128]
			w2 := tw[2*j*128]
			w3 := tw[3*j*128]

			idx0 := base + j
			idx1 := idx0 + 64
			idx2 := idx0 + 128
			idx3 := idx0 + 192

			a0 := bufA[idx0]
			a1 := mathpkg.MulComplex128(w1, bufA[idx1])
			a2 := mathpkg.MulComplex128(w2, bufA[idx2])
			a3 := mathpkg.MulComplex128(w3, bufA[idx3])

			t0 := a0 + a2
			t1 := a0 - a2
			t2 := a1 + a3
			t3 := a1 - a3

			bufB[idx0] = t0 + t2
			bufB[idx2] = t0 - t2
			bufB[idx1] = t1 + complex(imag(t3), -real(t3))
			bufB[idx3] = t1 + complex(-imag(t3), real(t3))
		}
	}

	// Stage 5: 32 radix-4 groups × 256 butterflies each
	for base := 0; base < n; base += 1024 {
		for j := range 256 {
			w1 := tw[j*32]
			w2 := tw[2*j*32]
			w3 := tw[3*j*32]

			idx0 := base + j
			idx1 := idx0 + 256
			idx2 := idx0 + 512
			idx3 := idx0 + 768

			a0 := bufB[idx0]
			a1 := mathpkg.MulComplex128(w1, bufB[idx1])
			a2 := mathpkg.MulComplex128(w2, bufB[idx2])
			a3 := mathpkg.MulComplex128(w3, bufB[idx3])

			t0 := a0 + a2
			t1 := a0 - a2
			t2 := a1 + a3
			t3 := a1 - a3

			bufA[idx0] = t0 + t2
			bufA[idx2] = t0 - t2
			bufA[idx1] = t1 + complex(imag(t3), -real(t3))
			bufA[idx3] = t1 + complex(-imag(t3), real(t3))
		}
	}

	// Stage 6: 8 radix-4 groups × 1024 butterflies each
	for base := 0; base < n; base += 4096 {
		for j := range 1024 {
			w1 := tw[j*8]
			w2 := tw[2*j*8]
			w3 := tw[3*j*8]

			idx0 := base + j
			idx1 := idx0 + 1024
			idx2 := idx0 + 2048
			idx3 := idx0 + 3072

			a0 := bufA[idx0]
			a1 := mathpkg.MulComplex128(w1, bufA[idx1])
			a2 := mathpkg.MulComplex128(w2, bufA[idx2])
			a3 := mathpkg.MulComplex128(w3, bufA[idx3])

			t0 := a0 + a2
			t1 := a0 - a2
			t2 := a1 + a3
			t3 := a1 - a3

			bufB[idx0] = t0 + t2
			bufB[idx2] = t0 - t2
			bufB[idx1] = t1 + complex(imag(t3), -real(t3))
			bufB[idx3] = t1 + complex(-imag(t3), real(t3))
		}
	}

	// Stage 7: 2 radix-4 groups × 4096 butterflies each
	for base := 0; base < n; base += 16384 {
		for j := range 4096 {
			w1 := tw[j*2]
			w2 := tw[2*j*2]
			w3 := tw[3*j*2]

			idx0 := base + j
			idx1 := idx0 + 4096
			idx2 := idx0 + 8192
			idx3 := idx0 + 12288

			a0 := bufB[idx0]
			a1 := mathpkg.MulComplex128(w1, bufB[idx1])
			a2 := mathpkg.MulComplex128(w2, bufB[idx2])
			a3 := mathpkg.MulComplex128(w3, bufB[idx3])

			t0 := a0 + a2
			t1 := a0 - a2
			t2 := a1 + a3
			t3 := a1 - a3

			bufA[idx0] = t0 + t2
			bufA[idx2] = t0 - t2
			bufA[idx1] = t1 + complex(imag(t3), -real(t3))
			bufA[idx3] = t1 + complex(-imag(t3), real(t3))
		}
	}

	// Stage 8: radix-2 final stage (combines two 16384-point halves)
	for j := range 16384 {
		w := tw[j]
		a := bufA[j]
		b := mathpkg.MulComplex128(w, bufA[j+16384])
		bufB[j] = a + b
		bufB[j+16384] = a - b
	}

	return true
}

// inverseDIT32768Radix4Then2Complex128 computes a 32768-point inverse FFT using
// radix-4-then-2 Decimation-in-Time (DIT) algorithm for complex128 data.
//
// Uses conjugated twiddle factors and applies 1/N scaling.
func inverseDIT32768Radix4Then2Complex128(dst, src, twiddle, scratch []complex128) bool {
	const n = 32768

	if len(dst) < n || len(twiddle) < n || len(scratch) < n || len(src) < n {
		return false
	}

	br := bitrevSize32768Radix4Then2[:n]
	s := src[:n]
	tw := twiddle[:n]

	bufA := scratch[:n] // stages 1, 3, 5, 7
	bufB := dst[:n]     // stages 2, 4, 6, 8

	// Stage 1: 8192 radix-4 butterflies with fused bit-reversal
	for base := 0; base < n; base += 4 {
		a0 := s[br[base]]
		a1 := s[br[base+1]]
		a2 := s[br[base+2]]
		a3 := s[br[base+3]]

		t0 := a0 + a2
		t1 := a0 - a2
		t2 := a1 + a3
		t3 := a1 - a3

		// Inverse butterfly: swap mulI and mulNegI
		bufA[base] = t0 + t2
		bufA[base+2] = t0 - t2
		bufA[base+1] = t1 + complex(-imag(t3), real(t3))
		bufA[base+3] = t1 + complex(imag(t3), -real(t3))
	}

	// Stage 2: 2048 radix-4 groups with conjugated twiddles
	for base := 0; base < n; base += 16 {
		for j := range 4 {
			w1 := complex(real(tw[j*2048]), -imag(tw[j*2048]))
			w2 := complex(real(tw[2*j*2048]), -imag(tw[2*j*2048]))
			w3 := complex(real(tw[3*j*2048]), -imag(tw[3*j*2048]))

			idx0 := base + j
			idx1 := idx0 + 4
			idx2 := idx0 + 8
			idx3 := idx0 + 12

			a0 := bufA[idx0]
			a1 := mathpkg.MulComplex128(w1, bufA[idx1])
			a2 := mathpkg.MulComplex128(w2, bufA[idx2])
			a3 := mathpkg.MulComplex128(w3, bufA[idx3])

			t0 := a0 + a2
			t1 := a0 - a2
			t2 := a1 + a3
			t3 := a1 - a3

			bufB[idx0] = t0 + t2
			bufB[idx2] = t0 - t2
			bufB[idx1] = t1 + complex(-imag(t3), real(t3))
			bufB[idx3] = t1 + complex(imag(t3), -real(t3))
		}
	}

	// Stage 3: 512 radix-4 groups with conjugated twiddles
	for base := 0; base < n; base += 64 {
		for j := range 16 {
			w1 := complex(real(tw[j*512]), -imag(tw[j*512]))
			w2 := complex(real(tw[2*j*512]), -imag(tw[2*j*512]))
			w3 := complex(real(tw[3*j*512]), -imag(tw[3*j*512]))

			idx0 := base + j
			idx1 := idx0 + 16
			idx2 := idx0 + 32
			idx3 := idx0 + 48

			a0 := bufB[idx0]
			a1 := mathpkg.MulComplex128(w1, bufB[idx1])
			a2 := mathpkg.MulComplex128(w2, bufB[idx2])
			a3 := mathpkg.MulComplex128(w3, bufB[idx3])

			t0 := a0 + a2
			t1 := a0 - a2
			t2 := a1 + a3
			t3 := a1 - a3

			bufA[idx0] = t0 + t2
			bufA[idx2] = t0 - t2
			bufA[idx1] = t1 + complex(-imag(t3), real(t3))
			bufA[idx3] = t1 + complex(imag(t3), -real(t3))
		}
	}

	// Stage 4: 128 radix-4 groups with conjugated twiddles
	for base := 0; base < n; base += 256 {
		for j := range 64 {
			w1 := complex(real(tw[j*128]), -imag(tw[j*128]))
			w2 := complex(real(tw[2*j*128]), -imag(tw[2*j*128]))
			w3 := complex(real(tw[3*j*128]), -imag(tw[3*j*128]))

			idx0 := base + j
			idx1 := idx0 + 64
			idx2 := idx0 + 128
			idx3 := idx0 + 192

			a0 := bufA[idx0]
			a1 := mathpkg.MulComplex128(w1, bufA[idx1])
			a2 := mathpkg.MulComplex128(w2, bufA[idx2])
			a3 := mathpkg.MulComplex128(w3, bufA[idx3])

			t0 := a0 + a2
			t1 := a0 - a2
			t2 := a1 + a3
			t3 := a1 - a3

			bufB[idx0] = t0 + t2
			bufB[idx2] = t0 - t2
			bufB[idx1] = t1 + complex(-imag(t3), real(t3))
			bufB[idx3] = t1 + complex(imag(t3), -real(t3))
		}
	}

	// Stage 5: 32 radix-4 groups with conjugated twiddles
	for base := 0; base < n; base += 1024 {
		for j := range 256 {
			w1 := complex(real(tw[j*32]), -imag(tw[j*32]))
			w2 := complex(real(tw[2*j*32]), -imag(tw[2*j*32]))
			w3 := complex(real(tw[3*j*32]), -imag(tw[3*j*32]))

			idx0 := base + j
			idx1 := idx0 + 256
			idx2 := idx0 + 512
			idx3 := idx0 + 768

			a0 := bufB[idx0]
			a1 := mathpkg.MulComplex128(w1, bufB[idx1])
			a2 := mathpkg.MulComplex128(w2, bufB[idx2])
			a3 := mathpkg.MulComplex128(w3, bufB[idx3])

			t0 := a0 + a2
			t1 := a0 - a2
			t2 := a1 + a3
			t3 := a1 - a3

			bufA[idx0] = t0 + t2
			bufA[idx2] = t0 - t2
			bufA[idx1] = t1 + complex(-imag(t3), real(t3))
			bufA[idx3] = t1 + complex(imag(t3), -real(t3))
		}
	}

	// Stage 6: 8 radix-4 groups with conjugated twiddles
	for base := 0; base < n; base += 4096 {
		for j := range 1024 {
			w1 := complex(real(tw[j*8]), -imag(tw[j*8]))
			w2 := complex(real(tw[2*j*8]), -imag(tw[2*j*8]))
			w3 := complex(real(tw[3*j*8]), -imag(tw[3*j*8]))

			idx0 := base + j
			idx1 := idx0 + 1024
			idx2 := idx0 + 2048
			idx3 := idx0 + 3072

			a0 := bufA[idx0]
			a1 := mathpkg.MulComplex128(w1, bufA[idx1])
			a2 := mathpkg.MulComplex128(w2, bufA[idx2])
			a3 := mathpkg.MulComplex128(w3, bufA[idx3])

			t0 := a0 + a2
			t1 := a0 - a2
			t2 := a1 + a3
			t3 := a1 - a3

			bufB[idx0] = t0 + t2
			bufB[idx2] = t0 - t2
			bufB[idx1] = t1 + complex(-imag(t3), real(t3))
			bufB[idx3] = t1 + complex(imag(t3), -real(t3))
		}
	}

	// Stage 7: 2 radix-4 groups with conjugated twiddles
	for base := 0; base < n; base += 16384 {
		for j := range 4096 {
			w1 := complex(real(tw[j*2]), -imag(tw[j*2]))
			w2 := complex(real(tw[2*j*2]), -imag(tw[2*j*2]))
			w3 := complex(real(tw[3*j*2]), -imag(tw[3*j*2]))

			idx0 := base + j
			idx1 := idx0 + 4096
			idx2 := idx0 + 8192
			idx3 := idx0 + 12288

			a0 := bufB[idx0]
			a1 := mathpkg.MulComplex128(w1, bufB[idx1])
			a2 := mathpkg.MulComplex128(w2, bufB[idx2])
			a3 := mathpkg.MulComplex128(w3, bufB[idx3])

			t0 := a0 + a2
			t1 := a0 - a2
			t2 := a1 + a3
			t3 := a1 - a3

			bufA[idx0] = t0 + t2
			bufA[idx2] = t0 - t2
			bufA[idx1] = t1 + complex(-imag(t3), real(t3))
			bufA[idx3] = t1 + complex(imag(t3), -real(t3))
		}
	}

	// Stage 8: radix-2 final stage with conjugated twiddles
	for j := range 16384 {
		w := complex(real(tw[j]), -imag(tw[j]))
		a := bufA[j]
		b := mathpkg.MulComplex128(w, bufA[j+16384])
		bufB[j] = a + b
		bufB[j+16384] = a - b
	}

	// Apply 1/N scaling
	scale := 1.0 / float64(n)
	for i := range dst[:n] {
		dst[i] = complex(real(dst[i])*scale, imag(dst[i])*scale)
	}

	return true
}
