// Code generated by genkernels from dit.go. DO NOT EDIT.

package kernels

import (
	mathpkg "github.com/cwbudde/algo-fft/internal/math"
)

func forwardDITComplex128(dst, src, twiddle, scratch []complex128) bool {
	switch len(src) {
	case 8:
		return forwardDIT8Complex128(dst, src, twiddle, scratch)
	case 16:
		// Use faster radix-4 implementation (12-15% faster than radix-2)
		return forwardDIT16Radix4Complex128(dst, src, twiddle, scratch)
	case 32:
		return forwardDIT32Radix2Complex128(dst, src, twiddle, scratch)
	case 64:
		return forwardDIT64Radix4Complex128(dst, src, twiddle, scratch)
	case 128:
		return forwardDIT128Radix2Complex128(dst, src, twiddle, scratch)
	case 256:
		return forwardDIT256Complex128(dst, src, twiddle, scratch)
	case 512:
		return forwardDIT512Complex128(dst, src, twiddle, scratch)
	case 1024:
		// Try radix-32x32 first (usually faster for large N)
		if forwardDIT1024Mixed32x32Complex128(dst, src, twiddle, scratch) {
			return true
		}
		// Fallback to optimized radix-4
		return forwardDIT1024Radix4Complex128(dst, src, twiddle, scratch)
	case 2048:
		return forwardDIT2048Radix4Then2Complex128(dst, src, twiddle, scratch)
	case 4096:
		if forwardDIT4096SixStepComplex128(dst, src, twiddle, scratch) {
			return true
		}

		return forwardDIT4096Radix4Complex128(dst, src, twiddle, scratch)
	}

	n := len(src)
	if isPowerOf4(n) {
		if forwardRadix4Complex128(dst, src, twiddle, scratch) {
			return true
		}
	} else if IsPowerOf2(n) {
		if forwardRadix4Then2Complex128(dst, src, twiddle, scratch) {
			return true
		}
	}

	return ditForwardComplex128(dst, src, twiddle, scratch)
}

func inverseDITComplex128(dst, src, twiddle, scratch []complex128) bool {
	switch len(src) {
	case 8:
		return inverseDIT8Complex128(dst, src, twiddle, scratch)
	case 16:
		// Use faster radix-4 implementation (12-15% faster than radix-2)
		return inverseDIT16Radix4Complex128(dst, src, twiddle, scratch)
	case 32:
		return inverseDIT32Radix2Complex128(dst, src, twiddle, scratch)
	case 64:
		return inverseDIT64Radix4Complex128(dst, src, twiddle, scratch)
	case 128:
		return inverseDIT128Radix2Complex128(dst, src, twiddle, scratch)
	case 256:
		return inverseDIT256Complex128(dst, src, twiddle, scratch)
	case 512:
		return inverseDIT512Complex128(dst, src, twiddle, scratch)
	case 1024:
		// Try radix-32x32 first
		if inverseDIT1024Mixed32x32Complex128(dst, src, twiddle, scratch) {
			return true
		}
		// Fallback to optimized radix-4
		return inverseDIT1024Radix4Complex128(dst, src, twiddle, scratch)
	case 2048:
		return inverseDIT2048Radix4Then2Complex128(dst, src, twiddle, scratch)
	case 4096:
		if inverseDIT4096SixStepComplex128(dst, src, twiddle, scratch) {
			return true
		}

		return inverseDIT4096Radix4Complex128(dst, src, twiddle, scratch)
	}

	n := len(src)
	if isPowerOf4(n) {
		if inverseRadix4Complex128(dst, src, twiddle, scratch) {
			return true
		}
	} else if IsPowerOf2(n) {
		if inverseRadix4Then2Complex128(dst, src, twiddle, scratch) {
			return true
		}
	}

	return ditInverseComplex128(dst, src, twiddle, scratch)
}

// ditForwardComplex128 is the monomorphized twin of ditForward, mirroring
// ditInverseComplex128. It exists so the complex128 fallback path multiplies in
// single precision (see butterfly2Complex128); the generic instantiation cannot.
func ditForwardComplex128(dst, src, twiddle, scratch []complex128) bool {
	n := len(src)
	if n == 0 {
		return true
	}

	if len(dst) < n || len(twiddle) < n || len(scratch) < n {
		return false
	}

	if n == 1 {
		dst[0] = src[0]
		return true
	}

	if !mathpkg.IsPowerOf2(n) {
		return false
	}

	work := dst
	workIsDst := true

	if sameSlice(dst, src) {
		work = scratch
		workIsDst = false
	}

	work = work[:n]
	src = src[:n]
	twiddle = twiddle[:n]

	bitrev := mathpkg.ComputeBitReversalIndices(n)

	for i := range n {
		work[i] = src[bitrev[i]]
	}

	for size := 2; size <= n; size <<= 1 {
		half := size >> 1

		step := n / size
		for base := 0; base < n; base += size {
			block := work[base : base+size]

			for j := range half {
				tw := twiddle[j*step]
				a, b := butterfly2Complex128(block[j], block[j+half], tw)
				block[j] = a
				block[j+half] = b
			}
		}
	}

	if !workIsDst {
		copy(dst, work)
	}

	return true
}

func ditInverseComplex128(dst, src, twiddle, scratch []complex128) bool {
	n := len(src)
	if n == 0 {
		return true
	}

	if len(dst) < n || len(twiddle) < n || len(scratch) < n {
		return false
	}

	if n == 1 {
		dst[0] = src[0]
		return true
	}

	if !mathpkg.IsPowerOf2(n) {
		return false
	}

	work := dst
	workIsDst := true

	if sameSlice(dst, src) {
		work = scratch
		workIsDst = false
	}

	work = work[:n]
	src = src[:n]
	twiddle = twiddle[:n]

	bitrev := mathpkg.ComputeBitReversalIndices(n)

	for i := range n {
		work[i] = src[bitrev[i]]
	}

	for size := 2; size <= n; size <<= 1 {
		half := size >> 1

		step := n / size
		for base := 0; base < n; base += size {
			block := work[base : base+size]

			for j := range half {
				tw := twiddle[j*step]
				tw = complex(real(tw), -imag(tw))
				a, b := butterfly2Complex128(block[j], block[j+half], tw)
				block[j] = a
				block[j+half] = b
			}
		}
	}

	if !workIsDst {
		copy(dst, work)
	}

	scale := 1.0 / float64(n)
	for i := range dst {
		dst[i] = complex(real(dst[i])*scale, imag(dst[i])*scale)
	}

	return true
}

// butterfly2Complex128 is the monomorphized twin of butterfly2. The generic
// form cannot avoid the float32->float64 promotion Go emits for scalar
// complex128 multiplication (see mathpkg.MulComplex128), because `w * b` there
// has type T; the complex128 codelets call this instead.
func butterfly2Complex128(a, b, w complex128) (complex128, complex128) {
	t := mathpkg.MulComplex128(w, b)
	return a + t, a - t
}

// Internal wrappers for sizes that now handle bit-reversal internally.
func forwardDIT8Complex128(dst, src, twiddle, scratch []complex128) bool {
	return forwardDIT8Radix8Complex128(dst, src, twiddle, scratch)
}

func inverseDIT8Complex128(dst, src, twiddle, scratch []complex128) bool {
	return inverseDIT8Radix8Complex128(dst, src, twiddle, scratch)
}

func forwardDIT16Complex128(dst, src, twiddle, scratch []complex128) bool {
	return forwardDIT16Radix4Complex128(dst, src, twiddle, scratch)
}

func inverseDIT16Complex128(dst, src, twiddle, scratch []complex128) bool {
	return inverseDIT16Radix4Complex128(dst, src, twiddle, scratch)
}
