// Code generated by genkernels from dit_8_radix2.go. DO NOT EDIT.

package kernels

import (
	mathpkg "github.com/cwbudde/algo-fft/internal/math"
)

// forwardDIT8Radix2Complex128 computes an 8-point forward FFT using the
// Decimation-in-Time (DIT) algorithm with radix-2 stages for complex128 data.
// Fully unrolled for maximum performance.
// Returns false if any slice is too small.
func forwardDIT8Radix2Complex128(dst, src, twiddle, scratch []complex128) bool {
	const n = 8

	if len(dst) < n || len(twiddle) < n || len(scratch) < n || len(src) < n {
		return false
	}

	// Bounds hint for compiler optimization
	s := src[:n]

	// Pre-load twiddle factors
	w1, w2, w3 := twiddle[1], twiddle[2], twiddle[3]

	// Stage 1: 4 radix-2 butterflies, stride=2, no twiddles (W^0 = 1)
	// Reorder input using bit-reversal indices during the first stage loads.
	x0 := s[0]
	x1 := s[4]
	a0, a1 := x0+x1, x0-x1
	x0 = s[2]
	x1 = s[6]
	a2, a3 := x0+x1, x0-x1
	x0 = s[1]
	x1 = s[5]
	a4, a5 := x0+x1, x0-x1
	x0 = s[3]
	x1 = s[7]
	a6, a7 := x0+x1, x0-x1

	// Stage 2: 2 radix-2 butterflies, stride=4
	b0, b2 := a0+a2, a0-a2
	t := mathpkg.MulComplex128(w2, a3)
	b1, b3 := a1+t, a1-t
	b4, b6 := a4+a6, a4-a6
	t = mathpkg.MulComplex128(w2, a7)
	b5, b7 := a5+t, a5-t

	// Stage 3: 1 radix-2 butterfly, stride=8 (full array)
	// Write directly to output or scratch buffer to avoid aliasing.
	work := dst
	if &dst[0] == &src[0] {
		work = scratch
	}

	work = work[:n]
	work[0], work[4] = b0+b4, b0-b4
	t = mathpkg.MulComplex128(w1, b5)
	work[1], work[5] = b1+t, b1-t
	t = mathpkg.MulComplex128(w2, b6)
	work[2], work[6] = b2+t, b2-t
	t = mathpkg.MulComplex128(w3, b7)
	work[3], work[7] = b3+t, b3-t

	// Copy result back if we used scratch buffer
	if &work[0] != &dst[0] {
		copy(dst, work)
	}

	return true
}

func inverseDIT8Radix2Complex128(dst, src, twiddle, scratch []complex128) bool {
	const n = 8

	if len(dst) < n || len(twiddle) < n || len(scratch) < n || len(src) < n {
		return false
	}

	// Bounds hint for compiler optimization
	s := src[:n]

	// Conjugate twiddles for inverse transform
	w1, w2, w3 := twiddle[1], twiddle[2], twiddle[3]
	w1 = complex(real(w1), -imag(w1))
	w2 = complex(real(w2), -imag(w2))
	w3 = complex(real(w3), -imag(w3))

	// Stage 1: 4 radix-2 butterflies, stride=2, no twiddles (W^0 = 1)
	// Reorder input using bit-reversal indices during the first stage loads.
	x0 := s[0]
	x1 := s[4]
	a0, a1 := x0+x1, x0-x1
	x0 = s[2]
	x1 = s[6]
	a2, a3 := x0+x1, x0-x1
	x0 = s[1]
	x1 = s[5]
	a4, a5 := x0+x1, x0-x1
	x0 = s[3]
	x1 = s[7]
	a6, a7 := x0+x1, x0-x1

	// Stage 2: 2 radix-2 butterflies, stride=4
	b0, b2 := a0+a2, a0-a2
	t := mathpkg.MulComplex128(w2, a3)
	b1, b3 := a1+t, a1-t
	b4, b6 := a4+a6, a4-a6
	t = mathpkg.MulComplex128(w2, a7)
	b5, b7 := a5+t, a5-t

	// Stage 3: 1 radix-2 butterfly, stride=8 (full array)
	// Write directly to output or scratch buffer to avoid aliasing.
	work := dst
	if &dst[0] == &src[0] {
		work = scratch
	}

	work = work[:n]
	work[0], work[4] = b0+b4, b0-b4
	t = mathpkg.MulComplex128(w1, b5)
	work[1], work[5] = b1+t, b1-t
	t = mathpkg.MulComplex128(w2, b6)
	work[2], work[6] = b2+t, b2-t
	t = mathpkg.MulComplex128(w3, b7)
	work[3], work[7] = b3+t, b3-t

	// Copy result back if we used scratch buffer
	if &work[0] != &dst[0] {
		copy(dst, work)
	}

	// Apply 1/N scaling for inverse transform
	scale := 1.0 / float64(n)
	for i := range dst[:n] {
		dst[i] = complex(real(dst[i])*scale, imag(dst[i])*scale)
	}

	return true
}
