// Code generated by genkernels from dit_radix4_then2.go. DO NOT EDIT.

package kernels

func forwardRadix4Then2Complex128(dst, src, twiddle, scratch []complex128) bool {
	// NOTE: The previous radix-4-then-2 implementation for odd log2 sizes was
	// incorrect and produced wrong results (e.g., impulse DC bin doubled for n=2048).
	// For correctness, delegate to the proven radix-2 DIT implementation.
	return ditForwardComplex128(dst, src, twiddle, scratch)
}

func inverseRadix4Then2Complex128(dst, src, twiddle, scratch []complex128) bool {
	// See forwardRadix4Then2Complex128: delegate to the proven radix-2 inverse.
	return ditInverseComplex128(dst, src, twiddle, scratch)
}
