// Code generated by genkernels from radix8_generic.go. DO NOT EDIT.

package kernels

import (
	mathpkg "github.com/cwbudde/algo-fft/internal/math"
	"math"
)

// prepareTwiddleRadix8Complex128 fills dst with the per-stage twiddle planes
// described above. For the inverse transform the imaginary parts are negated,
// which is the conjugate W^-k = conj(W^k), so the stage code is direction-blind
// apart from its butterfly.
func prepareTwiddleRadix8Complex128(n int, inverse bool, dst []complex128) {
	limit, tail, ok := radix8Limit(n)
	if !ok || len(dst) < twiddleSizeRadix8(n) {
		return
	}

	clear(dst[:twiddleSizeRadix8(n)])

	sign := -1.0
	if inverse {
		sign = 1.0
	}

	// w(e) = exp(sign * 2*pi*i*e/n), matching math.ComputeTwiddleFactors but
	// evaluated directly so no n-element intermediate table is needed.
	w := func(e int) complex128 {
		sin, cos := math.Sincos(sign * 2 * math.Pi * float64(e%n) / float64(n))

		return mathpkg.ComplexFromFloat64[complex128](cos, sin)
	}

	offset := 0

	// Radix-8 stages: butterfly j of block d is scaled by W_(8m)^(jd).
	for m := 8; m*8 <= limit; m *= 8 {
		step := n / (8 * m)

		for d := 1; d <= 7; d++ {
			for j := range m {
				dst[offset+j] = w(d * j * step)
			}

			offset += m
		}
	}

	// Tail stage: span n, so its step is 1.
	for d := 1; d < tail; d++ {
		m := n / tail

		for j := range m {
			dst[offset+j] = w(d * j)
		}

		offset += m
	}
}

// radix8PrologueComplex128 validates the arguments common to both directions and returns
// the working buffer, the stage-1 group table and the ladder shape.
func radix8PrologueComplex128(dst, src, twiddle, scratch []complex128) (
	work []complex128, groups []int32, limit, tail int, ok bool,
) {
	n := len(src)

	limit, tail, ok = radix8Limit(n)
	if !ok || len(dst) < n || len(scratch) < n || len(twiddle) < twiddleSizeRadix8(n) {
		return nil, nil, 0, 0, false
	}

	groups = radix8GroupIndices(n)
	if len(groups) != n/8 {
		return nil, nil, 0, 0, false
	}

	work = dst[:n]
	if &dst[0] == &src[0] {
		// Stage 1 gathers, so it cannot write over its own source.
		work = scratch[:n]
	}

	return work, groups, limit, tail, true
}

// forwardRadix8Complex128 is the CodeletFunc entry point for the forward
// transform. twiddle must be the table produced by prepareTwiddleRadix8Complex128.
func forwardRadix8Complex128(dst, src, twiddle, scratch []complex128) bool {
	n := len(src)

	work, groups, limit, tail, ok := radix8PrologueComplex128(dst, src, twiddle, scratch)
	if !ok {
		return false
	}

	s := src[:n]
	stride := n / 8

	// Stage 1: one twiddle-free butterfly per group, fused with the gather.
	for g, first := range groups {
		p := int(first)

		x0 := s[p]
		x1 := s[p+stride]
		x2 := s[p+2*stride]
		x3 := s[p+3*stride]
		x4 := s[p+4*stride]
		x5 := s[p+5*stride]
		x6 := s[p+6*stride]
		x7 := s[p+7*stride]

		a0 := x0 + x4
		a1 := x0 - x4
		a2 := x2 + x6
		a3 := x2 - x6
		a4 := x1 + x5
		a5 := x1 - x5
		a6 := x3 + x7
		a7 := x3 - x7

		e0 := a0 + a2
		e2 := a0 - a2
		e1 := a1 + complex(imag(a3), -real(a3)) // a1 - i*a3
		e3 := a1 + complex(-imag(a3), real(a3)) // a1 + i*a3
		o0 := a4 + a6
		o2 := a4 - a6
		o1 := a5 + complex(imag(a7), -real(a7)) // a5 - i*a7
		o3 := a5 + complex(-imag(a7), real(a7)) // a5 + i*a7

		t1 := complex(root2Over2*(real(o1)+imag(o1)), root2Over2*(imag(o1)-real(o1)))
		t2 := complex(imag(o2), -real(o2))
		t3 := complex(root2Over2*(imag(o3)-real(o3)), -root2Over2*(real(o3)+imag(o3)))

		out := work[8*g : 8*g+8 : 8*g+8]
		out[0] = e0 + o0
		out[1] = e1 + t1
		out[2] = e2 + t2
		out[3] = e3 + t3
		out[4] = e0 - o0
		out[5] = e1 - t1
		out[6] = e2 - t2
		out[7] = e3 - t3
	}

	offset := radix8StagesForwardComplex128(work, twiddle, n, limit)
	radix8TailForwardComplex128(work, twiddle, n, tail, offset)

	if &work[0] != &dst[0] {
		copy(dst[:n], work)
	}

	return true
}

// radix8StagesForwardComplex128 runs the twiddled radix-8 stages in place and
// returns the number of twiddle elements consumed.
func radix8StagesForwardComplex128(work, twiddle []complex128, n, limit int) int {
	offset := 0

	for m := 8; m*8 <= limit; m *= 8 {
		span := 8 * m

		w1 := twiddle[offset : offset+m]
		w2 := twiddle[offset+m : offset+2*m]
		w3 := twiddle[offset+2*m : offset+3*m]
		w4 := twiddle[offset+3*m : offset+4*m]
		w5 := twiddle[offset+4*m : offset+5*m]
		w6 := twiddle[offset+5*m : offset+6*m]
		w7 := twiddle[offset+6*m : offset+7*m]
		offset += 7 * m

		for base := 0; base < n; base += span {
			blk := work[base : base+span : base+span]

			for j := range m {
				x0 := blk[j]
				x1 := mathpkg.MulComplex128(w1[j], blk[j+m])
				x2 := mathpkg.MulComplex128(w2[j], blk[j+2*m])
				x3 := mathpkg.MulComplex128(w3[j], blk[j+3*m])
				x4 := mathpkg.MulComplex128(w4[j], blk[j+4*m])
				x5 := mathpkg.MulComplex128(w5[j], blk[j+5*m])
				x6 := mathpkg.MulComplex128(w6[j], blk[j+6*m])
				x7 := mathpkg.MulComplex128(w7[j], blk[j+7*m])

				a0 := x0 + x4
				a1 := x0 - x4
				a2 := x2 + x6
				a3 := x2 - x6
				a4 := x1 + x5
				a5 := x1 - x5
				a6 := x3 + x7
				a7 := x3 - x7

				e0 := a0 + a2
				e2 := a0 - a2
				e1 := a1 + complex(imag(a3), -real(a3))
				e3 := a1 + complex(-imag(a3), real(a3))
				o0 := a4 + a6
				o2 := a4 - a6
				o1 := a5 + complex(imag(a7), -real(a7))
				o3 := a5 + complex(-imag(a7), real(a7))

				t1 := complex(root2Over2*(real(o1)+imag(o1)), root2Over2*(imag(o1)-real(o1)))
				t2 := complex(imag(o2), -real(o2))
				t3 := complex(root2Over2*(imag(o3)-real(o3)), -root2Over2*(real(o3)+imag(o3)))

				blk[j] = e0 + o0
				blk[j+m] = e1 + t1
				blk[j+2*m] = e2 + t2
				blk[j+3*m] = e3 + t3
				blk[j+4*m] = e0 - o0
				blk[j+5*m] = e1 - t1
				blk[j+6*m] = e2 - t2
				blk[j+7*m] = e3 - t3
			}
		}
	}

	return offset
}

// radix8TailForwardComplex128 runs the single widest stage for the shapes that
// need one: radix-2 for n = 2*8^k, radix-4 for n = 4*8^k, nothing otherwise.
func radix8TailForwardComplex128(work, twiddle []complex128, n, tail, offset int) {
	switch tail {
	case 2:
		m := n / 2
		w1 := twiddle[offset : offset+m]

		for j := range m {
			a := work[j]
			b := mathpkg.MulComplex128(w1[j], work[j+m])
			work[j] = a + b
			work[j+m] = a - b
		}

	case 4:
		m := n / 4
		w1 := twiddle[offset : offset+m]
		w2 := twiddle[offset+m : offset+2*m]
		w3 := twiddle[offset+2*m : offset+3*m]

		for j := range m {
			x0 := work[j]
			x1 := mathpkg.MulComplex128(w1[j], work[j+m])
			x2 := mathpkg.MulComplex128(w2[j], work[j+2*m])
			x3 := mathpkg.MulComplex128(w3[j], work[j+3*m])

			t0 := x0 + x2
			t1 := x0 - x2
			t2 := x1 + x3
			t3 := x1 - x3

			work[j] = t0 + t2
			work[j+m] = t1 + complex(imag(t3), -real(t3)) // t1 - i*t3
			work[j+2*m] = t0 - t2
			work[j+3*m] = t1 + complex(-imag(t3), real(t3)) // t1 + i*t3
		}
	}
}

// inverseRadix8Complex128 is the CodeletFunc entry point for the inverse
// transform. The 1/n normalisation is exact here (n is a power of two) and is
// folded into the stage-1 gather rather than costing a separate pass over the
// data; by linearity the result is identical either way.
func inverseRadix8Complex128(dst, src, twiddle, scratch []complex128) bool {
	n := len(src)

	work, groups, limit, tail, ok := radix8PrologueComplex128(dst, src, twiddle, scratch)
	if !ok {
		return false
	}

	s := src[:n]
	stride := n / 8
	scale := 1 / float64(n)

	for g, first := range groups {
		p := int(first)

		v0 := s[p]
		v1 := s[p+stride]
		v2 := s[p+2*stride]
		v3 := s[p+3*stride]
		v4 := s[p+4*stride]
		v5 := s[p+5*stride]
		v6 := s[p+6*stride]
		v7 := s[p+7*stride]

		x0 := complex(real(v0)*scale, imag(v0)*scale)
		x1 := complex(real(v1)*scale, imag(v1)*scale)
		x2 := complex(real(v2)*scale, imag(v2)*scale)
		x3 := complex(real(v3)*scale, imag(v3)*scale)
		x4 := complex(real(v4)*scale, imag(v4)*scale)
		x5 := complex(real(v5)*scale, imag(v5)*scale)
		x6 := complex(real(v6)*scale, imag(v6)*scale)
		x7 := complex(real(v7)*scale, imag(v7)*scale)

		a0 := x0 + x4
		a1 := x0 - x4
		a2 := x2 + x6
		a3 := x2 - x6
		a4 := x1 + x5
		a5 := x1 - x5
		a6 := x3 + x7
		a7 := x3 - x7

		e0 := a0 + a2
		e2 := a0 - a2
		e1 := a1 + complex(-imag(a3), real(a3)) // a1 + i*a3
		e3 := a1 + complex(imag(a3), -real(a3)) // a1 - i*a3
		o0 := a4 + a6
		o2 := a4 - a6
		o1 := a5 + complex(-imag(a7), real(a7))
		o3 := a5 + complex(imag(a7), -real(a7))

		t1 := complex(root2Over2*(real(o1)-imag(o1)), root2Over2*(imag(o1)+real(o1)))
		t2 := complex(-imag(o2), real(o2))
		t3 := complex(-root2Over2*(real(o3)+imag(o3)), root2Over2*(real(o3)-imag(o3)))

		out := work[8*g : 8*g+8 : 8*g+8]
		out[0] = e0 + o0
		out[1] = e1 + t1
		out[2] = e2 + t2
		out[3] = e3 + t3
		out[4] = e0 - o0
		out[5] = e1 - t1
		out[6] = e2 - t2
		out[7] = e3 - t3
	}

	offset := radix8StagesInverseComplex128(work, twiddle, n, limit)
	radix8TailInverseComplex128(work, twiddle, n, tail, offset)

	if &work[0] != &dst[0] {
		copy(dst[:n], work)
	}

	return true
}

// radix8StagesInverseComplex128 is the inverse twin of
// radix8StagesForwardComplex128. The twiddles are already conjugated by
// prepareTwiddleRadix8Complex128, so only the butterfly's internal rotations
// differ.
func radix8StagesInverseComplex128(work, twiddle []complex128, n, limit int) int {
	offset := 0

	for m := 8; m*8 <= limit; m *= 8 {
		span := 8 * m

		w1 := twiddle[offset : offset+m]
		w2 := twiddle[offset+m : offset+2*m]
		w3 := twiddle[offset+2*m : offset+3*m]
		w4 := twiddle[offset+3*m : offset+4*m]
		w5 := twiddle[offset+4*m : offset+5*m]
		w6 := twiddle[offset+5*m : offset+6*m]
		w7 := twiddle[offset+6*m : offset+7*m]
		offset += 7 * m

		for base := 0; base < n; base += span {
			blk := work[base : base+span : base+span]

			for j := range m {
				x0 := blk[j]
				x1 := mathpkg.MulComplex128(w1[j], blk[j+m])
				x2 := mathpkg.MulComplex128(w2[j], blk[j+2*m])
				x3 := mathpkg.MulComplex128(w3[j], blk[j+3*m])
				x4 := mathpkg.MulComplex128(w4[j], blk[j+4*m])
				x5 := mathpkg.MulComplex128(w5[j], blk[j+5*m])
				x6 := mathpkg.MulComplex128(w6[j], blk[j+6*m])
				x7 := mathpkg.MulComplex128(w7[j], blk[j+7*m])

				a0 := x0 + x4
				a1 := x0 - x4
				a2 := x2 + x6
				a3 := x2 - x6
				a4 := x1 + x5
				a5 := x1 - x5
				a6 := x3 + x7
				a7 := x3 - x7

				e0 := a0 + a2
				e2 := a0 - a2
				e1 := a1 + complex(-imag(a3), real(a3))
				e3 := a1 + complex(imag(a3), -real(a3))
				o0 := a4 + a6
				o2 := a4 - a6
				o1 := a5 + complex(-imag(a7), real(a7))
				o3 := a5 + complex(imag(a7), -real(a7))

				t1 := complex(root2Over2*(real(o1)-imag(o1)), root2Over2*(imag(o1)+real(o1)))
				t2 := complex(-imag(o2), real(o2))
				t3 := complex(-root2Over2*(real(o3)+imag(o3)), root2Over2*(real(o3)-imag(o3)))

				blk[j] = e0 + o0
				blk[j+m] = e1 + t1
				blk[j+2*m] = e2 + t2
				blk[j+3*m] = e3 + t3
				blk[j+4*m] = e0 - o0
				blk[j+5*m] = e1 - t1
				blk[j+6*m] = e2 - t2
				blk[j+7*m] = e3 - t3
			}
		}
	}

	return offset
}

// radix8TailInverseComplex128 is the inverse twin of
// radix8TailForwardComplex128.
func radix8TailInverseComplex128(work, twiddle []complex128, n, tail, offset int) {
	switch tail {
	case 2:
		m := n / 2
		w1 := twiddle[offset : offset+m]

		for j := range m {
			a := work[j]
			b := mathpkg.MulComplex128(w1[j], work[j+m])
			work[j] = a + b
			work[j+m] = a - b
		}

	case 4:
		m := n / 4
		w1 := twiddle[offset : offset+m]
		w2 := twiddle[offset+m : offset+2*m]
		w3 := twiddle[offset+2*m : offset+3*m]

		for j := range m {
			x0 := work[j]
			x1 := mathpkg.MulComplex128(w1[j], work[j+m])
			x2 := mathpkg.MulComplex128(w2[j], work[j+2*m])
			x3 := mathpkg.MulComplex128(w3[j], work[j+3*m])

			t0 := x0 + x2
			t1 := x0 - x2
			t2 := x1 + x3
			t3 := x1 - x3

			work[j] = t0 + t2
			work[j+m] = t1 + complex(-imag(t3), real(t3)) // t1 + i*t3
			work[j+2*m] = t0 - t2
			work[j+3*m] = t1 + complex(imag(t3), -real(t3)) // t1 - i*t3
		}
	}
}
