// Code generated by genkernels from radix4.go. DO NOT EDIT.

package kernels

func forwardRadix4Complex128(dst, src, twiddle, scratch []complex128) bool {
	return radix4Forward[complex128](dst, src, twiddle, scratch)
}

func inverseRadix4Complex128(dst, src, twiddle, scratch []complex128) bool {
	return radix4Inverse[complex128](dst, src, twiddle, scratch)
}

func butterfly4ForwardComplex128(a0, a1, a2, a3 complex128) (complex128, complex128, complex128, complex128) {
	t0 := a0 + a2
	t1 := a0 - a2
	t2 := a1 + a3
	t3 := a1 - a3

	// Multiply by -i: -i*z = -i*(x+iy) = y - ix
	t3NegI := complex(imag(t3), -real(t3))
	// Multiply by i: i*z = i*(x+iy) = -y + ix
	t3I := complex(-imag(t3), real(t3))

	y0 := t0 + t2
	y2 := t0 - t2
	y1 := t1 + t3NegI
	y3 := t1 + t3I

	return y0, y1, y2, y3
}

func butterfly4InverseComplex128(a0, a1, a2, a3 complex128) (complex128, complex128, complex128, complex128) {
	t0 := a0 + a2
	t1 := a0 - a2
	t2 := a1 + a3
	t3 := a1 - a3

	// Multiply by i: i*z = i*(x+iy) = -y + ix
	t3I := complex(-imag(t3), real(t3))
	// Multiply by -i: -i*z = -i*(x+iy) = y - ix
	t3NegI := complex(imag(t3), -real(t3))

	y0 := t0 + t2
	y2 := t0 - t2
	y1 := t1 + t3I
	y3 := t1 + t3NegI

	return y0, y1, y2, y3
}

// Public exports for internal/fft - type-specific functions for direct calls.
func Butterfly4ForwardComplex128(a0, a1, a2, a3 complex128) (complex128, complex128, complex128, complex128) {
	return butterfly4ForwardComplex128(a0, a1, a2, a3)
}

func Butterfly4InverseComplex128(a0, a1, a2, a3 complex128) (complex128, complex128, complex128, complex128) {
	return butterfly4InverseComplex128(a0, a1, a2, a3)
}
