// Code generated by genkernels from radix16.go. DO NOT EDIT.

package kernels

// mulW16Pow1Complex128 multiplies by W16^1 = cos(pi/8) - i*sin(pi/8).
//
// Written out in float32 rather than as mathpkg.MulComplex128 against a constant
// because the generic helper costs 100 inline units against a budget of 80, and
// the ladder calls this once per butterfly. The explicit form is the same four
// multiplies and two adds, it keeps the float64 widening away (which is the
// whole point of MulComplex128), and it inlines.
func mulW16Pow1Complex128(z complex128) complex128 {
	x, y := real(z), imag(z)

	return complex(x*cos16+y*sin16, y*cos16-x*sin16)
}

// mulW16Pow3Complex128 multiplies by W16^3 = sin(pi/8) - i*cos(pi/8).
func mulW16Pow3Complex128(z complex128) complex128 {
	x, y := real(z), imag(z)

	return complex(x*sin16+y*cos16, y*sin16-x*cos16)
}

// mulW16Pow2Complex128 multiplies by W16^2 = (1-i)/sqrt(2). Two real multiplies:
// z*(1-i) = (x+y) + i*(y-x), then scale.
func mulW16Pow2Complex128(z complex128) complex128 {
	x, y := real(z), imag(z)

	return complex((x+y)*sqrt2Half16, (y-x)*sqrt2Half16)
}

// mulW16Pow6Complex128 multiplies by W16^6 = -(1+i)/sqrt(2). Two real multiplies:
// z*(1+i) = (x-y) + i*(x+y), then scale and negate.
func mulW16Pow6Complex128(z complex128) complex128 {
	x, y := real(z), imag(z)

	return complex((y-x)*sqrt2Half16, -(x+y)*sqrt2Half16)
}

// mulNegIComplex128 multiplies by W16^4 = -i, which costs no multiply at all.
func mulNegIComplex128(z complex128) complex128 {
	return complex(imag(z), -real(z))
}

// mulPosIComplex128 multiplies by +i, the inverse-direction twin of the above.
func mulPosIComplex128(z complex128) complex128 {
	return complex(-imag(z), real(z))
}

// butterfly16ForwardComplex128 replaces x with its 16-point DFT, natural order
// in and out.
func butterfly16ForwardComplex128(x *[16]complex128) {
	// Level 1: a radix-4 DFT down each stride-4 column. b<n0><k0>.
	b00, b01, b02, b03 := butterfly4ForwardComplex128(x[0], x[4], x[8], x[12])
	b10, b11, b12, b13 := butterfly4ForwardComplex128(x[1], x[5], x[9], x[13])
	b20, b21, b22, b23 := butterfly4ForwardComplex128(x[2], x[6], x[10], x[14])
	b30, b31, b32, b33 := butterfly4ForwardComplex128(x[3], x[7], x[11], x[15])

	// Twiddle layer: multiply b<n0><k0> by W16^(n0*k0). Row 0 and column 0 are
	// W16^0 = 1 and drop out entirely.
	c11 := mulW16Pow1Complex128(b11)
	c12 := mulW16Pow2Complex128(b12)
	c13 := mulW16Pow3Complex128(b13)

	c21 := mulW16Pow2Complex128(b21)
	c22 := mulNegIComplex128(b22)
	c23 := mulW16Pow6Complex128(b23)

	c31 := mulW16Pow3Complex128(b31)
	c32 := mulW16Pow6Complex128(b32)
	c33 := -mulW16Pow1Complex128(b33) // W16^9 = -W16^1

	// Level 2: a radix-4 DFT across the four columns, for each k0. Output k1 of
	// the k0-th call is X[k0+4*k1].
	x[0], x[4], x[8], x[12] = butterfly4ForwardComplex128(b00, b10, b20, b30)
	x[1], x[5], x[9], x[13] = butterfly4ForwardComplex128(b01, c11, c21, c31)
	x[2], x[6], x[10], x[14] = butterfly4ForwardComplex128(b02, c12, c22, c32)
	x[3], x[7], x[11], x[15] = butterfly4ForwardComplex128(b03, c13, c23, c33)
}

// butterfly16InverseComplex128 replaces x with its unnormalised 16-point inverse
// DFT. Every twiddle is the conjugate of the forward one; the 1/n scaling is
// the ladder's business, not the butterfly's.
func butterfly16InverseComplex128(x *[16]complex128) {
	b00, b01, b02, b03 := butterfly4InverseComplex128(x[0], x[4], x[8], x[12])
	b10, b11, b12, b13 := butterfly4InverseComplex128(x[1], x[5], x[9], x[13])
	b20, b21, b22, b23 := butterfly4InverseComplex128(x[2], x[6], x[10], x[14])
	b30, b31, b32, b33 := butterfly4InverseComplex128(x[3], x[7], x[11], x[15])

	c11 := mulW16PowNeg1Complex128(b11)
	c12 := mulW16PowNeg2Complex128(b12)
	c13 := mulW16PowNeg3Complex128(b13)

	c21 := mulW16PowNeg2Complex128(b21)
	c22 := mulPosIComplex128(b22)
	c23 := mulW16PowNeg6Complex128(b23)

	c31 := mulW16PowNeg3Complex128(b31)
	c32 := mulW16PowNeg6Complex128(b32)
	c33 := -mulW16PowNeg1Complex128(b33)

	x[0], x[4], x[8], x[12] = butterfly4InverseComplex128(b00, b10, b20, b30)
	x[1], x[5], x[9], x[13] = butterfly4InverseComplex128(b01, c11, c21, c31)
	x[2], x[6], x[10], x[14] = butterfly4InverseComplex128(b02, c12, c22, c32)
	x[3], x[7], x[11], x[15] = butterfly4InverseComplex128(b03, c13, c23, c33)
}

// mulW16PowNeg1Complex128 multiplies by W16^-1 = cos(pi/8) + i*sin(pi/8).
func mulW16PowNeg1Complex128(z complex128) complex128 {
	x, y := real(z), imag(z)

	return complex(x*cos16-y*sin16, y*cos16+x*sin16)
}

// mulW16PowNeg3Complex128 multiplies by W16^-3 = sin(pi/8) + i*cos(pi/8).
func mulW16PowNeg3Complex128(z complex128) complex128 {
	x, y := real(z), imag(z)

	return complex(x*sin16-y*cos16, y*sin16+x*cos16)
}

// mulW16PowNeg2Complex128 multiplies by W16^-2 = (1+i)/sqrt(2).
func mulW16PowNeg2Complex128(z complex128) complex128 {
	x, y := real(z), imag(z)

	return complex((x-y)*sqrt2Half16, (x+y)*sqrt2Half16)
}

// mulW16PowNeg6Complex128 multiplies by W16^-6 = -(1-i)/sqrt(2).
func mulW16PowNeg6Complex128(z complex128) complex128 {
	x, y := real(z), imag(z)

	return complex(-(x+y)*sqrt2Half16, (x-y)*sqrt2Half16)
}
