// Code generated by genkernels from radix16_generic.go. DO NOT EDIT.

package kernels

import (
	mathpkg "github.com/cwbudde/algo-fft/internal/math"
	"math"
)

// prepareTwiddleRadix16Complex128 fills dst with the per-stage twiddle planes
// described above. For the inverse transform the imaginary parts are negated,
// which is the conjugate W^-k = conj(W^k), so the stage code is direction-blind
// apart from its butterfly.
func prepareTwiddleRadix16Complex128(n int, inverse bool, dst []complex128) {
	limit, tail, ok := radix16Limit(n)
	if !ok || len(dst) < twiddleSizeRadix16(n) {
		return
	}

	clear(dst[:twiddleSizeRadix16(n)])

	sign := -1.0
	if inverse {
		sign = 1.0
	}

	w := func(e int) complex128 {
		sin, cos := math.Sincos(sign * 2 * math.Pi * float64(e%n) / float64(n))

		return mathpkg.ComplexFromFloat64[complex128](cos, sin)
	}

	offset := 0

	// Radix-16 stages: butterfly j of block d is scaled by W_(16m)^(jd).
	for m := 16; m*16 <= limit; m *= 16 {
		step := n / (16 * m)

		for d := 1; d <= 15; d++ {
			for j := range m {
				dst[offset+j] = w(d * j * step)
			}

			offset += m
		}
	}

	// Tail stage: span n, so its step is 1.
	for d := 1; d < tail; d++ {
		m := n / tail

		for j := range m {
			dst[offset+j] = w(d * j)
		}

		offset += m
	}
}

// radix16PrologueComplex128 validates the arguments common to both directions
// and returns the working buffer, the stage-1 group table and the ladder shape.
func radix16PrologueComplex128(dst, src, twiddle, scratch []complex128) (
	work []complex128, groups []int32, limit, tail int, ok bool,
) {
	n := len(src)

	limit, tail, ok = radix16Limit(n)
	if !ok || len(dst) < n || len(scratch) < n || len(twiddle) < twiddleSizeRadix16(n) {
		return nil, nil, 0, 0, false
	}

	groups = radix16GroupIndices(n)
	if len(groups) != n/16 {
		return nil, nil, 0, 0, false
	}

	work = dst[:n]
	if &dst[0] == &src[0] {
		// Stage 1 gathers, so it cannot write over its own source.
		work = scratch[:n]
	}

	return work, groups, limit, tail, true
}

// forwardRadix16Complex128 is the CodeletFunc entry point for the forward
// transform. twiddle must be the table produced by
// prepareTwiddleRadix16Complex128.
func forwardRadix16Complex128(dst, src, twiddle, scratch []complex128) bool {
	n := len(src)

	work, groups, limit, tail, ok := radix16PrologueComplex128(dst, src, twiddle, scratch)
	if !ok {
		return false
	}

	s := src[:n]
	st := n / 16

	// Stage 1: one twiddle-free butterfly per group, fused with the gather.
	for g, first := range groups {
		p := int(first)

		x0, x1, x2, x3 := s[p], s[p+st], s[p+2*st], s[p+3*st]
		x4, x5, x6, x7 := s[p+4*st], s[p+5*st], s[p+6*st], s[p+7*st]
		x8, x9, x10, x11 := s[p+8*st], s[p+9*st], s[p+10*st], s[p+11*st]
		x12, x13, x14, x15 := s[p+12*st], s[p+13*st], s[p+14*st], s[p+15*st]

		// Level 1: a radix-4 DFT down each stride-4 column. b<n0><k0>.
		u0, u1, u2, u3 := x0+x8, x0-x8, x4+x12, x4-x12
		b00, b02 := u0+u2, u0-u2
		b01 := u1 + complex(imag(u3), -real(u3))
		b03 := u1 + complex(-imag(u3), real(u3))

		v0, v1, v2, v3 := x1+x9, x1-x9, x5+x13, x5-x13
		b10, b12 := v0+v2, v0-v2
		b11 := v1 + complex(imag(v3), -real(v3))
		b13 := v1 + complex(-imag(v3), real(v3))

		q0, q1, q2, q3 := x2+x10, x2-x10, x6+x14, x6-x14
		b20, b22 := q0+q2, q0-q2
		b21 := q1 + complex(imag(q3), -real(q3))
		b23 := q1 + complex(-imag(q3), real(q3))

		z0, z1, z2, z3 := x3+x11, x3-x11, x7+x15, x7-x15
		b30, b32 := z0+z2, z0-z2
		b31 := z1 + complex(imag(z3), -real(z3))
		b33 := z1 + complex(-imag(z3), real(z3))

		// Twiddle layer: b<n0><k0> scaled by W16^(n0*k0). Row 0 and column 0
		// are W16^0 = 1 and drop out.
		c11 := mulW16Pow1Complex128(b11)
		c12 := mulW16Pow2Complex128(b12)
		c13 := mulW16Pow3Complex128(b13)
		c21 := mulW16Pow2Complex128(b21)
		c22 := mulNegIComplex128(b22)
		c23 := mulW16Pow6Complex128(b23)
		c31 := mulW16Pow3Complex128(b31)
		c32 := mulW16Pow6Complex128(b32)
		c33 := -mulW16Pow1Complex128(b33) // W16^9 = -W16^1

		// Level 2: a radix-4 DFT across the four columns, for each k0. Output
		// k1 of the k0-th column is X[k0+4*k1], hence the stride-4 stores.
		r0, r1, r2, r3 := b00+b20, b00-b20, b10+b30, b10-b30
		e0, e1, e2, e3 := b01+c21, b01-c21, c11+c31, c11-c31
		f0, f1, f2, f3 := b02+c22, b02-c22, c12+c32, c12-c32
		g0, g1, g2, g3 := b03+c23, b03-c23, c13+c33, c13-c33

		out := work[16*g : 16*g+16 : 16*g+16]
		out[0] = r0 + r2
		out[1] = e0 + e2
		out[2] = f0 + f2
		out[3] = g0 + g2
		out[4] = r1 + complex(imag(r3), -real(r3))
		out[5] = e1 + complex(imag(e3), -real(e3))
		out[6] = f1 + complex(imag(f3), -real(f3))
		out[7] = g1 + complex(imag(g3), -real(g3))
		out[8] = r0 - r2
		out[9] = e0 - e2
		out[10] = f0 - f2
		out[11] = g0 - g2
		out[12] = r1 + complex(-imag(r3), real(r3))
		out[13] = e1 + complex(-imag(e3), real(e3))
		out[14] = f1 + complex(-imag(f3), real(f3))
		out[15] = g1 + complex(-imag(g3), real(g3))
	}

	offset := radix16StagesForwardComplex128(work, twiddle, n, limit)
	radix16TailForwardComplex128(work, twiddle, n, tail, offset)

	if &work[0] != &dst[0] {
		copy(dst[:n], work)
	}

	return true
}

// radix16StagesForwardComplex128 runs the twiddled radix-16 stages in place and
// returns the number of twiddle elements consumed.
func radix16StagesForwardComplex128(work, twiddle []complex128, n, limit int) int {
	offset := 0

	for m := 16; m*16 <= limit; m *= 16 {
		span := 16 * m

		var w [16][]complex128
		for d := 1; d <= 15; d++ {
			w[d] = twiddle[offset+(d-1)*m : offset+d*m]
		}

		offset += 15 * m

		for base := 0; base < n; base += span {
			blk := work[base : base+span : base+span]

			for j := range m {
				x0 := blk[j]
				x1 := mathpkg.MulComplex128(w[1][j], blk[j+m])
				x2 := mathpkg.MulComplex128(w[2][j], blk[j+2*m])
				x3 := mathpkg.MulComplex128(w[3][j], blk[j+3*m])
				x4 := mathpkg.MulComplex128(w[4][j], blk[j+4*m])
				x5 := mathpkg.MulComplex128(w[5][j], blk[j+5*m])
				x6 := mathpkg.MulComplex128(w[6][j], blk[j+6*m])
				x7 := mathpkg.MulComplex128(w[7][j], blk[j+7*m])
				x8 := mathpkg.MulComplex128(w[8][j], blk[j+8*m])
				x9 := mathpkg.MulComplex128(w[9][j], blk[j+9*m])
				x10 := mathpkg.MulComplex128(w[10][j], blk[j+10*m])
				x11 := mathpkg.MulComplex128(w[11][j], blk[j+11*m])
				x12 := mathpkg.MulComplex128(w[12][j], blk[j+12*m])
				x13 := mathpkg.MulComplex128(w[13][j], blk[j+13*m])
				x14 := mathpkg.MulComplex128(w[14][j], blk[j+14*m])
				x15 := mathpkg.MulComplex128(w[15][j], blk[j+15*m])

				u0, u1, u2, u3 := x0+x8, x0-x8, x4+x12, x4-x12
				b00, b02 := u0+u2, u0-u2
				b01 := u1 + complex(imag(u3), -real(u3))
				b03 := u1 + complex(-imag(u3), real(u3))

				v0, v1, v2, v3 := x1+x9, x1-x9, x5+x13, x5-x13
				b10, b12 := v0+v2, v0-v2
				b11 := v1 + complex(imag(v3), -real(v3))
				b13 := v1 + complex(-imag(v3), real(v3))

				q0, q1, q2, q3 := x2+x10, x2-x10, x6+x14, x6-x14
				b20, b22 := q0+q2, q0-q2
				b21 := q1 + complex(imag(q3), -real(q3))
				b23 := q1 + complex(-imag(q3), real(q3))

				z0, z1, z2, z3 := x3+x11, x3-x11, x7+x15, x7-x15
				b30, b32 := z0+z2, z0-z2
				b31 := z1 + complex(imag(z3), -real(z3))
				b33 := z1 + complex(-imag(z3), real(z3))

				c11 := mulW16Pow1Complex128(b11)
				c12 := mulW16Pow2Complex128(b12)
				c13 := mulW16Pow3Complex128(b13)
				c21 := mulW16Pow2Complex128(b21)
				c22 := mulNegIComplex128(b22)
				c23 := mulW16Pow6Complex128(b23)
				c31 := mulW16Pow3Complex128(b31)
				c32 := mulW16Pow6Complex128(b32)
				c33 := -mulW16Pow1Complex128(b33)

				r0, r1, r2, r3 := b00+b20, b00-b20, b10+b30, b10-b30
				e0, e1, e2, e3 := b01+c21, b01-c21, c11+c31, c11-c31
				f0, f1, f2, f3 := b02+c22, b02-c22, c12+c32, c12-c32
				g0, g1, g2, g3 := b03+c23, b03-c23, c13+c33, c13-c33

				blk[j] = r0 + r2
				blk[j+m] = e0 + e2
				blk[j+2*m] = f0 + f2
				blk[j+3*m] = g0 + g2
				blk[j+4*m] = r1 + complex(imag(r3), -real(r3))
				blk[j+5*m] = e1 + complex(imag(e3), -real(e3))
				blk[j+6*m] = f1 + complex(imag(f3), -real(f3))
				blk[j+7*m] = g1 + complex(imag(g3), -real(g3))
				blk[j+8*m] = r0 - r2
				blk[j+9*m] = e0 - e2
				blk[j+10*m] = f0 - f2
				blk[j+11*m] = g0 - g2
				blk[j+12*m] = r1 + complex(-imag(r3), real(r3))
				blk[j+13*m] = e1 + complex(-imag(e3), real(e3))
				blk[j+14*m] = f1 + complex(-imag(f3), real(f3))
				blk[j+15*m] = g1 + complex(-imag(g3), real(g3))
			}
		}
	}

	return offset
}

// radix16TailForwardComplex128 runs the single widest stage for the shapes that
// need one: radix-2 for n = 2*16^k, radix-4 for 4*16^k, radix-8 for 8*16^k and
// nothing for a power of sixteen.
func radix16TailForwardComplex128(work, twiddle []complex128, n, tail, offset int) {
	switch tail {
	case 2:
		m := n / 2
		w1 := twiddle[offset : offset+m]

		for j := range m {
			a := work[j]
			b := mathpkg.MulComplex128(w1[j], work[j+m])
			work[j] = a + b
			work[j+m] = a - b
		}

	case 4:
		m := n / 4
		w1 := twiddle[offset : offset+m]
		w2 := twiddle[offset+m : offset+2*m]
		w3 := twiddle[offset+2*m : offset+3*m]

		for j := range m {
			x0 := work[j]
			x1 := mathpkg.MulComplex128(w1[j], work[j+m])
			x2 := mathpkg.MulComplex128(w2[j], work[j+2*m])
			x3 := mathpkg.MulComplex128(w3[j], work[j+3*m])

			t0, t1, t2, t3 := x0+x2, x0-x2, x1+x3, x1-x3

			work[j] = t0 + t2
			work[j+m] = t1 + complex(imag(t3), -real(t3)) // t1 - i*t3
			work[j+2*m] = t0 - t2
			work[j+3*m] = t1 + complex(-imag(t3), real(t3)) // t1 + i*t3
		}

	case 8:
		radix16Tail8ForwardComplex128(work, twiddle, n, offset)
	}
}

// radix16Tail8ForwardComplex128 is the radix-8 tail stage, the same butterfly
// radix8_generic.go uses in its own stages.
func radix16Tail8ForwardComplex128(work, twiddle []complex128, n, offset int) {
	m := n / 8

	var w [8][]complex128
	for d := 1; d <= 7; d++ {
		w[d] = twiddle[offset+(d-1)*m : offset+d*m]
	}

	for j := range m {
		x0 := work[j]
		x1 := mathpkg.MulComplex128(w[1][j], work[j+m])
		x2 := mathpkg.MulComplex128(w[2][j], work[j+2*m])
		x3 := mathpkg.MulComplex128(w[3][j], work[j+3*m])
		x4 := mathpkg.MulComplex128(w[4][j], work[j+4*m])
		x5 := mathpkg.MulComplex128(w[5][j], work[j+5*m])
		x6 := mathpkg.MulComplex128(w[6][j], work[j+6*m])
		x7 := mathpkg.MulComplex128(w[7][j], work[j+7*m])

		a0, a1, a2, a3 := x0+x4, x0-x4, x2+x6, x2-x6
		a4, a5, a6, a7 := x1+x5, x1-x5, x3+x7, x3-x7

		e0, e2 := a0+a2, a0-a2
		e1 := a1 + complex(imag(a3), -real(a3)) // a1 - i*a3
		e3 := a1 + complex(-imag(a3), real(a3)) // a1 + i*a3
		o0, o2 := a4+a6, a4-a6
		o1 := a5 + complex(imag(a7), -real(a7))
		o3 := a5 + complex(-imag(a7), real(a7))

		t1 := complex(root2Over2*(real(o1)+imag(o1)), root2Over2*(imag(o1)-real(o1)))
		t2 := complex(imag(o2), -real(o2))
		t3 := complex(root2Over2*(imag(o3)-real(o3)), -root2Over2*(real(o3)+imag(o3)))

		work[j] = e0 + o0
		work[j+m] = e1 + t1
		work[j+2*m] = e2 + t2
		work[j+3*m] = e3 + t3
		work[j+4*m] = e0 - o0
		work[j+5*m] = e1 - t1
		work[j+6*m] = e2 - t2
		work[j+7*m] = e3 - t3
	}
}

// inverseRadix16Complex128 is the CodeletFunc entry point for the inverse
// transform. The 1/n normalisation is exact here (n is a power of two) and is
// folded into the stage-1 gather rather than costing a separate pass over the
// data; by linearity the result is identical either way.
func inverseRadix16Complex128(dst, src, twiddle, scratch []complex128) bool {
	n := len(src)

	work, groups, limit, tail, ok := radix16PrologueComplex128(dst, src, twiddle, scratch)
	if !ok {
		return false
	}

	s := src[:n]
	st := n / 16
	k := 1 / float64(n)

	for g, first := range groups {
		p := int(first)

		// The 1/n scale rides along with the gather: two real multiplies per
		// element, and no extra pass over the buffer.
		d0, d1, d2, d3 := s[p], s[p+st], s[p+2*st], s[p+3*st]
		d4, d5, d6, d7 := s[p+4*st], s[p+5*st], s[p+6*st], s[p+7*st]
		d8, d9, d10, d11 := s[p+8*st], s[p+9*st], s[p+10*st], s[p+11*st]
		d12, d13, d14, d15 := s[p+12*st], s[p+13*st], s[p+14*st], s[p+15*st]

		x0 := complex(real(d0)*k, imag(d0)*k)
		x1 := complex(real(d1)*k, imag(d1)*k)
		x2 := complex(real(d2)*k, imag(d2)*k)
		x3 := complex(real(d3)*k, imag(d3)*k)
		x4 := complex(real(d4)*k, imag(d4)*k)
		x5 := complex(real(d5)*k, imag(d5)*k)
		x6 := complex(real(d6)*k, imag(d6)*k)
		x7 := complex(real(d7)*k, imag(d7)*k)
		x8 := complex(real(d8)*k, imag(d8)*k)
		x9 := complex(real(d9)*k, imag(d9)*k)
		x10 := complex(real(d10)*k, imag(d10)*k)
		x11 := complex(real(d11)*k, imag(d11)*k)
		x12 := complex(real(d12)*k, imag(d12)*k)
		x13 := complex(real(d13)*k, imag(d13)*k)
		x14 := complex(real(d14)*k, imag(d14)*k)
		x15 := complex(real(d15)*k, imag(d15)*k)

		u0, u1, u2, u3 := x0+x8, x0-x8, x4+x12, x4-x12
		b00, b02 := u0+u2, u0-u2
		b01 := u1 + complex(-imag(u3), real(u3))
		b03 := u1 + complex(imag(u3), -real(u3))

		v0, v1, v2, v3 := x1+x9, x1-x9, x5+x13, x5-x13
		b10, b12 := v0+v2, v0-v2
		b11 := v1 + complex(-imag(v3), real(v3))
		b13 := v1 + complex(imag(v3), -real(v3))

		q0, q1, q2, q3 := x2+x10, x2-x10, x6+x14, x6-x14
		b20, b22 := q0+q2, q0-q2
		b21 := q1 + complex(-imag(q3), real(q3))
		b23 := q1 + complex(imag(q3), -real(q3))

		z0, z1, z2, z3 := x3+x11, x3-x11, x7+x15, x7-x15
		b30, b32 := z0+z2, z0-z2
		b31 := z1 + complex(-imag(z3), real(z3))
		b33 := z1 + complex(imag(z3), -real(z3))

		c11 := mulW16PowNeg1Complex128(b11)
		c12 := mulW16PowNeg2Complex128(b12)
		c13 := mulW16PowNeg3Complex128(b13)
		c21 := mulW16PowNeg2Complex128(b21)
		c22 := mulPosIComplex128(b22)
		c23 := mulW16PowNeg6Complex128(b23)
		c31 := mulW16PowNeg3Complex128(b31)
		c32 := mulW16PowNeg6Complex128(b32)
		c33 := -mulW16PowNeg1Complex128(b33)

		r0, r1, r2, r3 := b00+b20, b00-b20, b10+b30, b10-b30
		e0, e1, e2, e3 := b01+c21, b01-c21, c11+c31, c11-c31
		f0, f1, f2, f3 := b02+c22, b02-c22, c12+c32, c12-c32
		g0, g1, g2, g3 := b03+c23, b03-c23, c13+c33, c13-c33

		out := work[16*g : 16*g+16 : 16*g+16]
		out[0] = r0 + r2
		out[1] = e0 + e2
		out[2] = f0 + f2
		out[3] = g0 + g2
		out[4] = r1 + complex(-imag(r3), real(r3))
		out[5] = e1 + complex(-imag(e3), real(e3))
		out[6] = f1 + complex(-imag(f3), real(f3))
		out[7] = g1 + complex(-imag(g3), real(g3))
		out[8] = r0 - r2
		out[9] = e0 - e2
		out[10] = f0 - f2
		out[11] = g0 - g2
		out[12] = r1 + complex(imag(r3), -real(r3))
		out[13] = e1 + complex(imag(e3), -real(e3))
		out[14] = f1 + complex(imag(f3), -real(f3))
		out[15] = g1 + complex(imag(g3), -real(g3))
	}

	offset := radix16StagesInverseComplex128(work, twiddle, n, limit)
	radix16TailInverseComplex128(work, twiddle, n, tail, offset)

	if &work[0] != &dst[0] {
		copy(dst[:n], work)
	}

	return true
}

// radix16StagesInverseComplex128 is the inverse twin of
// radix16StagesForwardComplex128. The twiddles are already conjugated by
// prepareTwiddleRadix16Complex128, so only the butterfly's internal rotations
// differ.
func radix16StagesInverseComplex128(work, twiddle []complex128, n, limit int) int {
	offset := 0

	for m := 16; m*16 <= limit; m *= 16 {
		span := 16 * m

		var w [16][]complex128
		for d := 1; d <= 15; d++ {
			w[d] = twiddle[offset+(d-1)*m : offset+d*m]
		}

		offset += 15 * m

		for base := 0; base < n; base += span {
			blk := work[base : base+span : base+span]

			for j := range m {
				x0 := blk[j]
				x1 := mathpkg.MulComplex128(w[1][j], blk[j+m])
				x2 := mathpkg.MulComplex128(w[2][j], blk[j+2*m])
				x3 := mathpkg.MulComplex128(w[3][j], blk[j+3*m])
				x4 := mathpkg.MulComplex128(w[4][j], blk[j+4*m])
				x5 := mathpkg.MulComplex128(w[5][j], blk[j+5*m])
				x6 := mathpkg.MulComplex128(w[6][j], blk[j+6*m])
				x7 := mathpkg.MulComplex128(w[7][j], blk[j+7*m])
				x8 := mathpkg.MulComplex128(w[8][j], blk[j+8*m])
				x9 := mathpkg.MulComplex128(w[9][j], blk[j+9*m])
				x10 := mathpkg.MulComplex128(w[10][j], blk[j+10*m])
				x11 := mathpkg.MulComplex128(w[11][j], blk[j+11*m])
				x12 := mathpkg.MulComplex128(w[12][j], blk[j+12*m])
				x13 := mathpkg.MulComplex128(w[13][j], blk[j+13*m])
				x14 := mathpkg.MulComplex128(w[14][j], blk[j+14*m])
				x15 := mathpkg.MulComplex128(w[15][j], blk[j+15*m])

				u0, u1, u2, u3 := x0+x8, x0-x8, x4+x12, x4-x12
				b00, b02 := u0+u2, u0-u2
				b01 := u1 + complex(-imag(u3), real(u3))
				b03 := u1 + complex(imag(u3), -real(u3))

				v0, v1, v2, v3 := x1+x9, x1-x9, x5+x13, x5-x13
				b10, b12 := v0+v2, v0-v2
				b11 := v1 + complex(-imag(v3), real(v3))
				b13 := v1 + complex(imag(v3), -real(v3))

				q0, q1, q2, q3 := x2+x10, x2-x10, x6+x14, x6-x14
				b20, b22 := q0+q2, q0-q2
				b21 := q1 + complex(-imag(q3), real(q3))
				b23 := q1 + complex(imag(q3), -real(q3))

				z0, z1, z2, z3 := x3+x11, x3-x11, x7+x15, x7-x15
				b30, b32 := z0+z2, z0-z2
				b31 := z1 + complex(-imag(z3), real(z3))
				b33 := z1 + complex(imag(z3), -real(z3))

				c11 := mulW16PowNeg1Complex128(b11)
				c12 := mulW16PowNeg2Complex128(b12)
				c13 := mulW16PowNeg3Complex128(b13)
				c21 := mulW16PowNeg2Complex128(b21)
				c22 := mulPosIComplex128(b22)
				c23 := mulW16PowNeg6Complex128(b23)
				c31 := mulW16PowNeg3Complex128(b31)
				c32 := mulW16PowNeg6Complex128(b32)
				c33 := -mulW16PowNeg1Complex128(b33)

				r0, r1, r2, r3 := b00+b20, b00-b20, b10+b30, b10-b30
				e0, e1, e2, e3 := b01+c21, b01-c21, c11+c31, c11-c31
				f0, f1, f2, f3 := b02+c22, b02-c22, c12+c32, c12-c32
				g0, g1, g2, g3 := b03+c23, b03-c23, c13+c33, c13-c33

				blk[j] = r0 + r2
				blk[j+m] = e0 + e2
				blk[j+2*m] = f0 + f2
				blk[j+3*m] = g0 + g2
				blk[j+4*m] = r1 + complex(-imag(r3), real(r3))
				blk[j+5*m] = e1 + complex(-imag(e3), real(e3))
				blk[j+6*m] = f1 + complex(-imag(f3), real(f3))
				blk[j+7*m] = g1 + complex(-imag(g3), real(g3))
				blk[j+8*m] = r0 - r2
				blk[j+9*m] = e0 - e2
				blk[j+10*m] = f0 - f2
				blk[j+11*m] = g0 - g2
				blk[j+12*m] = r1 + complex(imag(r3), -real(r3))
				blk[j+13*m] = e1 + complex(imag(e3), -real(e3))
				blk[j+14*m] = f1 + complex(imag(f3), -real(f3))
				blk[j+15*m] = g1 + complex(imag(g3), -real(g3))
			}
		}
	}

	return offset
}

// radix16TailInverseComplex128 is the inverse twin of
// radix16TailForwardComplex128.
func radix16TailInverseComplex128(work, twiddle []complex128, n, tail, offset int) {
	switch tail {
	case 2:
		m := n / 2
		w1 := twiddle[offset : offset+m]

		for j := range m {
			a := work[j]
			b := mathpkg.MulComplex128(w1[j], work[j+m])
			work[j] = a + b
			work[j+m] = a - b
		}

	case 4:
		m := n / 4
		w1 := twiddle[offset : offset+m]
		w2 := twiddle[offset+m : offset+2*m]
		w3 := twiddle[offset+2*m : offset+3*m]

		for j := range m {
			x0 := work[j]
			x1 := mathpkg.MulComplex128(w1[j], work[j+m])
			x2 := mathpkg.MulComplex128(w2[j], work[j+2*m])
			x3 := mathpkg.MulComplex128(w3[j], work[j+3*m])

			t0, t1, t2, t3 := x0+x2, x0-x2, x1+x3, x1-x3

			work[j] = t0 + t2
			work[j+m] = t1 + complex(-imag(t3), real(t3)) // t1 + i*t3
			work[j+2*m] = t0 - t2
			work[j+3*m] = t1 + complex(imag(t3), -real(t3)) // t1 - i*t3
		}

	case 8:
		radix16Tail8InverseComplex128(work, twiddle, n, offset)
	}
}

// radix16Tail8InverseComplex128 is the inverse twin of
// radix16Tail8ForwardComplex128.
func radix16Tail8InverseComplex128(work, twiddle []complex128, n, offset int) {
	m := n / 8

	var w [8][]complex128
	for d := 1; d <= 7; d++ {
		w[d] = twiddle[offset+(d-1)*m : offset+d*m]
	}

	for j := range m {
		x0 := work[j]
		x1 := mathpkg.MulComplex128(w[1][j], work[j+m])
		x2 := mathpkg.MulComplex128(w[2][j], work[j+2*m])
		x3 := mathpkg.MulComplex128(w[3][j], work[j+3*m])
		x4 := mathpkg.MulComplex128(w[4][j], work[j+4*m])
		x5 := mathpkg.MulComplex128(w[5][j], work[j+5*m])
		x6 := mathpkg.MulComplex128(w[6][j], work[j+6*m])
		x7 := mathpkg.MulComplex128(w[7][j], work[j+7*m])

		a0, a1, a2, a3 := x0+x4, x0-x4, x2+x6, x2-x6
		a4, a5, a6, a7 := x1+x5, x1-x5, x3+x7, x3-x7

		e0, e2 := a0+a2, a0-a2
		e1 := a1 + complex(-imag(a3), real(a3)) // a1 + i*a3
		e3 := a1 + complex(imag(a3), -real(a3)) // a1 - i*a3
		o0, o2 := a4+a6, a4-a6
		o1 := a5 + complex(-imag(a7), real(a7))
		o3 := a5 + complex(imag(a7), -real(a7))

		t1 := complex(root2Over2*(real(o1)-imag(o1)), root2Over2*(imag(o1)+real(o1)))
		t2 := complex(-imag(o2), real(o2))
		t3 := complex(-root2Over2*(real(o3)+imag(o3)), root2Over2*(real(o3)-imag(o3)))

		work[j] = e0 + o0
		work[j+m] = e1 + t1
		work[j+2*m] = e2 + t2
		work[j+3*m] = e3 + t3
		work[j+4*m] = e0 - o0
		work[j+5*m] = e1 - t1
		work[j+6*m] = e2 - t2
		work[j+7*m] = e3 - t3
	}
}
