// Code generated by genkernels from radix11.go. DO NOT EDIT.

package kernels

// Butterfly11ForwardComplex128 applies the forward radix-11 DFT butterfly to a
// in place. Inputs must already carry their stage twiddle factors.
func Butterfly11ForwardComplex128(a *[11]complex128) {
	butterfly11Complex128(a, &radix11Fwd128)
}

// Butterfly11InverseComplex128 applies the inverse (conjugate) radix-11 DFT
// butterfly to a in place. No 1/11 scaling is applied.
func Butterfly11InverseComplex128(a *[11]complex128) {
	butterfly11Complex128(a, &radix11Inv128)
}

func butterfly11Complex128(a *[11]complex128, table *[121]complex128) {
	var y [11]complex128

	sum := a[0]
	for k := 1; k < 11; k++ {
		sum += a[k]
	}

	y[0] = sum

	for j := 1; j < 11; j++ {
		acc := a[0]
		row := table[j*11 : j*11+11]

		for k := 1; k < 11; k++ {
			acc += a[k] * row[k]
		}

		y[j] = acc
	}

	*a = y
}
