// Code generated by genkernels from radix8.go. DO NOT EDIT.

package kernels

func butterfly8ForwardComplex128(x0, x1, x2, x3, x4, x5, x6, x7 complex128) (complex128, complex128, complex128, complex128, complex128, complex128, complex128, complex128) {
	a0 := x0 + x4
	a1 := x0 - x4
	a2 := x2 + x6
	a3 := x2 - x6
	a4 := x1 + x5
	a5 := x1 - x5
	a6 := x3 + x7
	a7 := x3 - x7

	e0 := a0 + a2
	e2 := a0 - a2
	e1 := a1 + complex(imag(a3), -real(a3)) // a1 − i·a3
	e3 := a1 + complex(-imag(a3), real(a3)) // a1 + i·a3

	o0 := a4 + a6
	o2 := a4 - a6
	o1 := a5 + complex(imag(a7), -real(a7)) // a5 − i·a7
	o3 := a5 + complex(-imag(a7), real(a7)) // a5 + i·a7

	// t1 = W_8^1·o1, t2 = W_8^2·o2 = −i·o2, t3 = W_8^3·o3
	t1 := complex(root2Over2*(real(o1)+imag(o1)), root2Over2*(imag(o1)-real(o1)))
	t2 := complex(imag(o2), -real(o2))
	t3 := complex(root2Over2*(imag(o3)-real(o3)), -root2Over2*(real(o3)+imag(o3)))

	return e0 + o0, e1 + t1, e2 + t2, e3 + t3, e0 - o0, e1 - t1, e2 - t2, e3 - t3
}

func butterfly8InverseComplex128(x0, x1, x2, x3, x4, x5, x6, x7 complex128) (complex128, complex128, complex128, complex128, complex128, complex128, complex128, complex128) {
	a0 := x0 + x4
	a1 := x0 - x4
	a2 := x2 + x6
	a3 := x2 - x6
	a4 := x1 + x5
	a5 := x1 - x5
	a6 := x3 + x7
	a7 := x3 - x7

	e0 := a0 + a2
	e2 := a0 - a2
	e1 := a1 + complex(-imag(a3), real(a3)) // a1 + i·a3
	e3 := a1 + complex(imag(a3), -real(a3)) // a1 − i·a3

	o0 := a4 + a6
	o2 := a4 - a6
	o1 := a5 + complex(-imag(a7), real(a7)) // a5 + i·a7
	o3 := a5 + complex(imag(a7), -real(a7)) // a5 − i·a7

	// Conjugated roots: t1 = conj(W_8^1)·o1, t2 = i·o2, t3 = conj(W_8^3)·o3
	t1 := complex(root2Over2*(real(o1)-imag(o1)), root2Over2*(imag(o1)+real(o1)))
	t2 := complex(-imag(o2), real(o2))
	t3 := complex(-root2Over2*(real(o3)+imag(o3)), root2Over2*(real(o3)-imag(o3)))

	return e0 + o0, e1 + t1, e2 + t2, e3 + t3, e0 - o0, e1 - t1, e2 - t2, e3 - t3
}

// Butterfly8ForwardComplex128 computes the forward 8-point DFT of eight
// already-twiddled complex128 inputs.
func Butterfly8ForwardComplex128(x0, x1, x2, x3, x4, x5, x6, x7 complex128) (complex128, complex128, complex128, complex128, complex128, complex128, complex128, complex128) {
	return butterfly8ForwardComplex128(x0, x1, x2, x3, x4, x5, x6, x7)
}

// Butterfly8InverseComplex128 computes the inverse (unscaled) 8-point DFT of
// eight already-twiddled complex128 inputs.
func Butterfly8InverseComplex128(x0, x1, x2, x3, x4, x5, x6, x7 complex128) (complex128, complex128, complex128, complex128, complex128, complex128, complex128, complex128) {
	return butterfly8InverseComplex128(x0, x1, x2, x3, x4, x5, x6, x7)
}
