// Code generated by genkernels from splitradix.go. DO NOT EDIT.

package kernels

import (
	mathpkg "github.com/cwbudde/algo-fft/internal/math"
)

func splitRadixForwardRecurseComplex128(dst, src []complex128, stride, step int, twiddle []complex128) {
	n := len(dst)

	if n < splitRadixMinRecurse {
		switch n {
		case 1:
			dst[0] = src[0]
		case 2:
			a, b := src[0], src[stride]
			dst[0] = a + b
			dst[1] = a - b
		case 4:
			e0 := src[0] + src[2*stride]
			e1 := src[0] - src[2*stride]
			u, z := src[stride], src[3*stride]
			t1 := u + z
			d := u - z
			t2 := complex(imag(d), -real(d)) // -i·d
			dst[0] = e0 + t1
			dst[2] = e0 - t1
			dst[1] = e1 + t2
			dst[3] = e1 - t2
		}

		return
	}

	half, quarter := n/2, n/4

	splitRadixForwardRecurseComplex128(dst[:half], src, 2*stride, 2*step, twiddle)
	splitRadixForwardRecurseComplex128(dst[half:half+quarter], src[stride:], 4*stride, 4*step, twiddle)
	splitRadixForwardRecurseComplex128(dst[half+quarter:n], src[3*stride:], 4*stride, 4*step, twiddle)

	// k = 0: both twiddles are 1.
	{
		a, b := dst[half], dst[half+quarter]
		t1 := a + b
		d := a - b
		t2 := complex(imag(d), -real(d))
		e0, e1 := dst[0], dst[quarter]
		dst[0] = e0 + t1
		dst[half] = e0 - t1
		dst[quarter] = e1 + t2
		dst[half+quarter] = e1 - t2
	}

	for k := 1; k < quarter; k++ {
		w1 := twiddle[k*step]
		w3 := twiddle[3*k*step]
		a := mathpkg.MulComplex128(w1, dst[half+k])
		b := mathpkg.MulComplex128(w3, dst[half+quarter+k])
		t1 := a + b
		d := a - b
		t2 := complex(imag(d), -real(d))
		e0, e1 := dst[k], dst[quarter+k]
		dst[k] = e0 + t1
		dst[half+k] = e0 - t1
		dst[quarter+k] = e1 + t2
		dst[half+quarter+k] = e1 - t2
	}
}

func splitRadixInverseRecurseComplex128(dst, src []complex128, stride, step int, twiddle []complex128) {
	n := len(dst)

	if n < splitRadixMinRecurse {
		switch n {
		case 1:
			dst[0] = src[0]
		case 2:
			a, b := src[0], src[stride]
			dst[0] = a + b
			dst[1] = a - b
		case 4:
			e0 := src[0] + src[2*stride]
			e1 := src[0] - src[2*stride]
			u, z := src[stride], src[3*stride]
			t1 := u + z
			d := u - z
			t2 := complex(-imag(d), real(d)) // +i·d
			dst[0] = e0 + t1
			dst[2] = e0 - t1
			dst[1] = e1 + t2
			dst[3] = e1 - t2
		}

		return
	}

	half, quarter := n/2, n/4

	splitRadixInverseRecurseComplex128(dst[:half], src, 2*stride, 2*step, twiddle)
	splitRadixInverseRecurseComplex128(dst[half:half+quarter], src[stride:], 4*stride, 4*step, twiddle)
	splitRadixInverseRecurseComplex128(dst[half+quarter:n], src[3*stride:], 4*stride, 4*step, twiddle)

	{
		a, b := dst[half], dst[half+quarter]
		t1 := a + b
		d := a - b
		t2 := complex(-imag(d), real(d))
		e0, e1 := dst[0], dst[quarter]
		dst[0] = e0 + t1
		dst[half] = e0 - t1
		dst[quarter] = e1 + t2
		dst[half+quarter] = e1 - t2
	}

	for k := 1; k < quarter; k++ {
		w1 := mathpkg.Conj(twiddle[k*step])
		w3 := mathpkg.Conj(twiddle[3*k*step])
		a := mathpkg.MulComplex128(w1, dst[half+k])
		b := mathpkg.MulComplex128(w3, dst[half+quarter+k])
		t1 := a + b
		d := a - b
		t2 := complex(-imag(d), real(d))
		e0, e1 := dst[k], dst[quarter+k]
		dst[k] = e0 + t1
		dst[half+k] = e0 - t1
		dst[quarter+k] = e1 + t2
		dst[half+quarter+k] = e1 - t2
	}
}

// ForwardSplitRadixComplex128 computes an unscaled forward FFT via the
// split-radix recursion. dst and src may alias (scratch is used as the work
// buffer in that case). Output is in natural order.
func ForwardSplitRadixComplex128(dst, src, twiddle, scratch []complex128) bool {
	n, ok := splitRadixValid(dst, src, twiddle, scratch)
	if !ok || n == 0 {
		return ok
	}

	work := dst[:n]
	if SameSlice(dst, src) {
		work = scratch[:n]
	}

	splitRadixForwardRecurseComplex128(work, src[:n], 1, len(twiddle)/n, twiddle)

	if SameSlice(dst, src) {
		copy(dst[:n], work)
	}

	return true
}

// InverseSplitRadixComplex128 is the inverse counterpart of
// ForwardSplitRadixComplex128; the output is scaled by 1/n per the library
// convention.
func InverseSplitRadixComplex128(dst, src, twiddle, scratch []complex128) bool {
	n, ok := splitRadixValid(dst, src, twiddle, scratch)
	if !ok || n == 0 {
		return ok
	}

	work := dst[:n]
	if SameSlice(dst, src) {
		work = scratch[:n]
	}

	splitRadixInverseRecurseComplex128(work, src[:n], 1, len(twiddle)/n, twiddle)

	scale := complex(1/float64(n), 0)
	for i, v := range work {
		dst[i] = mathpkg.MulComplex128(v, scale)
	}

	return true
}
