// Code generated by genkernels from stockham.go. DO NOT EDIT.

package kernels

import (
	mathpkg "github.com/cwbudde/algo-fft/internal/math"
)

func forwardStockhamComplex128(dst, src, twiddle, scratch []complex128) bool {
	return stockhamForward[complex128](dst, src, twiddle, scratch)
}

func inverseStockhamComplex128(dst, src, twiddle, scratch []complex128) bool {
	return stockhamInverseComplex128(dst, src, twiddle, scratch)
}

func stockhamInverseComplex128(dst, src, twiddle, scratch []complex128) bool {
	n := len(src)
	if n == 0 {
		return true
	}

	if len(dst) < n || len(twiddle) < n || len(scratch) < n {
		return false
	}

	if n == 1 {
		dst[0] = src[0]
		return true
	}

	if !mathpkg.IsPowerOf2(n) {
		return false
	}

	in := src
	out := dst
	same := sameSlice(dst, src)
	inIsDst := same
	outIsDst := true

	if same {
		out = scratch
		outIsDst = false
	}

	in = in[:n]
	out = out[:n]
	twiddle = twiddle[:n]

	stages := log2(n)
	halfN := n >> 1

	for s := range stages {
		m := 1 << (stages - s)
		half := m >> 1

		step := n / m

		kLimit := n / m
		for k := range kLimit {
			base := k * m

			outBase := k * half
			inBlock := in[base : base+m]
			outLo := out[outBase : outBase+half]

			outHi := out[outBase+halfN : outBase+halfN+half]
			for j := range half {
				a := inBlock[j]
				b := inBlock[j+half]
				tw := twiddle[j*step]
				tw = complex(real(tw), -imag(tw))
				outLo[j] = a + b
				outHi[j] = mathpkg.MulComplex128(a-b, tw)
			}
		}

		in = out

		inIsDst = outIsDst
		if outIsDst {
			out = scratch
			outIsDst = false
		} else {
			out = dst
			outIsDst = true
		}

		out = out[:n]
	}

	if !inIsDst {
		copy(dst, in)
	}

	scale := complex(1.0/float64(n), 0)
	for i := range dst {
		dst[i] = mathpkg.MulComplex128(dst[i], scale)
	}

	return true
}
